In [1]:
import pandas as pd

import os

from glob import glob

import numpy as np

import shutil

from tqdm import tqdm

pd.set_option('display.max_rows', None)

In [2]:
os.chdir(r'C:\Users\CHAE\OneDrive - 경희대학교\KHU\2023\Forest_Fire_Extraction\참고자료')

In [3]:
df = pd.read_csv('2016_2022_forestfire_area.csv', encoding  = 'utf-8')

In [4]:
df

        산불ID      피해면적 규모구분(대형/중소형)  규모구분(등급)
0    2016001      3.00          중소형         1
1    2016002      1.50          중소형         1
2    2016003      3.00          중소형         1
3    2016004      2.70          중소형         1
4    2016005      2.00          중소형         1
5    2016006      1.50          중소형         1
6    2016007      2.00          중소형         1
7    2016008      1.00          중소형         1
8    2016009     92.60          중소형         3
9    2016010      1.50          중소형         1
10   2016011      8.30          중소형         2
11   2016012      4.00          중소형         1
12   2016013      1.00          중소형         1
13   2016014     14.40          중소형         2
14   2016015      2.60          중소형         1
15   2016016     66.50          중소형         3
16   2016017      1.00          중소형         1
17   2016018      4.80          중소형         1
18   2016019      7.00          중소형         2
19   2016020      1.00          중소형         1
20   2016021      4.70          중소형         1
21   2016022      3.90          중소형         1
22   2016023      2.00          중소형         1
23   2016024     53.80          중소형         3
24   2016025      2.00          중소형         1
25   2016026      1.30          중소형         1
26   2016027      2.00          중소형         1
27   2016028     13.00          중소형         2
28   2016029      2.15          중소형         1
29   2016030      4.50          중소형         1
30   2017001      2.00          중소형         1
31   2017002      1.00          중소형         1
32   2017003    160.41           대형         4
33   2017004      5.20          중소형         2
34   2017005      2.00          중소형         1
35   2017006      3.00          중소형         1
36   2017007      2.00          중소형         1
37   2017008      1.30          중소형         1
38   2017009      1.50          중소형         1
39   2017010      2.20          중소형         1
40   2017011      1.50          중소형         1
41   2017012      1.00          중소형         1
42   2017013      1.00          중소형         1
43   2017014      2.50          중소형         1
44   2017015      2.50          중소형         1
45   2017016      1.00          중소형         1
46   2017017      1.50          중소형         1
47   2017018      1.20          중소형         1
48   2017019      2.00          중소형         1
49   2017020      1.25          중소형         1
50   2017021      1.00          중소형         1
51   2017022      2.00          중소형         1
52   2017023      1.30          중소형         1
53   2017024      1.00          중소형         1
54   2017025      1.50          중소형         1
55   2017026      1.00          중소형         1
56   2017027    252.00           대형         4
57   2017028     86.00          중소형         3
58   2017029    765.12           대형         4
59   2017030      5.90          중소형         2
60   2017031      1.70          중소형         1
61   2017032     24.18          중소형         2
62   2017033      3.12          중소형         1
63   2017034      6.30          중소형         2
64   2017035      6.50          중소형         2
65   2017036      4.80          중소형         1
66   2017037      5.00          중소형         2
67   2017038     18.00          중소형         2
68   2017039      1.89          중소형         1
69   2017040      1.50          중소형         1
70   2017041      3.00          중소형         1
71   2018001     65.00          중소형         3
72   2018002     17.73          중소형         2
73   2018003      3.00          중소형         1
74   2018004      1.00          중소형         1
75   2018005      1.00          중소형         1
76   2018006      1.20          중소형         1
77   2018007      1.50          중소형         1
78   2018008     13.00          중소형         2
79   2018009     76.46          중소형         3
80   2018010    161.14           대형         4
81   2018011      1.00          중소형         1
82   2018012      3.00          중소형         1
83   2018013      7.00          중소형         2
84   2018014      1.00          중소형         1
85   2018015      1.00          중소형         1
86   2018016      1.40          중소형         1
87   2018017      2.50          중소형         1
88   2018018      1.10          중소형         1
89   2018019      1.20          중소형         1
90   2018020     12.40          중소형         2
91   2018021    356.85           대형         4
92   2018022      1.50          중소형         1
93   2018023      2.00          중소형         1
94   2018024     16.10          중소형         2
95   2018025     13.08          중소형         2
96   2018026      1.00          중소형         1
97   2018027      3.00          중소형         1
98   2018028      1.00          중소형         1
99   2018029      3.00          중소형         1
100  2018030      1.50          중소형         1
101  2018031      3.00          중소형         1
102  2018032     31.90          중소형         3
103  2018033      9.40          중소형         2
104  2018034      1.00          중소형         1
105  2018035     27.00          중소형         2
106  2019001     97.94          중소형         3
107  2019002      1.46          중소형         1
108  2019003      5.00          중소형         2
109  2019004      1.00          중소형         1
110  2019005      1.45          중소형         1
111  2019006      9.14          중소형         2
112  2019007      1.50          중소형         1
113  2019008      2.00          중소형         1
114  2019009      1.00          중소형         1
115  2019010      1.00          중소형         1
116  2019011      1.00          중소형         1
117  2019012      1.30          중소형         1
118  2019013      1.00          중소형         1
119  2019014      3.00          중소형         1
120  2019015     22.00          중소형         2
121  2019016      2.00          중소형         1
122  2019017      1.00          중소형         1
123  2019018      1.00          중소형         1
124  2019019     18.44          중소형         2
125  2019020      7.00          중소형         2
126  2019021     56.90          중소형         3
127  2019022      1.00          중소형         1
128  2019023      9.60          중소형         2
129  2019024      3.50          중소형         1
130  2019025      1.00          중소형         1
131  2019026      1.00          중소형         1
132  2019027   1260.15           대형         5
133  2019028   1266.62           대형         5
134  2019029    344.93           대형         4
135  2019030      2.00          중소형         1
136  2019031      4.00          중소형         1
137  2019032      1.30          중소형         1
138  2019033      1.00          중소형         1
139  2019035      4.00          중소형         1
140  2019036      2.00          중소형         1
141  2019037      2.00          중소형         1
142  2019038      1.00          중소형         1
143  2019039      1.50          중소형         1
144  2019040      1.20          중소형         1
145  2019041      1.50          중소형         1
146  2019042      2.00          중소형         1
147  2019043      2.53          중소형         1
148  2019044      5.20          중소형         2
149  2019045      1.50          중소형         1
150  2019046      1.90          중소형         1
151  2019047      1.00          중소형         1
152  2019048      1.50          중소형         1
153  2019049      2.00          중소형         1
154  2019050      1.00          중소형         1
155  2019051      4.70          중소형         1
156  2019052      1.07          중소형         1
157  2020001     34.26          중소형         3
158  2020002      1.35          중소형         1
159  2020003      7.00          중소형         2
160  2020004    519.00           대형         4
161  2020005      2.20          중소형         1
162  2020006      2.68          중소형         1
163  2020007     18.30          중소형         2
164  2020008     10.59          중소형         2
165  2020009      1.40          중소형         1
166  2020010     13.20          중소형         2
167  2020011      9.85          중소형         2
168  2020012      2.11          중소형         1
169  2020013      3.75          중소형         1
170  2020014      6.20          중소형         2
171  2020015      1.70          중소형         1
172  2020016      2.70          중소형         1
173  2020017      1.50          중소형         1
174  2020018     20.00          중소형         2
175  2020019     11.91          중소형         2
176  2020020     48.20          중소형         3
177  2020021      1.20          중소형         1
178  2020022      2.75          중소형         1
179  2020023     19.00          중소형         2
180  2020024      3.56          중소형         1
181  2020025   1944.00           대형         5
182  2020026      1.70          중소형         1
183  2020027      1.82          중소형         1
184  2020028    123.20           대형         4
185  2020029      3.77          중소형         1
186  2020030      2.00          중소형         1
187  2020031      2.00          중소형         1
188  2020032      2.60          중소형         1
189  2020033      3.00          중소형         1
190  2020034      2.00          중소형         1
191  2021001      3.00          중소형         1
192  2021002      4.00          중소형         1
193  2021003      1.50          중소형         1
194  2021004      2.02          중소형         1
195  2021005      3.70          중소형         1
196  2021006      3.00          중소형         1
197  2021007      2.70          중소형         1
198  2021008      3.62          중소형         1
199  2021009     24.56          중소형         2
200  2021010     34.13          중소형         3
201  2021011     74.90          중소형         3
202  2021012    112.00           대형         4
203  2021013    307.00           대형         4
204  2021014     49.15          중소형         3
205  2021015      4.42          중소형         1
206  2021016     20.00          중소형         2
207  2021017      2.00          중소형         1
208  2021018      1.28          중소형         1
209  2021019     10.70          중소형         2
210  2021020      1.40          중소형         1
211  2021021      2.00          중소형         1
212  2021022      1.50          중소형         1
213  2021023     10.00          중소형         2
214  2021024      1.23          중소형         1
215  2021025      5.00          중소형         2
216  2021026      1.27          중소형         1
217  2021027     10.00          중소형         2
218  2021028      4.00          중소형         1
219  2022001      5.50          중소형         2
220  2022002     14.10          중소형         2
221  2022003      4.40          중소형         1
222  2022004      1.45          중소형         1
223  2022005      2.50          중소형         1
224  2022006      1.03          중소형         1
225  2022007      1.15          중소형         1
226  2022008      1.60          중소형         1
227  2022009     12.40          중소형         2
228  2022010      1.37          중소형         1
229  2022011      1.47          중소형         1
230  2022012      1.80          중소형         1
231  2022013      8.53          중소형         2
232  2022014      1.50          중소형         1
233  2022015    405.69           대형         4
234  2022016      9.20          중소형         2
235  2022017      3.95          중소형         1
236  2022018      3.00          중소형         1
237  2022019     10.20          중소형         2
238  2022020      4.10          중소형         1
239  2022021      8.03          중소형         2
240  2022022      2.00          중소형         1
241  2022023     29.00          중소형         2
242  2022024     88.63          중소형         3
243  2022025      8.69          중소형         2
244  2022026     18.50          중소형         2
245  2022027      2.00          중소형         1
246  2022028      1.50          중소형         1
247  2022029      2.00          중소형         1
248  2022030    813.89           대형         4
249  2022031     20.00          중소형         2
250  2022032     30.89          중소형         3
251  2022033     16.30          중소형         2
252  2022034      1.80          중소형         1
253  2022035    184.01           대형         4
254  2022036  16301.98           대형         5
255  2022037      6.54          중소형         2
256  2022038      5.00          중소형         2
257  2022039      3.86          중소형         1
258  2022040      8.00          중소형         2
259  2022041   4190.38           대형         5
260  2022042     11.00          중소형         2
261  2022043      5.00          중소형         2
262  2022044      1.16          중소형         1
263  2022045      8.00          중소형         2
264  2022046      3.00          중소형         1
265  2022047      3.80          중소형         1
266  2022048      1.47          중소형         1
267  2022049      5.00          중소형         2
268  2022050      8.00          중소형         2
269  2022051      3.50          중소형         1
270  2022052    130.00           대형         4
271  2022053      8.00          중소형         2
272  2022054      4.00          중소형         1
273  2022055      1.80          중소형         1
274  2022056      1.50          중소형         1
275  2022057      1.60          중소형         1
276  2022058    158.11           대형         4
277  2022059      3.00          중소형         1
278  2022060    716.31           대형         4
279  2022061      2.50          중소형         1
280  2022062      1.24          중소형         1
281  2022063    225.72           대형         4
282  2022064      3.30          중소형         1
283  2022065      2.00          중소형         1
284  2022066      9.69          중소형         2
285  2022067      2.89          중소형         1
286  2022068      3.18          중소형         1
287  2022069      1.80          중소형         1
288  2022070     70.44          중소형         3
289  2022071      3.00          중소형         1
290  2022072      2.82          중소형         1
291  2022073      5.00          중소형         2
292  2022074      1.44          중소형         1
293  2022075      4.00          중소형         1
294  2022076      2.25          중소형         1
295  2022077      2.50          중소형         1
296  2022078      3.00          중소형         1
297  2022079      1.20          중소형         1
298  2022080      2.80          중소형         1
299  2022081    228.76           대형         4
300  2022082      5.30          중소형         2
301  2022083    660.82           대형         4
302  2022084      5.00          중소형         2
303  2022085      2.00          중소형         1

In [5]:
hist = df.groupby('규모구분(등급)').count()

hist = hist.drop(columns = ['산불ID', '피해면적'], axis = 1)

hist = hist.rename(columns = {'규모구분(대형/중소형)' : '건수'})

In [6]:
hist

           건수
규모구분(등급)
1         197
2          66
3          17
4          19
5           5

In [7]:
hist['비율'] = hist['건수'] /hist['건수'].sum() * 100

hist = hist.round({'비율' : 1})

In [8]:
hist

           건수    비율
규모구분(등급)
1         197  64.8
2          66  21.7
3          17   5.6
4          19   6.2
5           5   1.6

In [9]:
df.loc[df['규모구분(등급)']== 5]

        산불ID      피해면적 규모구분(대형/중소형)  규모구분(등급)
132  2019027   1260.15           대형         5
133  2019028   1266.62           대형         5
181  2020025   1944.00           대형         5
254  2022036  16301.98           대형         5
259  2022041   4190.38           대형         5

In [14]:
df.loc[df['규모구분(등급)']== 4]

        산불ID    피해면적 규모구분(대형/중소형)  규모구분(등급)
32   2017003  160.41           대형         4
56   2017027  252.00           대형         4
58   2017029  765.12           대형         4
80   2018010  161.14           대형         4
91   2018021  356.85           대형         4
134  2019029  344.93           대형         4
160  2020004  519.00           대형         4
184  2020028  123.20           대형         4
202  2021012  112.00           대형         4
203  2021013  307.00           대형         4
233  2022015  405.69           대형         4
248  2022030  813.89           대형         4
253  2022035  184.01           대형         4
270  2022052  130.00           대형         4
276  2022058  158.11           대형         4
278  2022060  716.31           대형         4
281  2022063  225.72           대형         4
299  2022081  228.76           대형         4
301  2022083  660.82           대형         4

In [15]:
df.loc[df['규모구분(등급)']== 3]

        산불ID   피해면적 규모구분(대형/중소형)  규모구분(등급)
8    2016009  92.60          중소형         3
15   2016016  66.50          중소형         3
23   2016024  53.80          중소형         3
57   2017028  86.00          중소형         3
71   2018001  65.00          중소형         3
79   2018009  76.46          중소형         3
102  2018032  31.90          중소형         3
106  2019001  97.94          중소형         3
126  2019021  56.90          중소형         3
157  2020001  34.26          중소형         3
176  2020020  48.20          중소형         3
200  2021010  34.13          중소형         3
201  2021011  74.90          중소형         3
204  2021014  49.15          중소형         3
242  2022024  88.63          중소형         3
250  2022032  30.89          중소형         3
288  2022070  70.44          중소형         3

In [16]:
df.loc[df['규모구분(등급)']== 2]

        산불ID   피해면적 규모구분(대형/중소형)  규모구분(등급)
10   2016011   8.30          중소형         2
13   2016014  14.40          중소형         2
18   2016019   7.00          중소형         2
27   2016028  13.00          중소형         2
33   2017004   5.20          중소형         2
..       ...    ...          ...       ...
271  2022053   8.00          중소형         2
284  2022066   9.69          중소형         2
291  2022073   5.00          중소형         2
300  2022082   5.30          중소형         2
302  2022084   5.00          중소형         2

[66 rows x 4 columns]

In [17]:
df.loc[df['규모구분(등급)']== 1]

        산불ID  피해면적 규모구분(대형/중소형)  규모구분(등급)
0    2016001   3.0          중소형         1
1    2016002   1.5          중소형         1
2    2016003   3.0          중소형         1
3    2016004   2.7          중소형         1
4    2016005   2.0          중소형         1
..       ...   ...          ...       ...
295  2022077   2.5          중소형         1
296  2022078   3.0          중소형         1
297  2022079   1.2          중소형         1
298  2022080   2.8          중소형         1
303  2022085   2.0          중소형         1

[197 rows x 4 columns]

In [10]:
os.getcwd()

'C:\\Users\\CHAE\\OneDrive - 경희대학교\\KHU\\2023\\Forest_Fire_Extraction\\참고자료'

In [5]:
os.chdir(r'D:\deep_learning\Sentinel_forestfire\MY_TEST_SENTINEL_IMAGERY_DATA\imagery_data_complete_0828\data\image')

In [6]:
images = glob('*.tif')

In [7]:
images[0][-11:-4]

'2022027'

In [8]:
images_se = pd.Series(images)

In [9]:
images_se

0      T51SYU_20220226T021651_2022027.tif
1      T51SYU_20220303T021609_2022027.tif
2      T52SBC_20200427T021611_2020027.tif
3      T52SBD_20220402T021559_2022046.tif
4      T52SBE_20170413T021601_2017002.tif
5      T52SBE_20210407T021559_2021017.tif
6      T52SBE_20220522T021609_2022077.tif
7      T52SBF_20220303T021609_2022028.tif
8      T52SBF_20220308T021611_2022038.tif
9      T52SBF_20220417T021611_2022058.tif
10     T52SBG_20160329T022653_2016008.tif
11     T52SBG_20160408T022530_2016008.tif
12     T52SBG_20160508T022702_2016026.tif
13     T52SBG_20161005T021602_2016029.tif
14     T52SBG_20161214T022102_2016030.tif
15     T52SBG_20170324T021601_2017006.tif
16     T52SBG_20170403T022701_2017006.tif
17     T52SBG_20170403T022701_2017013.tif
18     T52SBG_20170503T021611_2017018.tif
19     T52SBG_20170526T022551_2017026.tif
20     T52SBG_20200318T021601_2020003.tif
21     T52SBG_20200323T021559_2020006.tif
22     T52SBG_20200427T021611_2020021.tif
23     T52SCD_20190403T021651_2019020.tif
24     T52SCD_20201208T022059_2020034.tif
25     T52SCD_20210213T020809_2021006.tif
26     T52SCD_20210305T020649_2021014.tif
27     T52SCD_20210414T020649_2021020.tif
28     T52SCD_20210429T020651_2021022.tif
29     T52SCD_20211228T022111_2021027.tif
30     T52SCD_20211230T021059_2021027.tif
31     T52SCD_20220203T020911_2022003.tif
32     T52SCD_20220226T021651_2022022.tif
33     T52SCD_20220226T021651_2022023.tif
34     T52SCD_20220412T021559_2022055.tif
35     T52SCE_20171211T021049_2017037.tif
36     T52SCE_20180217T021741_2018012.tif
37     T52SCE_20180821T021559_2018034.tif
38     T52SCE_20180905T021601_2018034.tif
39     T52SCE_20190408T021609_2019025.tif
40     T52SCE_20200409T020649_2020018.tif
41     T52SCE_20210104T021059_2021001.tif
42     T52SCE_20210107T022059_2021001.tif
43     T52SCE_20210109T021051_2021001.tif
44     T52SCE_20210502T021601_2021023.tif
45     T52SCE_20210509T020651_2021023.tif
46     T52SCE_20220226T021651_2022021.tif
47     T52SCE_20220305T020701_2022033.tif
48     T52SCE_20220315T020701_2022047.tif
49     T52SCE_20220404T020701_2022049.tif
50     T52SCE_20220502T021559_2022073.tif
51     T52SCF_20160408T022530_2016018.tif
52     T52SCF_20170503T021611_2017019.tif
53     T52SCF_20170612T021601_2017033.tif
54     T52SCF_20170727T021559_2017034.tif
55     T52SCF_20171214T022059_2017036.tif
56     T52SCF_20190408T021609_2019032.tif
57     T52SCF_20190418T021609_2019041.tif
58     T52SCF_20190503T021611_2019041.tif
59     T52SCF_20190503T021611_2019042.tif
60     T52SCF_20210226T021639_2021010.tif
61     T52SCF_20210904T021559_2021025.tif
62     T52SCF_20220226T021651_2022012.tif
63     T52SCF_20220417T021611_2022054.tif
64     T52SCF_20220424T020701_2022072.tif
65     T52SCF_20221208T022059_2022084.tif
66     T52SCG_20160309T022651_2016004.tif
67     T52SCG_20160408T021612_2016020.tif
68     T52SCG_20160408T021612_2016022.tif
69     T52SCG_20160408T021612_2016023.tif
70     T52SCG_20160408T022530_2016005.tif
71     T52SCG_20160408T022530_2016011.tif
72     T52SCG_20160408T022530_2016013.tif
73     T52SCG_20160408T022530_2016015.tif
74     T52SCG_20160428T022700_2016019.tif
75     T52SCG_20160428T022702_2016025.tif
76     T52SCG_20170403T022701_2017005.tif
77     T52SCG_20170403T022701_2017007.tif
78     T52SCG_20170403T022701_2017008.tif
79     T52SCG_20170403T022701_2017012.tif
80     T52SCG_20170413T021601_2017014.tif
81     T52SCG_20170413T021601_2017015.tif
82     T52SCG_20170413T021601_2017016.tif
83     T52SCG_20170503T021611_2017021.tif
84     T52SCG_20170503T021611_2017022.tif
85     T52SCG_20170503T021611_2017023.tif
86     T52SCG_20170602T022701_2017023.tif
87     T52SCG_20170602T022701_2017031.tif
88     T52SCG_20180202T021909_2018003.tif
89     T52SCG_20180324T021559_2018018.tif
90     T52SCG_20180428T021611_2018026.tif
91     T52SCG_20180707T021601_2018028.tif
92     T52SCG_20190207T021849_2019005.tif
93     T52SCG_20190314T021601_2019010.tif
94     T52SCG_20190324T021601_2019011.tif
95     T52SCG_20190324T021601_2019013.tif
96     T52SCG_20190408T021609_2019024.tif
97     T52SCG_20190408T021609_2019033.tif
98     T52SCG_20190413T021611_2019039.tif
99     T52SCG_20190523T021611_2019045.tif
100    T52SCG_20200323T021559_2020005.tif
101    T52SCG_20200402T021559_2020013.tif
102    T52SCG_20200407T021601_2020013.tif
103    T52SCG_20200407T021601_2020014.tif
104    T52SCG_20200407T021601_2020016.tif
105    T52SCG_20200427T021611_2020022.tif
106    T52SCG_20200507T021611_2020022.tif
107    T52SCG_20200507T021611_2020024.tif
108    T52SCG_20200527T021611_2020022.tif
109    T52SCG_20201113T021941_2020033.tif
110    T52SCG_20220226T021651_2022018.tif
111    T52SCG_20220308T021611_2022034.tif
112    T52SCG_20220308T021611_2022040.tif
113    T52SCG_20220328T021611_2022043.tif
114    T52SCG_20220407T021601_2022050.tif
115    T52SCG_20220412T021559_2022056.tif
116    T52SCG_20220417T021611_2022053.tif
117    T52SCG_20220417T021611_2022056.tif
118    T52SCG_20220427T021611_2022069.tif
119    T52SCG_20220527T021611_2022075.tif
120    T52SCH_20160408T021612_2016007.tif
121    T52SCH_20160408T022530_2016010.tif
122    T52SCH_20160408T022530_2016019.tif
123    T52SCH_20170413T021601_2017009.tif
124    T52SCH_20170503T021611_2017017.tif
125    T52SCH_20171119T022001_2017035.tif
126    T52SCH_20180413T021559_2018022.tif
127    T52SCH_20180831T021559_2018033.tif
128    T52SCH_20190123T022001_2019002.tif
129    T52SCH_20190128T021949_2019003.tif
130    T52SCH_20190304T021601_2019009.tif
131    T52SCH_20190314T021601_2019009.tif
132    T52SCH_20190403T021651_2019022.tif
133    T52SCH_20190408T021609_2019030.tif
134    T52SCH_20190508T021609_2019047.tif
135    T52SCH_20190508T021609_2019048.tif
136    T52SCH_20190523T021611_2019049.tif
137    T52SCH_20200113T022039_2020001.tif
138    T52SCH_20200118T022021_2020001.tif
139    T52SCH_20200328T021601_2020011.tif
140    T52SCH_20200402T021559_2020012.tif
141    T52SCH_20200422T021559_2020023.tif
142    T52SCH_20220102T022059_2021028.tif
143    T52SCH_20220216T021751_2022008.tif
144    T52SCH_20220417T021611_2022057.tif
145    T52SCH_20220417T021611_2022062.tif
146    T52SCH_20220417T021611_2022064.tif
147    T52SDD_20180130T020919_2018004.tif
148    T52SDD_20180224T020651_2018007.tif
149    T52SDD_20190301T020651_2019008.tif
150    T52SDD_20220208T020829_2022006.tif
151    T52SDD_20220305T020701_2022019.tif
152    T52SDD_20221230T021111_2022085.tif
153    T52SDE_20170321T020651_2017004.tif
154    T52SDE_20170430T020701_2017020.tif
155    T52SDE_20170609T020651_2017032.tif
156    T52SDE_20171221T021059_2017040.tif
157    T52SDE_20180209T020829_2018006.tif
158    T52SDE_20180219T020719_2018014.tif
159    T52SDE_20180222T021709_2018015.tif
160    T52SDE_20180408T021601_2018024.tif
161    T52SDE_20180729T020649_2018030.tif
162    T52SDE_20180801T021649_2018030.tif
163    T52SDE_20190331T030651_2019016.tif
164    T52SDE_20190405T020659_2019026.tif
165    T52SDE_20190415T020659_2019036.tif
166    T52SDE_20190530T020701_2019050.tif
167    T52SDE_20220114T021041_2022001.tif
168    T52SDE_20220203T020911_2022004.tif
169    T52SDE_20220218T020729_2022009.tif
170    T52SDE_20220218T020729_2022013.tif
171    T52SDE_20220218T020729_2022014.tif
172    T52SDE_20220303T021609_2022030.tif
173    T52SDE_20220305T020701_2022024.tif
174    T52SDE_20220305T020701_2022037.tif
175    T52SDE_20220315T020701_2022024.tif
176    T52SDE_20220402T021559_2022048.tif
177    T52SDE_20220417T021611_2022066.tif
178    T52SDE_20220424T020701_2022067.tif
179    T52SDE_20220424T020701_2022068.tif
180    T52SDE_20220504T020701_2022074.tif
181    T52SDE_20220522T021609_2022078.tif
182    T52SDE_20220529T020659_2022080.tif
183    T52SDE_20220601T021559_2022082.tif
184    T52SDE_20220603T020701_2022080.tif
185    T52SDE_20220603T020701_2022083.tif
186    T52SDF_20160215T021228_2016002.tif
187    T52SDF_20160408T021612_2016009.tif
188    T52SDF_20160408T021612_2016016.tif
189    T52SDF_20160408T022530_2016006.tif
190    T52SDF_20160408T022530_2016012.tif
191    T52SDF_20160408T022530_2016024.tif
192    T52SDF_20170314T022651_2017001.tif
193    T52SDF_20170403T022701_2017001.tif
194    T52SDF_20170410T020651_2017010.tif
195    T52SDF_20170410T020651_2017011.tif
196    T52SDF_20170520T020701_2017025.tif
197    T52SDF_20170520T020701_2017028.tif
198    T52SDF_20180202T021909_2018005.tif
199    T52SDF_20180324T021559_2018017.tif
200    T52SDF_20181002T020651_2018032.tif
201    T52SDF_20190319T021659_2019014.tif
202    T52SDF_20190324T021601_2019014.tif
203    T52SDF_20190403T021651_2019015.tif
204    T52SDF_20190403T021651_2019017.tif
205    T52SDF_20190403T021651_2019018.tif
206    T52SDF_20190408T021609_2019038.tif
207    T52SDF_20190415T020659_2019019.tif
208    T52SDF_20190530T020701_2019051.tif
209    T52SDF_20200308T021601_2020002.tif
210    T52SDF_20200323T021559_2020007.tif
211    T52SDF_20200404T020651_2020010.tif
212    T52SDF_20200409T020649_2020020.tif
213    T52SDF_20200427T021611_2020025.tif
214    T52SDF_20200429T020649_2020025.tif
215    T52SDF_20210223T020659_2021011.tif
216    T52SDF_20210223T020659_2021012.tif
217    T52SDF_20210223T020659_2021013.tif
218    T52SDF_20210502T021601_2021021.tif
219    T52SDF_20220112T022039_2022002.tif
220    T52SDF_20220211T021819_2022007.tif
221    T52SDF_20220218T020729_2022011.tif
222    T52SDF_20220223T020701_2022016.tif
223    T52SDF_20220303T021609_2022026.tif
224    T52SDF_20220308T021611_2022039.tif
225    T52SDF_20220407T021601_2022052.tif
226    T52SDF_20220409T020649_2022052.tif
227    T52SDF_20220412T021559_2022052.tif
228    T52SDF_20220419T020649_2022063.tif
229    T52SDF_20220424T020701_2022071.tif
230    T52SDG_20160126T021710_2016001.tif
231    T52SDG_20160218T022652_2016003.tif
232    T52SDG_20160309T022651_2016003.tif
233    T52SDG_20160408T022530_2016017.tif
234    T52SDG_20160408T022530_2016021.tif
235    T52SDG_20160515T020702_2016027.tif
236    T52SDG_20160518T021612_2016027.tif
237    T52SDG_20160528T022702_2016028.tif
238    T52SDG_20170311T021651_2017003.tif
239    T52SDG_20170520T020701_2017027.tif
240    T52SDG_20170520T020701_2017029.tif
241    T52SDG_20190405T020659_2019027.tif
242    T52SDG_20190408T021609_2019027.tif
243    T52SDG_20190408T021609_2019031.tif
244    T52SDG_20190413T021611_2019027.tif
245    T52SDG_20190415T020659_2019027.tif
246    T52SDG_20190508T021609_2019046.tif
247    T52SDG_20200330T020649_2020009.tif
248    T52SDG_20200409T020649_2020019.tif
249    T52SDG_20200427T021611_2020017.tif
250    T52SDG_20200429T020649_2020026.tif
251    T52SDG_20210206T021849_2021004.tif
252    T52SDG_20210208T020851_2021004.tif
253    T52SDG_20210213T020809_2021005.tif
254    T52SDG_20210218T020731_2021007.tif
255    T52SDG_20210221T021721_2021009.tif
256    T52SDG_20210223T020659_2021009.tif
257    T52SDG_20210313T021601_2021015.tif
258    T52SDG_20210402T021601_2021016.tif
259    T52SDG_20210402T021601_2021019.tif
260    T52SDG_20220223T020701_2022017.tif
261    T52SDG_20220228T020649_2022020.tif
262    T52SDG_20220305T020701_2022032.tif
263    T52SDG_20220305T020701_2022035.tif
264    T52SDG_20220305T020701_2022041.tif
265    T52SDG_20220308T021611_2022032.tif
266    T52SDG_20220308T021611_2022035.tif
267    T52SDG_20220310T020649_2022041.tif
268    T52SDG_20220315T020701_2022041.tif
269    T52SDG_20220315T020701_2022045.tif
270    T52SDG_20220524T020701_2022076.tif
271    T52SDG_20220524T020701_2022079.tif
272    T52SDH_20160408T022530_2016014.tif
273    T52SDH_20180115T021021_2018002.tif
274    T52SDH_20180329T021651_2018021.tif
275    T52SDH_20180331T020649_2018021.tif
276    T52SDH_20180420T020649_2018025.tif
277    T52SDH_20180428T021611_2018027.tif
278    T52SDH_20190103T022101_2019001.tif
279    T52SDH_20190128T021949_2019004.tif
280    T52SDH_20190319T021659_2019012.tif
281    T52SDH_20190405T020659_2019028.tif
282    T52SDH_20190408T021609_2019029.tif
283    T52SDH_20190413T021611_2019029.tif
284    T52SDH_20190508T021609_2019044.tif
285    T52SDH_20200502T021559_2020028.tif
286    T52SDH_20200504T020701_2020028.tif
287    T52SDH_20210221T021721_2021008.tif
288    T52SDH_20211115T020941_2021026.tif
289    T52SDH_20220228T020649_2022025.tif
290    T52SDH_20220303T021609_2022025.tif
291    T52SDH_20220417T021611_2022060.tif
292    T52SDH_20220424T020701_2022070.tif
293    T52SEE_20171221T021059_2017038.tif
294    T52SEE_20171221T021059_2017039.tif
295    T52SEE_20171231T021059_2017041.tif
296    T52SEE_20180110T021039_2018001.tif
297    T52SEE_20180214T020801_2018011.tif
298    T52SEE_20180326T020651_2018016.tif
299    T52SEE_20180326T020651_2018019.tif
300    T52SEE_20180331T020649_2018019.tif
301    T52SEE_20180714T020651_2018029.tif
302    T52SEE_20180719T020649_2018029.tif
303    T52SEE_20180818T020649_2018031.tif
304    T52SEE_20190130T020931_2019006.tif
305    T52SEE_20190204T020859_2019006.tif
306    T52SEE_20190405T020659_2019021.tif
307    T52SEE_20190405T020659_2019023.tif
308    T52SEE_20190405T020659_2019035.tif
309    T52SEE_20190415T020659_2019037.tif
310    T52SEE_20190420T020701_2019040.tif
311    T52SEE_20190604T020659_2019052.tif
312    T52SEE_20200320T020649_2020004.tif
313    T52SEE_20200325T020651_2020004.tif
314    T52SEE_20200325T020651_2020008.tif
315    T52SEE_20200623T020701_2020031.tif
316    T52SEE_20210119T021021_2021002.tif
317    T52SEE_20210119T021021_2021003.tif
318    T52SEE_20220203T020911_2022005.tif
319    T52SEE_20220218T020729_2022010.tif
320    T52SEE_20220305T020701_2022029.tif
321    T52SEE_20220305T020701_2022031.tif
322    T52SEE_20220310T020649_2022031.tif
323    T52SEE_20220310T020649_2022042.tif
324    T52SEE_20220404T020701_2022044.tif
325    T52SEE_20220419T020649_2022061.tif
326    T52SEE_20220419T020649_2022065.tif
327    T52SEF_20170520T020701_2017024.tif
328    T52SEF_20170520T020701_2017030.tif
329    T52SEF_20180214T020801_2018008.tif
330    T52SEF_20180219T020719_2018013.tif
331    T52SEF_20180331T020649_2018020.tif
332    T52SEF_20180410T020649_2018023.tif
333    T52SEF_20190204T020859_2019007.tif
334    T52SEF_20190510T020701_2019043.tif
335    T52SEF_20200409T020649_2020015.tif
336    T52SEF_20200603T020701_2020030.tif
337    T52SEF_20201110T020921_2020032.tif
338    T52SEF_20220218T020729_2022015.tif
339    T52SEF_20220404T020701_2022051.tif
340    T52SEG_20180214T020801_2018010.tif
341    T52SEG_20180219T020719_2018009.tif
342    T52SEG_20180219T020719_2018010.tif
343    T52SEG_20181231T021101_2018035.tif
344    T52SEG_20200504T020701_2020029.tif
345    T52SEG_20210414T020649_2021018.tif
346    T52SEG_20210519T020651_2021024.tif
347    T52SEG_20220305T020701_2022036.tif
348    T52SEG_20220310T020649_2022036.tif
349    T52SEG_20220315T020701_2022036.tif
350    T52SEG_20220409T020649_2022059.tif
351    T52SEG_20220419T020649_2022059.tif
352    T52SEG_20220529T020659_2022081.tif
dtype: object

In [10]:
images_df = images_se.to_frame()

In [11]:
images_df

                                      0
0    T51SYU_20220226T021651_2022027.tif
1    T51SYU_20220303T021609_2022027.tif
2    T52SBC_20200427T021611_2020027.tif
3    T52SBD_20220402T021559_2022046.tif
4    T52SBE_20170413T021601_2017002.tif
5    T52SBE_20210407T021559_2021017.tif
6    T52SBE_20220522T021609_2022077.tif
7    T52SBF_20220303T021609_2022028.tif
8    T52SBF_20220308T021611_2022038.tif
9    T52SBF_20220417T021611_2022058.tif
10   T52SBG_20160329T022653_2016008.tif
11   T52SBG_20160408T022530_2016008.tif
12   T52SBG_20160508T022702_2016026.tif
13   T52SBG_20161005T021602_2016029.tif
14   T52SBG_20161214T022102_2016030.tif
15   T52SBG_20170324T021601_2017006.tif
16   T52SBG_20170403T022701_2017006.tif
17   T52SBG_20170403T022701_2017013.tif
18   T52SBG_20170503T021611_2017018.tif
19   T52SBG_20170526T022551_2017026.tif
20   T52SBG_20200318T021601_2020003.tif
21   T52SBG_20200323T021559_2020006.tif
22   T52SBG_20200427T021611_2020021.tif
23   T52SCD_20190403T021651_2019020.tif
24   T52SCD_20201208T022059_2020034.tif
25   T52SCD_20210213T020809_2021006.tif
26   T52SCD_20210305T020649_2021014.tif
27   T52SCD_20210414T020649_2021020.tif
28   T52SCD_20210429T020651_2021022.tif
29   T52SCD_20211228T022111_2021027.tif
30   T52SCD_20211230T021059_2021027.tif
31   T52SCD_20220203T020911_2022003.tif
32   T52SCD_20220226T021651_2022022.tif
33   T52SCD_20220226T021651_2022023.tif
34   T52SCD_20220412T021559_2022055.tif
35   T52SCE_20171211T021049_2017037.tif
36   T52SCE_20180217T021741_2018012.tif
37   T52SCE_20180821T021559_2018034.tif
38   T52SCE_20180905T021601_2018034.tif
39   T52SCE_20190408T021609_2019025.tif
40   T52SCE_20200409T020649_2020018.tif
41   T52SCE_20210104T021059_2021001.tif
42   T52SCE_20210107T022059_2021001.tif
43   T52SCE_20210109T021051_2021001.tif
44   T52SCE_20210502T021601_2021023.tif
45   T52SCE_20210509T020651_2021023.tif
46   T52SCE_20220226T021651_2022021.tif
47   T52SCE_20220305T020701_2022033.tif
48   T52SCE_20220315T020701_2022047.tif
49   T52SCE_20220404T020701_2022049.tif
50   T52SCE_20220502T021559_2022073.tif
51   T52SCF_20160408T022530_2016018.tif
52   T52SCF_20170503T021611_2017019.tif
53   T52SCF_20170612T021601_2017033.tif
54   T52SCF_20170727T021559_2017034.tif
55   T52SCF_20171214T022059_2017036.tif
56   T52SCF_20190408T021609_2019032.tif
57   T52SCF_20190418T021609_2019041.tif
58   T52SCF_20190503T021611_2019041.tif
59   T52SCF_20190503T021611_2019042.tif
60   T52SCF_20210226T021639_2021010.tif
61   T52SCF_20210904T021559_2021025.tif
62   T52SCF_20220226T021651_2022012.tif
63   T52SCF_20220417T021611_2022054.tif
64   T52SCF_20220424T020701_2022072.tif
65   T52SCF_20221208T022059_2022084.tif
66   T52SCG_20160309T022651_2016004.tif
67   T52SCG_20160408T021612_2016020.tif
68   T52SCG_20160408T021612_2016022.tif
69   T52SCG_20160408T021612_2016023.tif
70   T52SCG_20160408T022530_2016005.tif
71   T52SCG_20160408T022530_2016011.tif
72   T52SCG_20160408T022530_2016013.tif
73   T52SCG_20160408T022530_2016015.tif
74   T52SCG_20160428T022700_2016019.tif
75   T52SCG_20160428T022702_2016025.tif
76   T52SCG_20170403T022701_2017005.tif
77   T52SCG_20170403T022701_2017007.tif
78   T52SCG_20170403T022701_2017008.tif
79   T52SCG_20170403T022701_2017012.tif
80   T52SCG_20170413T021601_2017014.tif
81   T52SCG_20170413T021601_2017015.tif
82   T52SCG_20170413T021601_2017016.tif
83   T52SCG_20170503T021611_2017021.tif
84   T52SCG_20170503T021611_2017022.tif
85   T52SCG_20170503T021611_2017023.tif
86   T52SCG_20170602T022701_2017023.tif
87   T52SCG_20170602T022701_2017031.tif
88   T52SCG_20180202T021909_2018003.tif
89   T52SCG_20180324T021559_2018018.tif
90   T52SCG_20180428T021611_2018026.tif
91   T52SCG_20180707T021601_2018028.tif
92   T52SCG_20190207T021849_2019005.tif
93   T52SCG_20190314T021601_2019010.tif
94   T52SCG_20190324T021601_2019011.tif
95   T52SCG_20190324T021601_2019013.tif
96   T52SCG_20190408T021609_2019024.tif
97   T52SCG_20190408T021609_2019033.tif
98   T52SCG_20190413T021611_2019039.tif
99   T52SCG_20190523T021611_2019045.tif
100  T52SCG_20200323T021559_2020005.tif
101  T52SCG_20200402T021559_2020013.tif
102  T52SCG_20200407T021601_2020013.tif
103  T52SCG_20200407T021601_2020014.tif
104  T52SCG_20200407T021601_2020016.tif
105  T52SCG_20200427T021611_2020022.tif
106  T52SCG_20200507T021611_2020022.tif
107  T52SCG_20200507T021611_2020024.tif
108  T52SCG_20200527T021611_2020022.tif
109  T52SCG_20201113T021941_2020033.tif
110  T52SCG_20220226T021651_2022018.tif
111  T52SCG_20220308T021611_2022034.tif
112  T52SCG_20220308T021611_2022040.tif
113  T52SCG_20220328T021611_2022043.tif
114  T52SCG_20220407T021601_2022050.tif
115  T52SCG_20220412T021559_2022056.tif
116  T52SCG_20220417T021611_2022053.tif
117  T52SCG_20220417T021611_2022056.tif
118  T52SCG_20220427T021611_2022069.tif
119  T52SCG_20220527T021611_2022075.tif
120  T52SCH_20160408T021612_2016007.tif
121  T52SCH_20160408T022530_2016010.tif
122  T52SCH_20160408T022530_2016019.tif
123  T52SCH_20170413T021601_2017009.tif
124  T52SCH_20170503T021611_2017017.tif
125  T52SCH_20171119T022001_2017035.tif
126  T52SCH_20180413T021559_2018022.tif
127  T52SCH_20180831T021559_2018033.tif
128  T52SCH_20190123T022001_2019002.tif
129  T52SCH_20190128T021949_2019003.tif
130  T52SCH_20190304T021601_2019009.tif
131  T52SCH_20190314T021601_2019009.tif
132  T52SCH_20190403T021651_2019022.tif
133  T52SCH_20190408T021609_2019030.tif
134  T52SCH_20190508T021609_2019047.tif
135  T52SCH_20190508T021609_2019048.tif
136  T52SCH_20190523T021611_2019049.tif
137  T52SCH_20200113T022039_2020001.tif
138  T52SCH_20200118T022021_2020001.tif
139  T52SCH_20200328T021601_2020011.tif
140  T52SCH_20200402T021559_2020012.tif
141  T52SCH_20200422T021559_2020023.tif
142  T52SCH_20220102T022059_2021028.tif
143  T52SCH_20220216T021751_2022008.tif
144  T52SCH_20220417T021611_2022057.tif
145  T52SCH_20220417T021611_2022062.tif
146  T52SCH_20220417T021611_2022064.tif
147  T52SDD_20180130T020919_2018004.tif
148  T52SDD_20180224T020651_2018007.tif
149  T52SDD_20190301T020651_2019008.tif
150  T52SDD_20220208T020829_2022006.tif
151  T52SDD_20220305T020701_2022019.tif
152  T52SDD_20221230T021111_2022085.tif
153  T52SDE_20170321T020651_2017004.tif
154  T52SDE_20170430T020701_2017020.tif
155  T52SDE_20170609T020651_2017032.tif
156  T52SDE_20171221T021059_2017040.tif
157  T52SDE_20180209T020829_2018006.tif
158  T52SDE_20180219T020719_2018014.tif
159  T52SDE_20180222T021709_2018015.tif
160  T52SDE_20180408T021601_2018024.tif
161  T52SDE_20180729T020649_2018030.tif
162  T52SDE_20180801T021649_2018030.tif
163  T52SDE_20190331T030651_2019016.tif
164  T52SDE_20190405T020659_2019026.tif
165  T52SDE_20190415T020659_2019036.tif
166  T52SDE_20190530T020701_2019050.tif
167  T52SDE_20220114T021041_2022001.tif
168  T52SDE_20220203T020911_2022004.tif
169  T52SDE_20220218T020729_2022009.tif
170  T52SDE_20220218T020729_2022013.tif
171  T52SDE_20220218T020729_2022014.tif
172  T52SDE_20220303T021609_2022030.tif
173  T52SDE_20220305T020701_2022024.tif
174  T52SDE_20220305T020701_2022037.tif
175  T52SDE_20220315T020701_2022024.tif
176  T52SDE_20220402T021559_2022048.tif
177  T52SDE_20220417T021611_2022066.tif
178  T52SDE_20220424T020701_2022067.tif
179  T52SDE_20220424T020701_2022068.tif
180  T52SDE_20220504T020701_2022074.tif
181  T52SDE_20220522T021609_2022078.tif
182  T52SDE_20220529T020659_2022080.tif
183  T52SDE_20220601T021559_2022082.tif
184  T52SDE_20220603T020701_2022080.tif
185  T52SDE_20220603T020701_2022083.tif
186  T52SDF_20160215T021228_2016002.tif
187  T52SDF_20160408T021612_2016009.tif
188  T52SDF_20160408T021612_2016016.tif
189  T52SDF_20160408T022530_2016006.tif
190  T52SDF_20160408T022530_2016012.tif
191  T52SDF_20160408T022530_2016024.tif
192  T52SDF_20170314T022651_2017001.tif
193  T52SDF_20170403T022701_2017001.tif
194  T52SDF_20170410T020651_2017010.tif
195  T52SDF_20170410T020651_2017011.tif
196  T52SDF_20170520T020701_2017025.tif
197  T52SDF_20170520T020701_2017028.tif
198  T52SDF_20180202T021909_2018005.tif
199  T52SDF_20180324T021559_2018017.tif
200  T52SDF_20181002T020651_2018032.tif
201  T52SDF_20190319T021659_2019014.tif
202  T52SDF_20190324T021601_2019014.tif
203  T52SDF_20190403T021651_2019015.tif
204  T52SDF_20190403T021651_2019017.tif
205  T52SDF_20190403T021651_2019018.tif
206  T52SDF_20190408T021609_2019038.tif
207  T52SDF_20190415T020659_2019019.tif
208  T52SDF_20190530T020701_2019051.tif
209  T52SDF_20200308T021601_2020002.tif
210  T52SDF_20200323T021559_2020007.tif
211  T52SDF_20200404T020651_2020010.tif
212  T52SDF_20200409T020649_2020020.tif
213  T52SDF_20200427T021611_2020025.tif
214  T52SDF_20200429T020649_2020025.tif
215  T52SDF_20210223T020659_2021011.tif
216  T52SDF_20210223T020659_2021012.tif
217  T52SDF_20210223T020659_2021013.tif
218  T52SDF_20210502T021601_2021021.tif
219  T52SDF_20220112T022039_2022002.tif
220  T52SDF_20220211T021819_2022007.tif
221  T52SDF_20220218T020729_2022011.tif
222  T52SDF_20220223T020701_2022016.tif
223  T52SDF_20220303T021609_2022026.tif
224  T52SDF_20220308T021611_2022039.tif
225  T52SDF_20220407T021601_2022052.tif
226  T52SDF_20220409T020649_2022052.tif
227  T52SDF_20220412T021559_2022052.tif
228  T52SDF_20220419T020649_2022063.tif
229  T52SDF_20220424T020701_2022071.tif
230  T52SDG_20160126T021710_2016001.tif
231  T52SDG_20160218T022652_2016003.tif
232  T52SDG_20160309T022651_2016003.tif
233  T52SDG_20160408T022530_2016017.tif
234  T52SDG_20160408T022530_2016021.tif
235  T52SDG_20160515T020702_2016027.tif
236  T52SDG_20160518T021612_2016027.tif
237  T52SDG_20160528T022702_2016028.tif
238  T52SDG_20170311T021651_2017003.tif
239  T52SDG_20170520T020701_2017027.tif
240  T52SDG_20170520T020701_2017029.tif
241  T52SDG_20190405T020659_2019027.tif
242  T52SDG_20190408T021609_2019027.tif
243  T52SDG_20190408T021609_2019031.tif
244  T52SDG_20190413T021611_2019027.tif
245  T52SDG_20190415T020659_2019027.tif
246  T52SDG_20190508T021609_2019046.tif
247  T52SDG_20200330T020649_2020009.tif
248  T52SDG_20200409T020649_2020019.tif
249  T52SDG_20200427T021611_2020017.tif
250  T52SDG_20200429T020649_2020026.tif
251  T52SDG_20210206T021849_2021004.tif
252  T52SDG_20210208T020851_2021004.tif
253  T52SDG_20210213T020809_2021005.tif
254  T52SDG_20210218T020731_2021007.tif
255  T52SDG_20210221T021721_2021009.tif
256  T52SDG_20210223T020659_2021009.tif
257  T52SDG_20210313T021601_2021015.tif
258  T52SDG_20210402T021601_2021016.tif
259  T52SDG_20210402T021601_2021019.tif
260  T52SDG_20220223T020701_2022017.tif
261  T52SDG_20220228T020649_2022020.tif
262  T52SDG_20220305T020701_2022032.tif
263  T52SDG_20220305T020701_2022035.tif
264  T52SDG_20220305T020701_2022041.tif
265  T52SDG_20220308T021611_2022032.tif
266  T52SDG_20220308T021611_2022035.tif
267  T52SDG_20220310T020649_2022041.tif
268  T52SDG_20220315T020701_2022041.tif
269  T52SDG_20220315T020701_2022045.tif
270  T52SDG_20220524T020701_2022076.tif
271  T52SDG_20220524T020701_2022079.tif
272  T52SDH_20160408T022530_2016014.tif
273  T52SDH_20180115T021021_2018002.tif
274  T52SDH_20180329T021651_2018021.tif
275  T52SDH_20180331T020649_2018021.tif
276  T52SDH_20180420T020649_2018025.tif
277  T52SDH_20180428T021611_2018027.tif
278  T52SDH_20190103T022101_2019001.tif
279  T52SDH_20190128T021949_2019004.tif
280  T52SDH_20190319T021659_2019012.tif
281  T52SDH_20190405T020659_2019028.tif
282  T52SDH_20190408T021609_2019029.tif
283  T52SDH_20190413T021611_2019029.tif
284  T52SDH_20190508T021609_2019044.tif
285  T52SDH_20200502T021559_2020028.tif
286  T52SDH_20200504T020701_2020028.tif
287  T52SDH_20210221T021721_2021008.tif
288  T52SDH_20211115T020941_2021026.tif
289  T52SDH_20220228T020649_2022025.tif
290  T52SDH_20220303T021609_2022025.tif
291  T52SDH_20220417T021611_2022060.tif
292  T52SDH_20220424T020701_2022070.tif
293  T52SEE_20171221T021059_2017038.tif
294  T52SEE_20171221T021059_2017039.tif
295  T52SEE_20171231T021059_2017041.tif
296  T52SEE_20180110T021039_2018001.tif
297  T52SEE_20180214T020801_2018011.tif
298  T52SEE_20180326T020651_2018016.tif
299  T52SEE_20180326T020651_2018019.tif
300  T52SEE_20180331T020649_2018019.tif
301  T52SEE_20180714T020651_2018029.tif
302  T52SEE_20180719T020649_2018029.tif
303  T52SEE_20180818T020649_2018031.tif
304  T52SEE_20190130T020931_2019006.tif
305  T52SEE_20190204T020859_2019006.tif
306  T52SEE_20190405T020659_2019021.tif
307  T52SEE_20190405T020659_2019023.tif
308  T52SEE_20190405T020659_2019035.tif
309  T52SEE_20190415T020659_2019037.tif
310  T52SEE_20190420T020701_2019040.tif
311  T52SEE_20190604T020659_2019052.tif
312  T52SEE_20200320T020649_2020004.tif
313  T52SEE_20200325T020651_2020004.tif
314  T52SEE_20200325T020651_2020008.tif
315  T52SEE_20200623T020701_2020031.tif
316  T52SEE_20210119T021021_2021002.tif
317  T52SEE_20210119T021021_2021003.tif
318  T52SEE_20220203T020911_2022005.tif
319  T52SEE_20220218T020729_2022010.tif
320  T52SEE_20220305T020701_2022029.tif
321  T52SEE_20220305T020701_2022031.tif
322  T52SEE_20220310T020649_2022031.tif
323  T52SEE_20220310T020649_2022042.tif
324  T52SEE_20220404T020701_2022044.tif
325  T52SEE_20220419T020649_2022061.tif
326  T52SEE_20220419T020649_2022065.tif
327  T52SEF_20170520T020701_2017024.tif
328  T52SEF_20170520T020701_2017030.tif
329  T52SEF_20180214T020801_2018008.tif
330  T52SEF_20180219T020719_2018013.tif
331  T52SEF_20180331T020649_2018020.tif
332  T52SEF_20180410T020649_2018023.tif
333  T52SEF_20190204T020859_2019007.tif
334  T52SEF_20190510T020701_2019043.tif
335  T52SEF_20200409T020649_2020015.tif
336  T52SEF_20200603T020701_2020030.tif
337  T52SEF_20201110T020921_2020032.tif
338  T52SEF_20220218T020729_2022015.tif
339  T52SEF_20220404T020701_2022051.tif
340  T52SEG_20180214T020801_2018010.tif
341  T52SEG_20180219T020719_2018009.tif
342  T52SEG_20180219T020719_2018010.tif
343  T52SEG_20181231T021101_2018035.tif
344  T52SEG_20200504T020701_2020029.tif
345  T52SEG_20210414T020649_2021018.tif
346  T52SEG_20210519T020651_2021024.tif
347  T52SEG_20220305T020701_2022036.tif
348  T52SEG_20220310T020649_2022036.tif
349  T52SEG_20220315T020701_2022036.tif
350  T52SEG_20220409T020649_2022059.tif
351  T52SEG_20220419T020649_2022059.tif
352  T52SEG_20220529T020659_2022081.tif

In [12]:
images_df = images_df.rename(columns = {0 : 'filename'})

In [13]:
images_df['file_id'] = ''
for index, row in images_df.iterrows():
    fileid = row['filename'][-11:-4]
    images_df.at[index, 'file_id'] = fileid

In [14]:
images_df

                               filename  file_id
0    T51SYU_20220226T021651_2022027.tif  2022027
1    T51SYU_20220303T021609_2022027.tif  2022027
2    T52SBC_20200427T021611_2020027.tif  2020027
3    T52SBD_20220402T021559_2022046.tif  2022046
4    T52SBE_20170413T021601_2017002.tif  2017002
5    T52SBE_20210407T021559_2021017.tif  2021017
6    T52SBE_20220522T021609_2022077.tif  2022077
7    T52SBF_20220303T021609_2022028.tif  2022028
8    T52SBF_20220308T021611_2022038.tif  2022038
9    T52SBF_20220417T021611_2022058.tif  2022058
10   T52SBG_20160329T022653_2016008.tif  2016008
11   T52SBG_20160408T022530_2016008.tif  2016008
12   T52SBG_20160508T022702_2016026.tif  2016026
13   T52SBG_20161005T021602_2016029.tif  2016029
14   T52SBG_20161214T022102_2016030.tif  2016030
15   T52SBG_20170324T021601_2017006.tif  2017006
16   T52SBG_20170403T022701_2017006.tif  2017006
17   T52SBG_20170403T022701_2017013.tif  2017013
18   T52SBG_20170503T021611_2017018.tif  2017018
19   T52SBG_20170526T022551_2017026.tif  2017026
20   T52SBG_20200318T021601_2020003.tif  2020003
21   T52SBG_20200323T021559_2020006.tif  2020006
22   T52SBG_20200427T021611_2020021.tif  2020021
23   T52SCD_20190403T021651_2019020.tif  2019020
24   T52SCD_20201208T022059_2020034.tif  2020034
25   T52SCD_20210213T020809_2021006.tif  2021006
26   T52SCD_20210305T020649_2021014.tif  2021014
27   T52SCD_20210414T020649_2021020.tif  2021020
28   T52SCD_20210429T020651_2021022.tif  2021022
29   T52SCD_20211228T022111_2021027.tif  2021027
30   T52SCD_20211230T021059_2021027.tif  2021027
31   T52SCD_20220203T020911_2022003.tif  2022003
32   T52SCD_20220226T021651_2022022.tif  2022022
33   T52SCD_20220226T021651_2022023.tif  2022023
34   T52SCD_20220412T021559_2022055.tif  2022055
35   T52SCE_20171211T021049_2017037.tif  2017037
36   T52SCE_20180217T021741_2018012.tif  2018012
37   T52SCE_20180821T021559_2018034.tif  2018034
38   T52SCE_20180905T021601_2018034.tif  2018034
39   T52SCE_20190408T021609_2019025.tif  2019025
40   T52SCE_20200409T020649_2020018.tif  2020018
41   T52SCE_20210104T021059_2021001.tif  2021001
42   T52SCE_20210107T022059_2021001.tif  2021001
43   T52SCE_20210109T021051_2021001.tif  2021001
44   T52SCE_20210502T021601_2021023.tif  2021023
45   T52SCE_20210509T020651_2021023.tif  2021023
46   T52SCE_20220226T021651_2022021.tif  2022021
47   T52SCE_20220305T020701_2022033.tif  2022033
48   T52SCE_20220315T020701_2022047.tif  2022047
49   T52SCE_20220404T020701_2022049.tif  2022049
50   T52SCE_20220502T021559_2022073.tif  2022073
51   T52SCF_20160408T022530_2016018.tif  2016018
52   T52SCF_20170503T021611_2017019.tif  2017019
53   T52SCF_20170612T021601_2017033.tif  2017033
54   T52SCF_20170727T021559_2017034.tif  2017034
55   T52SCF_20171214T022059_2017036.tif  2017036
56   T52SCF_20190408T021609_2019032.tif  2019032
57   T52SCF_20190418T021609_2019041.tif  2019041
58   T52SCF_20190503T021611_2019041.tif  2019041
59   T52SCF_20190503T021611_2019042.tif  2019042
60   T52SCF_20210226T021639_2021010.tif  2021010
61   T52SCF_20210904T021559_2021025.tif  2021025
62   T52SCF_20220226T021651_2022012.tif  2022012
63   T52SCF_20220417T021611_2022054.tif  2022054
64   T52SCF_20220424T020701_2022072.tif  2022072
65   T52SCF_20221208T022059_2022084.tif  2022084
66   T52SCG_20160309T022651_2016004.tif  2016004
67   T52SCG_20160408T021612_2016020.tif  2016020
68   T52SCG_20160408T021612_2016022.tif  2016022
69   T52SCG_20160408T021612_2016023.tif  2016023
70   T52SCG_20160408T022530_2016005.tif  2016005
71   T52SCG_20160408T022530_2016011.tif  2016011
72   T52SCG_20160408T022530_2016013.tif  2016013
73   T52SCG_20160408T022530_2016015.tif  2016015
74   T52SCG_20160428T022700_2016019.tif  2016019
75   T52SCG_20160428T022702_2016025.tif  2016025
76   T52SCG_20170403T022701_2017005.tif  2017005
77   T52SCG_20170403T022701_2017007.tif  2017007
78   T52SCG_20170403T022701_2017008.tif  2017008
79   T52SCG_20170403T022701_2017012.tif  2017012
80   T52SCG_20170413T021601_2017014.tif  2017014
81   T52SCG_20170413T021601_2017015.tif  2017015
82   T52SCG_20170413T021601_2017016.tif  2017016
83   T52SCG_20170503T021611_2017021.tif  2017021
84   T52SCG_20170503T021611_2017022.tif  2017022
85   T52SCG_20170503T021611_2017023.tif  2017023
86   T52SCG_20170602T022701_2017023.tif  2017023
87   T52SCG_20170602T022701_2017031.tif  2017031
88   T52SCG_20180202T021909_2018003.tif  2018003
89   T52SCG_20180324T021559_2018018.tif  2018018
90   T52SCG_20180428T021611_2018026.tif  2018026
91   T52SCG_20180707T021601_2018028.tif  2018028
92   T52SCG_20190207T021849_2019005.tif  2019005
93   T52SCG_20190314T021601_2019010.tif  2019010
94   T52SCG_20190324T021601_2019011.tif  2019011
95   T52SCG_20190324T021601_2019013.tif  2019013
96   T52SCG_20190408T021609_2019024.tif  2019024
97   T52SCG_20190408T021609_2019033.tif  2019033
98   T52SCG_20190413T021611_2019039.tif  2019039
99   T52SCG_20190523T021611_2019045.tif  2019045
100  T52SCG_20200323T021559_2020005.tif  2020005
101  T52SCG_20200402T021559_2020013.tif  2020013
102  T52SCG_20200407T021601_2020013.tif  2020013
103  T52SCG_20200407T021601_2020014.tif  2020014
104  T52SCG_20200407T021601_2020016.tif  2020016
105  T52SCG_20200427T021611_2020022.tif  2020022
106  T52SCG_20200507T021611_2020022.tif  2020022
107  T52SCG_20200507T021611_2020024.tif  2020024
108  T52SCG_20200527T021611_2020022.tif  2020022
109  T52SCG_20201113T021941_2020033.tif  2020033
110  T52SCG_20220226T021651_2022018.tif  2022018
111  T52SCG_20220308T021611_2022034.tif  2022034
112  T52SCG_20220308T021611_2022040.tif  2022040
113  T52SCG_20220328T021611_2022043.tif  2022043
114  T52SCG_20220407T021601_2022050.tif  2022050
115  T52SCG_20220412T021559_2022056.tif  2022056
116  T52SCG_20220417T021611_2022053.tif  2022053
117  T52SCG_20220417T021611_2022056.tif  2022056
118  T52SCG_20220427T021611_2022069.tif  2022069
119  T52SCG_20220527T021611_2022075.tif  2022075
120  T52SCH_20160408T021612_2016007.tif  2016007
121  T52SCH_20160408T022530_2016010.tif  2016010
122  T52SCH_20160408T022530_2016019.tif  2016019
123  T52SCH_20170413T021601_2017009.tif  2017009
124  T52SCH_20170503T021611_2017017.tif  2017017
125  T52SCH_20171119T022001_2017035.tif  2017035
126  T52SCH_20180413T021559_2018022.tif  2018022
127  T52SCH_20180831T021559_2018033.tif  2018033
128  T52SCH_20190123T022001_2019002.tif  2019002
129  T52SCH_20190128T021949_2019003.tif  2019003
130  T52SCH_20190304T021601_2019009.tif  2019009
131  T52SCH_20190314T021601_2019009.tif  2019009
132  T52SCH_20190403T021651_2019022.tif  2019022
133  T52SCH_20190408T021609_2019030.tif  2019030
134  T52SCH_20190508T021609_2019047.tif  2019047
135  T52SCH_20190508T021609_2019048.tif  2019048
136  T52SCH_20190523T021611_2019049.tif  2019049
137  T52SCH_20200113T022039_2020001.tif  2020001
138  T52SCH_20200118T022021_2020001.tif  2020001
139  T52SCH_20200328T021601_2020011.tif  2020011
140  T52SCH_20200402T021559_2020012.tif  2020012
141  T52SCH_20200422T021559_2020023.tif  2020023
142  T52SCH_20220102T022059_2021028.tif  2021028
143  T52SCH_20220216T021751_2022008.tif  2022008
144  T52SCH_20220417T021611_2022057.tif  2022057
145  T52SCH_20220417T021611_2022062.tif  2022062
146  T52SCH_20220417T021611_2022064.tif  2022064
147  T52SDD_20180130T020919_2018004.tif  2018004
148  T52SDD_20180224T020651_2018007.tif  2018007
149  T52SDD_20190301T020651_2019008.tif  2019008
150  T52SDD_20220208T020829_2022006.tif  2022006
151  T52SDD_20220305T020701_2022019.tif  2022019
152  T52SDD_20221230T021111_2022085.tif  2022085
153  T52SDE_20170321T020651_2017004.tif  2017004
154  T52SDE_20170430T020701_2017020.tif  2017020
155  T52SDE_20170609T020651_2017032.tif  2017032
156  T52SDE_20171221T021059_2017040.tif  2017040
157  T52SDE_20180209T020829_2018006.tif  2018006
158  T52SDE_20180219T020719_2018014.tif  2018014
159  T52SDE_20180222T021709_2018015.tif  2018015
160  T52SDE_20180408T021601_2018024.tif  2018024
161  T52SDE_20180729T020649_2018030.tif  2018030
162  T52SDE_20180801T021649_2018030.tif  2018030
163  T52SDE_20190331T030651_2019016.tif  2019016
164  T52SDE_20190405T020659_2019026.tif  2019026
165  T52SDE_20190415T020659_2019036.tif  2019036
166  T52SDE_20190530T020701_2019050.tif  2019050
167  T52SDE_20220114T021041_2022001.tif  2022001
168  T52SDE_20220203T020911_2022004.tif  2022004
169  T52SDE_20220218T020729_2022009.tif  2022009
170  T52SDE_20220218T020729_2022013.tif  2022013
171  T52SDE_20220218T020729_2022014.tif  2022014
172  T52SDE_20220303T021609_2022030.tif  2022030
173  T52SDE_20220305T020701_2022024.tif  2022024
174  T52SDE_20220305T020701_2022037.tif  2022037
175  T52SDE_20220315T020701_2022024.tif  2022024
176  T52SDE_20220402T021559_2022048.tif  2022048
177  T52SDE_20220417T021611_2022066.tif  2022066
178  T52SDE_20220424T020701_2022067.tif  2022067
179  T52SDE_20220424T020701_2022068.tif  2022068
180  T52SDE_20220504T020701_2022074.tif  2022074
181  T52SDE_20220522T021609_2022078.tif  2022078
182  T52SDE_20220529T020659_2022080.tif  2022080
183  T52SDE_20220601T021559_2022082.tif  2022082
184  T52SDE_20220603T020701_2022080.tif  2022080
185  T52SDE_20220603T020701_2022083.tif  2022083
186  T52SDF_20160215T021228_2016002.tif  2016002
187  T52SDF_20160408T021612_2016009.tif  2016009
188  T52SDF_20160408T021612_2016016.tif  2016016
189  T52SDF_20160408T022530_2016006.tif  2016006
190  T52SDF_20160408T022530_2016012.tif  2016012
191  T52SDF_20160408T022530_2016024.tif  2016024
192  T52SDF_20170314T022651_2017001.tif  2017001
193  T52SDF_20170403T022701_2017001.tif  2017001
194  T52SDF_20170410T020651_2017010.tif  2017010
195  T52SDF_20170410T020651_2017011.tif  2017011
196  T52SDF_20170520T020701_2017025.tif  2017025
197  T52SDF_20170520T020701_2017028.tif  2017028
198  T52SDF_20180202T021909_2018005.tif  2018005
199  T52SDF_20180324T021559_2018017.tif  2018017
200  T52SDF_20181002T020651_2018032.tif  2018032
201  T52SDF_20190319T021659_2019014.tif  2019014
202  T52SDF_20190324T021601_2019014.tif  2019014
203  T52SDF_20190403T021651_2019015.tif  2019015
204  T52SDF_20190403T021651_2019017.tif  2019017
205  T52SDF_20190403T021651_2019018.tif  2019018
206  T52SDF_20190408T021609_2019038.tif  2019038
207  T52SDF_20190415T020659_2019019.tif  2019019
208  T52SDF_20190530T020701_2019051.tif  2019051
209  T52SDF_20200308T021601_2020002.tif  2020002
210  T52SDF_20200323T021559_2020007.tif  2020007
211  T52SDF_20200404T020651_2020010.tif  2020010
212  T52SDF_20200409T020649_2020020.tif  2020020
213  T52SDF_20200427T021611_2020025.tif  2020025
214  T52SDF_20200429T020649_2020025.tif  2020025
215  T52SDF_20210223T020659_2021011.tif  2021011
216  T52SDF_20210223T020659_2021012.tif  2021012
217  T52SDF_20210223T020659_2021013.tif  2021013
218  T52SDF_20210502T021601_2021021.tif  2021021
219  T52SDF_20220112T022039_2022002.tif  2022002
220  T52SDF_20220211T021819_2022007.tif  2022007
221  T52SDF_20220218T020729_2022011.tif  2022011
222  T52SDF_20220223T020701_2022016.tif  2022016
223  T52SDF_20220303T021609_2022026.tif  2022026
224  T52SDF_20220308T021611_2022039.tif  2022039
225  T52SDF_20220407T021601_2022052.tif  2022052
226  T52SDF_20220409T020649_2022052.tif  2022052
227  T52SDF_20220412T021559_2022052.tif  2022052
228  T52SDF_20220419T020649_2022063.tif  2022063
229  T52SDF_20220424T020701_2022071.tif  2022071
230  T52SDG_20160126T021710_2016001.tif  2016001
231  T52SDG_20160218T022652_2016003.tif  2016003
232  T52SDG_20160309T022651_2016003.tif  2016003
233  T52SDG_20160408T022530_2016017.tif  2016017
234  T52SDG_20160408T022530_2016021.tif  2016021
235  T52SDG_20160515T020702_2016027.tif  2016027
236  T52SDG_20160518T021612_2016027.tif  2016027
237  T52SDG_20160528T022702_2016028.tif  2016028
238  T52SDG_20170311T021651_2017003.tif  2017003
239  T52SDG_20170520T020701_2017027.tif  2017027
240  T52SDG_20170520T020701_2017029.tif  2017029
241  T52SDG_20190405T020659_2019027.tif  2019027
242  T52SDG_20190408T021609_2019027.tif  2019027
243  T52SDG_20190408T021609_2019031.tif  2019031
244  T52SDG_20190413T021611_2019027.tif  2019027
245  T52SDG_20190415T020659_2019027.tif  2019027
246  T52SDG_20190508T021609_2019046.tif  2019046
247  T52SDG_20200330T020649_2020009.tif  2020009
248  T52SDG_20200409T020649_2020019.tif  2020019
249  T52SDG_20200427T021611_2020017.tif  2020017
250  T52SDG_20200429T020649_2020026.tif  2020026
251  T52SDG_20210206T021849_2021004.tif  2021004
252  T52SDG_20210208T020851_2021004.tif  2021004
253  T52SDG_20210213T020809_2021005.tif  2021005
254  T52SDG_20210218T020731_2021007.tif  2021007
255  T52SDG_20210221T021721_2021009.tif  2021009
256  T52SDG_20210223T020659_2021009.tif  2021009
257  T52SDG_20210313T021601_2021015.tif  2021015
258  T52SDG_20210402T021601_2021016.tif  2021016
259  T52SDG_20210402T021601_2021019.tif  2021019
260  T52SDG_20220223T020701_2022017.tif  2022017
261  T52SDG_20220228T020649_2022020.tif  2022020
262  T52SDG_20220305T020701_2022032.tif  2022032
263  T52SDG_20220305T020701_2022035.tif  2022035
264  T52SDG_20220305T020701_2022041.tif  2022041
265  T52SDG_20220308T021611_2022032.tif  2022032
266  T52SDG_20220308T021611_2022035.tif  2022035
267  T52SDG_20220310T020649_2022041.tif  2022041
268  T52SDG_20220315T020701_2022041.tif  2022041
269  T52SDG_20220315T020701_2022045.tif  2022045
270  T52SDG_20220524T020701_2022076.tif  2022076
271  T52SDG_20220524T020701_2022079.tif  2022079
272  T52SDH_20160408T022530_2016014.tif  2016014
273  T52SDH_20180115T021021_2018002.tif  2018002
274  T52SDH_20180329T021651_2018021.tif  2018021
275  T52SDH_20180331T020649_2018021.tif  2018021
276  T52SDH_20180420T020649_2018025.tif  2018025
277  T52SDH_20180428T021611_2018027.tif  2018027
278  T52SDH_20190103T022101_2019001.tif  2019001
279  T52SDH_20190128T021949_2019004.tif  2019004
280  T52SDH_20190319T021659_2019012.tif  2019012
281  T52SDH_20190405T020659_2019028.tif  2019028
282  T52SDH_20190408T021609_2019029.tif  2019029
283  T52SDH_20190413T021611_2019029.tif  2019029
284  T52SDH_20190508T021609_2019044.tif  2019044
285  T52SDH_20200502T021559_2020028.tif  2020028
286  T52SDH_20200504T020701_2020028.tif  2020028
287  T52SDH_20210221T021721_2021008.tif  2021008
288  T52SDH_20211115T020941_2021026.tif  2021026
289  T52SDH_20220228T020649_2022025.tif  2022025
290  T52SDH_20220303T021609_2022025.tif  2022025
291  T52SDH_20220417T021611_2022060.tif  2022060
292  T52SDH_20220424T020701_2022070.tif  2022070
293  T52SEE_20171221T021059_2017038.tif  2017038
294  T52SEE_20171221T021059_2017039.tif  2017039
295  T52SEE_20171231T021059_2017041.tif  2017041
296  T52SEE_20180110T021039_2018001.tif  2018001
297  T52SEE_20180214T020801_2018011.tif  2018011
298  T52SEE_20180326T020651_2018016.tif  2018016
299  T52SEE_20180326T020651_2018019.tif  2018019
300  T52SEE_20180331T020649_2018019.tif  2018019
301  T52SEE_20180714T020651_2018029.tif  2018029
302  T52SEE_20180719T020649_2018029.tif  2018029
303  T52SEE_20180818T020649_2018031.tif  2018031
304  T52SEE_20190130T020931_2019006.tif  2019006
305  T52SEE_20190204T020859_2019006.tif  2019006
306  T52SEE_20190405T020659_2019021.tif  2019021
307  T52SEE_20190405T020659_2019023.tif  2019023
308  T52SEE_20190405T020659_2019035.tif  2019035
309  T52SEE_20190415T020659_2019037.tif  2019037
310  T52SEE_20190420T020701_2019040.tif  2019040
311  T52SEE_20190604T020659_2019052.tif  2019052
312  T52SEE_20200320T020649_2020004.tif  2020004
313  T52SEE_20200325T020651_2020004.tif  2020004
314  T52SEE_20200325T020651_2020008.tif  2020008
315  T52SEE_20200623T020701_2020031.tif  2020031
316  T52SEE_20210119T021021_2021002.tif  2021002
317  T52SEE_20210119T021021_2021003.tif  2021003
318  T52SEE_20220203T020911_2022005.tif  2022005
319  T52SEE_20220218T020729_2022010.tif  2022010
320  T52SEE_20220305T020701_2022029.tif  2022029
321  T52SEE_20220305T020701_2022031.tif  2022031
322  T52SEE_20220310T020649_2022031.tif  2022031
323  T52SEE_20220310T020649_2022042.tif  2022042
324  T52SEE_20220404T020701_2022044.tif  2022044
325  T52SEE_20220419T020649_2022061.tif  2022061
326  T52SEE_20220419T020649_2022065.tif  2022065
327  T52SEF_20170520T020701_2017024.tif  2017024
328  T52SEF_20170520T020701_2017030.tif  2017030
329  T52SEF_20180214T020801_2018008.tif  2018008
330  T52SEF_20180219T020719_2018013.tif  2018013
331  T52SEF_20180331T020649_2018020.tif  2018020
332  T52SEF_20180410T020649_2018023.tif  2018023
333  T52SEF_20190204T020859_2019007.tif  2019007
334  T52SEF_20190510T020701_2019043.tif  2019043
335  T52SEF_20200409T020649_2020015.tif  2020015
336  T52SEF_20200603T020701_2020030.tif  2020030
337  T52SEF_20201110T020921_2020032.tif  2020032
338  T52SEF_20220218T020729_2022015.tif  2022015
339  T52SEF_20220404T020701_2022051.tif  2022051
340  T52SEG_20180214T020801_2018010.tif  2018010
341  T52SEG_20180219T020719_2018009.tif  2018009
342  T52SEG_20180219T020719_2018010.tif  2018010
343  T52SEG_20181231T021101_2018035.tif  2018035
344  T52SEG_20200504T020701_2020029.tif  2020029
345  T52SEG_20210414T020649_2021018.tif  2021018
346  T52SEG_20210519T020651_2021024.tif  2021024
347  T52SEG_20220305T020701_2022036.tif  2022036
348  T52SEG_20220310T020649_2022036.tif  2022036
349  T52SEG_20220315T020701_2022036.tif  2022036
350  T52SEG_20220409T020649_2022059.tif  2022059
351  T52SEG_20220419T020649_2022059.tif  2022059
352  T52SEG_20220529T020659_2022081.tif  2022081

In [15]:
images_df.dtypes

filename    object
file_id     object
dtype: object

In [16]:
df.dtypes

산불ID              int64
피해면적            float64
규모구분(대형/중소형)     object
규모구분(등급)          int64
dtype: object

In [17]:
df['산불ID'] = df['산불ID'].astype('str')

In [18]:
new_df = pd.merge(images_df, df, left_on = 'file_id', right_on = '산불ID', how = 'outer')

In [19]:
new_df.dtypes

filename         object
file_id          object
산불ID             object
피해면적            float64
규모구분(대형/중소형)     object
규모구분(등급)          int64
dtype: object

In [20]:
new_df

,filename,file_id,산불ID,피해면적,규모구분(대형/중소형),규모구분(등급)
0,T51SYU_20220226T021651_2022027.tif,2022027,2022027,2.00,중소형,1
1,T51SYU_20220303T021609_2022027.tif,2022027,2022027,2.00,중소형,1
2,T52SBC_20200427T021611_2020027.tif,2020027,2020027,1.82,중소형,1
3,T52SBD_20220402T021559_2022046.tif,2022046,2022046,3.00,중소형,1
4,T52SBE_20170413T021601_2017002.tif,2017002,2017002,1.00,중소형,1
5,T52SBE_20210407T021559_2021017.tif,2021017,2021017,2.00,중소형,1
6,T52SBE_20220522T021609_2022077.tif,2022077,2022077,2.50,중소형,1
7,T52SBF_20220303T021609_2022028.tif,2022028,2022028,1.50,중소형,1
8,T52SBF_20220308T021611_2022038.tif,2022038,2022038,5.00,중소형,2
9,T52SBF_20220417T021611_2022058.tif,2022058,2022058,158.11,대형,4
10,T52SBG_20160329T022653_2016008.tif,2016008,2016008,1.00,중소형,1
11,T52SBG_20160408T022530_2016008.tif,2016008,2016008,1.00,중소형,1
12,T52SBG_20160508T022702_2016026.tif,2016026,2016026,1.30,중소형,1
13,T52SBG_20161005T021602_2016029.tif,2016029,2016029,2.15,중소형,1
14,T52SBG_20161214T022102_2016030.tif,2016030,2016030,4.50,중소형,1
15,T52SBG_20170324T021601_2017006.tif,2017006,2017006,3.00,중소형,1
16,T52SBG_20170403T022701_2017006.tif,2017006,2017006,3.00,중소형,1
17,T52SBG_20170403T022701_2017013.tif,2017013,2017013,1.00,중소형,1
18,T52SBG_20170503T021611_2017018.tif,2017018,2017018,1.20,중소형,1
19,T52SBG_20170526T022551_2017026.tif,2017026,2017026,1.00,중소형,1
20,T52SBG_20200318T021601_2020003.tif,2020003,2020003,7.00,중소형,2
21,T52SBG_20200323T021559_2020006.tif,2020006,2020006,2.68,중소형,1
22,T52SBG_20200427T021611_2020021.tif,2020021,2020021,1.20,중소형,1
23,T52SCD_20190403T021651_2019020.tif,2019020,2019020,7.00,중소형,2
24,T52SCD_20201208T022059_2020034.tif,2020034,2020034,2.00,중소형,1
25,T52SCD_20210213T020809_2021006.tif,2021006,2021006,3.00,중소형,1
26,T52SCD_20210305T020649_2021014.tif,2021014,2021014,49.15,중소형,3
27,T52SCD_20210414T020649_2021020.tif,2021020,2021020,1.40,중소형,1
28,T52SCD_20210429T020651_2021022.tif,2021022,2021022,1.50,중소형,1
29,T52SCD_20211228T022111_2021027.tif,2021027,2021027,10.00,중소형,2
30,T52SCD_20211230T021059_2021027.tif,2021027,2021027,10.00,중소형,2
31,T52SCD_20220203T020911_2022003.tif,2022003,2022003,4.40,중소형,1
32,T52SCD_20220226T021651_2022022.tif,2022022,2022022,2.00,중소형,1
33,T52SCD_20220226T021651_2022023.tif,2022023,2022023,29.00,중소형,2
34,T52SCD_20220412T021559_2022055.tif,2022055,2022055,1.80,중소형,1
35,T52SCE_20171211T021049_2017037.tif,2017037,2017037,5.00,중소형,2
36,T52SCE_20180217T021741_2018012.tif,2018012,2018012,3.00,중소형,1
37,T52SCE_20180821T021559_2018034.tif,2018034,2018034,1.00,중소형,1
38,T52SCE_20180905T021601_2018034.tif,2018034,2018034,1.00,중소형,1
39,T52SCE_20190408T021609_2019025.tif,2019025,2019025,1.00,중소형,1
40,T52SCE_20200409T020649_2020018.tif,2020018,2020018,20.00,중소형,2
41,T52SCE_20210104T021059_2021001.tif,2021001,2021001,3.00,중소형,1
42,T52SCE_20210107T022059_2021001.tif,2021001,2021001,3.00,중소형,1
43,T52SCE_20210109T021051_2021001.tif,2021001,2021001,3.00,중소형,1
44,T52SCE_20210502T021601_2021023.tif,2021023,2021023,10.00,중소형,2
45,T52SCE_20210509T020651_2021023.tif,2021023,2021023,10.00,중소형,2
46,T52SCE_20220226T021651_2022021.tif,2022021,2022021,8.03,중소형,2
47,T52SCE_20220305T020701_2022033.tif,2022033,2022033,16.30,중소형,2
48,T52SCE_20220315T020701_2022047.tif,2022047,2022047,3.80,중소형,1
49,T52SCE_20220404T020701_2022049.tif,2022049,2022049,5.00,중소형,2
50,T52SCE_20220502T021559_2022073.tif,2022073,2022073,5.00,중소형,2
51,T52SCF_20160408T022530_2016018.tif,2016018,2016018,4.80,중소형,1
52,T52SCF_20170503T021611_2017019.tif,2017019,2017019,2.00,중소형,1
53,T52SCF_20170612T021601_2017033.tif,2017033,2017033,3.12,중소형,1
54,T52SCF_20170727T021559_2017034.tif,2017034,2017034,6.30,중소형,2
55,T52SCF_20171214T022059_2017036.tif,2017036,2017036,4.80,중소형,1
56,T52SCF_20190408T021609_2019032.tif,2019032,2019032,1.30,중소형,1
57,T52SCF_20190418T021609_2019041.tif,2019041,2019041,1.50,중소형,1
58,T52SCF_20190503T021611_2019041.tif,2019041,2019041,1.50,중소형,1
59,T52SCF_20190503T021611_2019042.tif,2019042,2019042,2.00,중소형,1
60,T52SCF_20210226T021639_2021010.tif,2021010,2021010,34.13,중소형,3
61,T52SCF_20210904T021559_2021025.tif,2021025,2021025,5.00,중소형,2
62,T52SCF_20220226T021651_2022012.tif,2022012,2022012,1.80,중소형,1
63,T52SCF_20220417T021611_2022054.tif,2022054,2022054,4.00,중소형,1
64,T52SCF_20220424T020701_2022072.tif,2022072,2022072,2.82,중소형,1
65,T52SCF_20221208T022059_2022084.tif,2022084,2022084,5.00,중소형,2
66,T52SCG_20160309T022651_2016004.tif,2016004,2016004,2.70,중소형,1
67,T52SCG_20160408T021612_2016020.tif,2016020,2016020,1.00,중소형,1
68,T52SCG_20160408T021612_2016022.tif,2016022,2016022,3.90,중소형,1
69,T52SCG_20160408T021612_2016023.tif,2016023,2016023,2.00,중소형,1
70,T52SCG_20160408T022530_2016005.tif,2016005,2016005,2.00,중소형,1
71,T52SCG_20160408T022530_2016011.tif,2016011,2016011,8.30,중소형,2
72,T52SCG_20160408T022530_2016013.tif,2016013,2016013,1.00,중소형,1
73,T52SCG_20160408T022530_2016015.tif,2016015,2016015,2.60,중소형,1
74,T52SCG_20160428T022700_2016019.tif,2016019,2016019,7.00,중소형,2
75,T52SCH_20160408T022530_2016019.tif,2016019,2016019,7.00,중소형,2
76,T52SCG_20160428T022702_2016025.tif,2016025,2016025,2.00,중소형,1
77,T52SCG_20170403T022701_2017005.tif,2017005,2017005,2.00,중소형,1
78,T52SCG_20170403T022701_2017007.tif,2017007,2017007,2.00,중소형,1
79,T52SCG_20170403T022701_2017008.tif,2017008,2017008,1.30,중소형,1
80,T52SCG_20170403T022701_2017012.tif,2017012,2017012,1.00,중소형,1
81,T52SCG_20170413T021601_2017014.tif,2017014,2017014,2.50,중소형,1
82,T52SCG_20170413T021601_2017015.tif,2017015,2017015,2.50,중소형,1
83,T52SCG_20170413T021601_2017016.tif,2017016,2017016,1.00,중소형,1
84,T52SCG_20170503T021611_2017021.tif,2017021,2017021,1.00,중소형,1
85,T52SCG_20170503T021611_2017022.tif,2017022,2017022,2.00,중소형,1
86,T52SCG_20170503T021611_2017023.tif,2017023,2017023,1.30,중소형,1
87,T52SCG_20170602T022701_2017023.tif,2017023,2017023,1.30,중소형,1
88,T52SCG_20170602T022701_2017031.tif,2017031,2017031,1.70,중소형,1
89,T52SCG_20180202T021909_2018003.tif,2018003,2018003,3.00,중소형,1
90,T52SCG_20180324T021559_2018018.tif,2018018,2018018,1.10,중소형,1
91,T52SCG_20180428T021611_2018026.tif,2018026,2018026,1.00,중소형,1
92,T52SCG_20180707T021601_2018028.tif,2018028,2018028,1.00,중소형,1
93,T52SCG_20190207T021849_2019005.tif,2019005,2019005,1.45,중소형,1
94,T52SCG_20190314T021601_2019010.tif,2019010,2019010,1.00,중소형,1
95,T52SCG_20190324T021601_2019011.tif,2019011,2019011,1.00,중소형,1
96,T52SCG_20190324T021601_2019013.tif,2019013,2019013,1.00,중소형,1
97,T52SCG_20190408T021609_2019024.tif,2019024,2019024,3.50,중소형,1
98,T52SCG_20190408T021609_2019033.tif,2019033,2019033,1.00,중소형,1
99,T52SCG_20190413T021611_2019039.tif,2019039,2019039,1.50,중소형,1
100,T52SCG_20190523T021611_2019045.tif,2019045,2019045,1.50,중소형,1
101,T52SCG_20200323T021559_2020005.tif,2020005,2020005,2.20,중소형,1
102,T52SCG_20200402T021559_2020013.tif,2020013,2020013,3.75,중소형,1
103,T52SCG_20200407T021601_2020013.tif,2020013,2020013,3.75,중소형,1
104,T52SCG_20200407T021601_2020014.tif,2020014,2020014,6.20,중소형,2
105,T52SCG_20200407T021601_2020016.tif,2020016,2020016,2.70,중소형,1
106,T52SCG_20200427T021611_2020022.tif,2020022,2020022,2.75,중소형,1
107,T52SCG_20200507T021611_2020022.tif,2020022,2020022,2.75,중소형,1
108,T52SCG_20200527T021611_2020022.tif,2020022,2020022,2.75,중소형,1
109,T52SCG_20200507T021611_2020024.tif,2020024,2020024,3.56,중소형,1
110,T52SCG_20201113T021941_2020033.tif,2020033,2020033,3.00,중소형,1
111,T52SCG_20220226T021651_2022018.tif,2022018,2022018,3.00,중소형,1
112,T52SCG_20220308T021611_2022034.tif,2022034,2022034,1.80,중소형,1
113,T52SCG_20220308T021611_2022040.tif,2022040,2022040,8.00,중소형,2
114,T52SCG_20220328T021611_2022043.tif,2022043,2022043,5.00,중소형,2
115,T52SCG_20220407T021601_2022050.tif,2022050,2022050,8.00,중소형,2
116,T52SCG_20220412T021559_2022056.tif,2022056,2022056,1.50,중소형,1
117,T52SCG_20220417T021611_2022056.tif,2022056,2022056,1.50,중소형,1
118,T52SCG_20220417T021611_2022053.tif,2022053,2022053,8.00,중소형,2
119,T52SCG_20220427T021611_2022069.tif,2022069,2022069,1.80,중소형,1
120,T52SCG_20220527T021611_2022075.tif,2022075,2022075,4.00,중소형,1
121,T52SCH_20160408T021612_2016007.tif,2016007,2016007,2.00,중소형,1
122,T52SCH_20160408T022530_2016010.tif,2016010,2016010,1.50,중소형,1
123,T52SCH_20170413T021601_2017009.tif,2017009,2017009,1.50,중소형,1
124,T52SCH_20170503T021611_2017017.tif,2017017,2017017,1.50,중소형,1
125,T52SCH_20171119T022001_2017035.tif,2017035,2017035,6.50,중소형,2
126,T52SCH_20180413T021559_2018022.tif,2018022,2018022,1.50,중소형,1
127,T52SCH_20180831T021559_2018033.tif,2018033,2018033,9.40,중소형,2
128,T52SCH_20190123T022001_2019002.tif,2019002,2019002,1.46,중소형,1
129,T52SCH_20190128T021949_2019003.tif,2019003,2019003,5.00,중소형,2
130,T52SCH_20190304T021601_2019009.tif,2019009,2019009,1.00,중소형,1
131,T52SCH_20190314T021601_2019009.tif,2019009,2019009,1.00,중소형,1
132,T52SCH_20190403T021651_2019022.tif,2019022,2019022,1.00,중소형,1
133,T52SCH_20190408T021609_2019030.tif,2019030,2019030,2.00,중소형,1
134,T52SCH_20190508T021609_2019047.tif,2019047,2019047,1.00,중소형,1
135,T52SCH_20190508T021609_2019048.tif,2019048,2019048,1.50,중소형,1
136,T52SCH_20190523T021611_2019049.tif,2019049,2019049,2.00,중소형,1
137,T52SCH_20200113T022039_2020001.tif,2020001,2020001,34.26,중소형,3
138,T52SCH_20200118T022021_2020001.tif,2020001,2020001,34.26,중소형,3
139,T52SCH_20200328T021601_2020011.tif,2020011,2020011,9.85,중소형,2
140,T52SCH_20200402T021559_2020012.tif,2020012,2020012,2.11,중소형,1
141,T52SCH_20200422T021559_2020023.tif,2020023,2020023,19.00,중소형,2
142,T52SCH_20220102T022059_2021028.tif,2021028,2021028,4.00,중소형,1
143,T52SCH_20220216T021751_2022008.tif,2022008,2022008,1.60,중소형,1
144,T52SCH_20220417T021611_2022057.tif,2022057,2022057,1.60,중소형,1
145,T52SCH_20220417T021611_2022062.tif,2022062,2022062,1.24,중소형,1
146,T52SCH_20220417T021611_2022064.tif,2022064,2022064,3.30,중소형,1
147,T52SDD_20180130T020919_2018004.tif,2018004,2018004,1.00,중소형,1
148,T52SDD_20180224T020651_2018007.tif,2018007,2018007,1.50,중소형,1
149,T52SDD_20190301T020651_2019008.tif,2019008,2019008,2.00,중소형,1
150,T52SDD_20220208T020829_2022006.tif,2022006,2022006,1.03,중소형,1
151,T52SDD_20220305T020701_2022019.tif,2022019,2022019,10.20,중소형,2
152,T52SDD_20221230T021111_2022085.tif,2022085,2022085,2.00,중소형,1
153,T52SDE_20170321T020651_2017004.tif,2017004,2017004,5.20,중소형,2
154,T52SDE_20170430T020701_2017020.tif,2017020,2017020,1.25,중소형,1
155,T52SDE_20170609T020651_2017032.tif,2017032,2017032,24.18,중소형,2
156,T52SDE_20171221T021059_2017040.tif,2017040,2017040,1.50,중소형,1
157,T52SDE_20180209T020829_2018006.tif,2018006,2018006,1.20,중소형,1
158,T52SDE_20180219T020719_2018014.tif,2018014,2018014,1.00,중소형,1
159,T52SDE_20180222T021709_2018015.tif,2018015,2018015,1.00,중소형,1
160,T52SDE_20180408T021601_2018024.tif,2018024,2018024,16.10,중소형,2
161,T52SDE_20180729T020649_2018030.tif,2018030,2018030,1.50,중소형,1
162,T52SDE_20180801T021649_2018030.tif,2018030,2018030,1.50,중소형,1
163,T52SDE_20190331T030651_2019016.tif,2019016,2019016,2.00,중소형,1
164,T52SDE_20190405T020659_2019026.tif,2019026,2019026,1.00,중소형,1
165,T52SDE_20190415T020659_2019036.tif,2019036,2019036,2.00,중소형,1
166,T52SDE_20190530T020701_2019050.tif,2019050,2019050,1.00,중소형,1
167,T52SDE_20220114T021041_2022001.tif,2022001,2022001,5.50,중소형,2
168,T52SDE_20220203T020911_2022004.tif,2022004,2022004,1.45,중소형,1
169,T52SDE_20220218T020729_2022009.tif,2022009,2022009,12.40,중소형,2
170,T52SDE_20220218T020729_2022013.tif,2022013,2022013,8.53,중소형,2
171,T52SDE_20220218T020729_2022014.tif,2022014,2022014,1.50,중소형,1
172,T52SDE_20220303T021609_2022030.tif,2022030,2022030,813.89,대형,4
173,T52SDE_20220305T020701_2022024.tif,2022024,2022024,88.63,중소형,3
174,T52SDE_20220315T020701_2022024.tif,2022024,2022024,88.63,중소형,3
175,T52SDE_20220305T020701_2022037.tif,2022037,2022037,6.54,중소형,2
176,T52SDE_20220402T021559_2022048.tif,2022048,2022048,1.47,중소형,1
177,T52SDE_20220417T021611_2022066.tif,2022066,2022066,9.69,중소형,2
178,T52SDE_20220424T020701_2022067.tif,2022067,2022067,2.89,중소형,1
179,T52SDE_20220424T020701_2022068.tif,2022068,2022068,3.18,중소형,1
180,T52SDE_20220504T020701_2022074.tif,2022074,2022074,1.44,중소형,1
181,T52SDE_20220522T021609_2022078.tif,2022078,2022078,3.00,중소형,1
182,T52SDE_20220529T020659_2022080.tif,2022080,2022080,2.80,중소형,1
183,T52SDE_20220603T020701_2022080.tif,2022080,2022080,2.80,중소형,1
184,T52SDE_20220601T021559_2022082.tif,2022082,2022082,5.30,중소형,2
185,T52SDE_20220603T020701_2022083.tif,2022083,2022083,660.82,대형,4
186,T52SDF_20160215T021228_2016002.tif,2016002,2016002,1.50,중소형,1
187,T52SDF_20160408T021612_2016009.tif,2016009,2016009,92.60,중소형,3
188,T52SDF_20160408T021612_2016016.tif,2016016,2016016,66.50,중소형,3
189,T52SDF_20160408T022530_2016006.tif,2016006,2016006,1.50,중소형,1
190,T52SDF_20160408T022530_2016012.tif,2016012,2016012,4.00,중소형,1
191,T52SDF_20160408T022530_2016024.tif,2016024,2016024,53.80,중소형,3
192,T52SDF_20170314T022651_2017001.tif,2017001,2017001,2.00,중소형,1
193,T52SDF_20170403T022701_2017001.tif,2017001,2017001,2.00,중소형,1
194,T52SDF_20170410T020651_2017010.tif,2017010,2017010,2.20,중소형,1
195,T52SDF_20170410T020651_2017011.tif,2017011,2017011,1.50,중소형,1
196,T52SDF_20170520T020701_2017025.tif,2017025,2017025,1.50,중소형,1
197,T52SDF_20170520T020701_2017028.tif,2017028,2017028,86.00,중소형,3
198,T52SDF_20180202T021909_2018005.tif,2018005,2018005,1.00,중소형,1
199,T52SDF_20180324T021559_2018017.tif,2018017,2018017,2.50,중소형,1
200,T52SDF_20181002T020651_2018032.tif,2018032,2018032,31.90,중소형,3
201,T52SDF_20190319T021659_2019014.tif,2019014,2019014,3.00,중소형,1
202,T52SDF_20190324T021601_2019014.tif,2019014,2019014,3.00,중소형,1
203,T52SDF_20190403T021651_2019015.tif,2019015,2019015,22.00,중소형,2
204,T52SDF_20190403T021651_2019017.tif,2019017,2019017,1.00,중소형,1
205,T52SDF_20190403T021651_2019018.tif,2019018,2019018,1.00,중소형,1
206,T52SDF_20190408T021609_2019038.tif,2019038,2019038,1.00,중소형,1
207,T52SDF_20190415T020659_2019019.tif,2019019,2019019,18.44,중소형,2
208,T52SDF_20190530T020701_2019051.tif,2019051,2019051,4.70,중소형,1
209,T52SDF_20200308T021601_2020002.tif,2020002,2020002,1.35,중소형,1
210,T52SDF_20200323T021559_2020007.tif,2020007,2020007,18.30,중소형,2
211,T52SDF_20200404T020651_2020010.tif,2020010,2020010,13.20,중소형,2
212,T52SDF_20200409T020649_2020020.tif,2020020,2020020,48.20,중소형,3
213,T52SDF_20200427T021611_2020025.tif,2020025,2020025,1944.00,대형,5
214,T52SDF_20200429T020649_2020025.tif,2020025,2020025,1944.00,대형,5
215,T52SDF_20210223T020659_2021011.tif,2021011,2021011,74.90,중소형,3
216,T52SDF_20210223T020659_2021012.tif,2021012,2021012,112.00,대형,4
217,T52SDF_20210223T020659_2021013.tif,2021013,2021013,307.00,대형,4
218,T52SDF_20210502T021601_2021021.tif,2021021,2021021,2.00,중소형,1
219,T52SDF_20220112T022039_2022002.tif,2022002,2022002,14.10,중소형,2
220,T52SDF_20220211T021819_2022007.tif,2022007,2022007,1.15,중소형,1
221,T52SDF_20220218T020729_2022011.tif,2022011,2022011,1.47,중소형,1
222,T52SDF_20220223T020701_2022016.tif,2022016,2022016,9.20,중소형,2
223,T52SDF_20220303T021609_2022026.tif,2022026,2022026,18.50,중소형,2
224,T52SDF_20220308T021611_2022039.tif,2022039,2022039,3.86,중소형,1
225,T52SDF_20220407T021601_2022052.tif,2022052,2022052,130.00,대형,4
226,T52SDF_20220409T020649_2022052.tif,2022052,2022052,130.00,대형,4
227,T52SDF_20220412T021559_2022052.tif,2022052,2022052,130.00,대형,4
228,T52SDF_20220419T020649_2022063.tif,2022063,2022063,225.72,대형,4
229,T52SDF_20220424T020701_2022071.tif,2022071,2022071,3.00,중소형,1
230,T52SDG_20160126T021710_2016001.tif,2016001,2016001,3.00,중소형,1
231,T52SDG_20160218T022652_2016003.tif,2016003,2016003,3.00,중소형,1
232,T52SDG_20160309T022651_2016003.tif,2016003,2016003,3.00,중소형,1
233,T52SDG_20160408T022530_2016017.tif,2016017,2016017,1.00,중소형,1
234,T52SDG_20160408T022530_2016021.tif,2016021,2016021,4.70,중소형,1
235,T52SDG_20160515T020702_2016027.tif,2016027,2016027,2.00,중소형,1
236,T52SDG_20160518T021612_2016027.tif,2016027,2016027,2.00,중소형,1
237,T52SDG_20160528T022702_2016028.tif,2016028,2016028,13.00,중소형,2
238,T52SDG_20170311T021651_2017003.tif,2017003,2017003,160.41,대형,4
239,T52SDG_20170520T020701_2017027.tif,2017027,2017027,252.00,대형,4
240,T52SDG_20170520T020701_2017029.tif,2017029,2017029,765.12,대형,4
241,T52SDG_20190405T020659_2019027.tif,2019027,2019027,1260.15,대형,5
242,T52SDG_20190408T021609_2019027.tif,2019027,2019027,1260.15,대형,5
243,T52SDG_20190413T021611_2019027.tif,2019027,2019027,1260.15,대형,5
244,T52SDG_20190415T020659_2019027.tif,2019027,2019027,1260.15,대형,5
245,T52SDG_20190408T021609_2019031.tif,2019031,2019031,4.00,중소형,1
246,T52SDG_20190508T021609_2019046.tif,2019046,2019046,1.90,중소형,1
247,T52SDG_20200330T020649_2020009.tif,2020009,2020009,1.40,중소형,1
248,T52SDG_20200409T020649_2020019.tif,2020019,2020019,11.91,중소형,2
249,T52SDG_20200427T021611_2020017.tif,2020017,2020017,1.50,중소형,1
250,T52SDG_20200429T020649_2020026.tif,2020026,2020026,1.70,중소형,1
251,T52SDG_20210206T021849_2021004.tif,2021004,2021004,2.02,중소형,1
252,T52SDG_20210208T020851_2021004.tif,2021004,2021004,2.02,중소형,1
253,T52SDG_20210213T020809_2021005.tif,2021005,2021005,3.70,중소형,1
254,T52SDG_20210218T020731_2021007.tif,2021007,2021007,2.70,중소형,1
255,T52SDG_20210221T021721_2021009.tif,2021009,2021009,24.56,중소형,2
256,T52SDG_20210223T020659_2021009.tif,2021009,2021009,24.56,중소형,2
257,T52SDG_20210313T021601_2021015.tif,2021015,2021015,4.42,중소형,1
258,T52SDG_20210402T021601_2021016.tif,2021016,2021016,20.00,중소형,2
259,T52SDG_20210402T021601_2021019.tif,2021019,2021019,10.70,중소형,2
260,T52SDG_20220223T020701_2022017.tif,2022017,2022017,3.95,중소형,1
261,T52SDG_20220228T020649_2022020.tif,2022020,2022020,4.10,중소형,1
262,T52SDG_20220305T020701_2022032.tif,2022032,2022032,30.89,중소형,3
263,T52SDG_20220308T021611_2022032.tif,2022032,2022032,30.89,중소형,3
264,T52SDG_20220305T020701_2022035.tif,2022035,2022035,184.01,대형,4
265,T52SDG_20220308T021611_2022035.tif,2022035,2022035,184.01,대형,4
266,T52SDG_20220305T020701_2022041.tif,2022041,2022041,4190.38,대형,5
267,T52SDG_20220310T020649_2022041.tif,2022041,2022041,4190.38,대형,5
268,T52SDG_20220315T020701_2022041.tif,2022041,2022041,4190.38,대형,5
269,T52SDG_20220315T020701_2022045.tif,2022045,2022045,8.00,중소형,2
270,T52SDG_20220524T020701_2022076.tif,2022076,2022076,2.25,중소형,1
271,T52SDG_20220524T020701_2022079.tif,2022079,2022079,1.20,중소형,1
272,T52SDH_20160408T022530_2016014.tif,2016014,2016014,14.40,중소형,2
273,T52SDH_20180115T021021_2018002.tif,2018002,2018002,17.73,중소형,2
274,T52SDH_20180329T021651_2018021.tif,2018021,2018021,356.85,대형,4
275,T52SDH_20180331T020649_2018021.tif,2018021,2018021,356.85,대형,4
276,T52SDH_20180420T020649_2018025.tif,2018025,2018025,13.08,중소형,2
277,T52SDH_20180428T021611_2018027.tif,2018027,2018027,3.00,중소형,1
278,T52SDH_20190103T022101_2019001.tif,2019001,2019001,97.94,중소형,3
279,T52SDH_20190128T021949_2019004.tif,2019004,2019004,1.00,중소형,1
280,T52SDH_20190319T021659_2019012.tif,2019012,2019012,1.30,중소형,1
281,T52SDH_20190405T020659_2019028.tif,2019028,2019028,1266.62,대형,5
282,T52SDH_20190408T021609_2019029.tif,2019029,2019029,344.93,대형,4
283,T52SDH_20190413T021611_2019029.tif,2019029,2019029,344.93,대형,4
284,T52SDH_20190508T021609_2019044.tif,2019044,2019044,5.20,중소형,2
285,T52SDH_20200502T021559_2020028.tif,2020028,2020028,123.20,대형,4
286,T52SDH_20200504T020701_2020028.tif,2020028,2020028,123.20,대형,4
287,T52SDH_20210221T021721_2021008.tif,2021008,2021008,3.62,중소형,1
288,T52SDH_20211115T020941_2021026.tif,2021026,2021026,1.27,중소형,1
289,T52SDH_20220228T020649_2022025.tif,2022025,2022025,8.69,중소형,2
290,T52SDH_20220303T021609_2022025.tif,2022025,2022025,8.69,중소형,2
291,T52SDH_20220417T021611_2022060.tif,2022060,2022060,716.31,대형,4
292,T52SDH_20220424T020701_2022070.tif,2022070,2022070,70.44,중소형,3
293,T52SEE_20171221T021059_2017038.tif,2017038,2017038,18.00,중소형,2
294,T52SEE_20171221T021059_2017039.tif,2017039,2017039,1.89,중소형,1
295,T52SEE_20171231T021059_2017041.tif,2017041,2017041,3.00,중소형,1
296,T52SEE_20180110T021039_2018001.tif,2018001,2018001,65.00,중소형,3
297,T52SEE_20180214T020801_2018011.tif,2018011,2018011,1.00,중소형,1
298,T52SEE_20180326T020651_2018016.tif,2018016,2018016,1.40,중소형,1
299,T52SEE_20180326T020651_2018019.tif,2018019,2018019,1.20,중소형,1
300,T52SEE_20180331T020649_2018019.tif,2018019,2018019,1.20,중소형,1
301,T52SEE_20180714T020651_2018029.tif,2018029,2018029,3.00,중소형,1

In [ ]:
hist_n = new_df.groupby('규모구분(등급)').count()

hist_n = hist_n.rename(columns = {'규모구분(대형/중소형)' : '건수'})

hist_n = hist_n.drop(columns = ['filename', '산불ID', '피해면적', 'file_id'], axis = 1)

In [30]:
hist_n['비율'] = hist_n['건수'] /hist_n['건수'].sum() * 100

hist_n = hist_n.round({'비율' : 1})

hist_n.reset_index(inplace=True)

In [32]:
hist_n

   규모구분(등급)   건수    비율
0         1  220  62.3
1         2   73  20.7
2         3   20   5.7
3         4   27   7.6
4         5   13   3.7

In [ ]:
# 조건 : 전체 데이터 7 : 2 : 1 비율 training, validation, test 데이터로 구분,
# 각각의 데이터셋은 비슷한 비율로 데이터를 가져야..?
# 어떻게 하느냐.

In [110]:
new_df = new_df.sample(frac=1, random_state=6183)

In [111]:
train_ratio, val_ratio, test_ratio = 0.6, 0.2, 0.2

In [112]:
new_df['dataset'] = 'train'

In [113]:
grouped = new_df.groupby('규모구분(등급)')

In [138]:
for _, group in grouped:
    num_samples = len(group)
    num_train = int(train_ratio * num_samples)
    num_val = int(val_ratio * num_samples)
    
    indices = np.arange(num_samples)
    np.random.shuffle(indices)
    
    train_indices = indices[:num_train]
    val_indices = indices[num_train:num_train + num_val]
    
    new_df.loc[group.index[train_indices], 'dataset'] = 'train'
    new_df.loc[group.index[val_indices], 'dataset'] = 'val'
    new_df.loc[group.index[num_train + num_val:], 'dataset'] = 'test'

In [215]:
test_result2 = new_df.groupby('dataset').count()

In [216]:
test_result2

         filename  file_id  산불ID  피해면적  규모구분(대형/중소형)  규모구분(등급)
dataset
test           71       71    71    71            71        71
train         212      212   212   212           212       212
val            70       70    70    70            70        70

In [141]:
new_df = new_df.sort_index()

In [50]:
74+206+73

353

In [153]:
round(71/353*100, 2)

20.11

In [148]:
round(212/353*100, 2)

60.06

In [154]:
round(70/353*100, 2)

19.83

In [ ]:
# test 3개 -> val로
# train 4개 -> val로

In [217]:
test_result = new_df.groupby(['규모구분(등급)','dataset']).count()

In [ ]:
# 등급1짜리 train 3개 -> val로 , 
# 옮겨야할 train 잔여 개수 1개

In [ ]:
#76번 row, 146, 234 번 row

In [166]:
new_df.at[76, 'dataset']= 'val'
new_df.at[146, 'dataset']= 'val'
new_df.at[234, 'dataset']= 'val'

In [ ]:
# 등급 2 test1건을 무작위로 정해서 val

In [ ]:
#248번

In [182]:
new_df.at[248, 'dataset']= 'val'

In [ ]:
# 등급 2 train 1건을 무작위로 정해서 val 
# 20

In [196]:
new_df.at[20, 'dataset']= 'val'

In [ ]:
# 등급 4, 5에서 test 1개씩 val로

# 227
# 241

In [206]:
new_df.at[227, 'dataset']= 'val'
new_df.at[241, 'dataset']= 'val'

In [200]:
hist_n['건수'].tolist()

[220, 73, 20, 27, 13]

In [203]:
round(17/27*100, 2)

62.96

In [219]:
test_result

                  filename  file_id  산불ID  피해면적  규모구분(대형/중소형)
규모구분(등급) dataset
1        test           44       44    44    44            44
         train         132      132   132   132           132
         val            44       44    44    44            44
2        test           15       15    15    15            15
         train          44       44    44    44            44
         val            14       14    14    14            14
3        test            4        4     4     4             4
         train          12       12    12    12            12
         val             4        4     4     4             4
4        test            5        5     5     5             5
         train          17       17    17    17            17
         val             5        5     5     5             5
5        test            3        3     3     3             3
         train           7        7     7     7             7
         val             3        3     3     3             3

In [ ]:
# 160회의 randomcrop이 일어날 등급 5 케이스의 경우는 멀끔한 경우 / 산불 진행중 / 구름낀 경우가 있는데 최소한 산불진행중과
# 멀끔+ 멀끔&구름낀 경우 를 val이랑 test에서 3개씩이니깐 잘 포함하도록 조정 
# 조정끝

In [131]:
'''new_df.at[214, 'dataset']= 'test'
new_df.at[349, 'dataset']= 'train'

new_df.at[266, 'dataset']= 'val'
new_df.at[268, 'dataset']= 'train'

# 266 268


new_df.at[213, 'dataset']= 'train'
new_df.at[241, 'dataset']= 'train'
new_df.at[242, 'dataset']= 'val'

new_df.at[349, 'dataset']= 'val'
new_df.at[267, 'dataset']= 'test'

new_df.at[244, 'dataset']= 'train'
new_df.at[281, 'dataset']= 'val'

new_df.at[266, 'dataset']= 'train'
new_df.at[214, 'dataset']= 'val'
new_df.at[347, 'dataset']= 'val'
new_df.at[349, 'dataset']= 'test'
'''

In [ ]:
# 전체 데이터 중 2048 * 2048  8장  배점 160
# 1024*1024 12장  배점 40
# 512 * 512 배점은 10
# train * validation 과정에서만 유효
# 배점고려안해도 산불 규모 등급별로 일정 비율 배분했으면 어느정도 만족한것으로 간주해도..?

In [212]:
#new_df.loc[new_df['규모구분(등급)']==5]

,filename,file_id,산불ID,피해면적,규모구분(대형/중소형),규모구분(등급),dataset
213,T52SDF_20200427T021611_2020025.tif,2020025,2020025,1944.00,대형,5,train
214,T52SDF_20200429T020649_2020025.tif,2020025,2020025,1944.00,대형,5,train
241,T52SDG_20190405T020659_2019027.tif,2019027,2019027,1260.15,대형,5,val
242,T52SDG_20190408T021609_2019027.tif,2019027,2019027,1260.15,대형,5,train
243,T52SDG_20190413T021611_2019027.tif,2019027,2019027,1260.15,대형,5,train
244,T52SDG_20190415T020659_2019027.tif,2019027,2019027,1260.15,대형,5,test
266,T52SDG_20220305T020701_2022041.tif,2022041,2022041,4190.38,대형,5,train
267,T52SDG_20220310T020649_2022041.tif,2022041,2022041,4190.38,대형,5,train
268,T52SDG_20220315T020701_2022041.tif,2022041,2022041,4190.38,대형,5,val
281,T52SDH_20190405T020659_2019028.tif,2019028,2019028,1266.62,대형,5,test
347,T52SEG_20220305T020701_2022036.tif,2022036,2022036,16301.98,대형,5,test
348,T52SEG_20220310T020649_2022036.tif,2022036,2022036,16301.98,대형,5,train
349,T52SEG_20220315T020701_2022036.tif,2022036,2022036,16301.98,대형,5,val

In [ ]:
# 347 row 를 val로
#

In [213]:
new_df

,filename,file_id,산불ID,피해면적,규모구분(대형/중소형),규모구분(등급),dataset
0,T51SYU_20220226T021651_2022027.tif,2022027,2022027,2.00,중소형,1,val
1,T51SYU_20220303T021609_2022027.tif,2022027,2022027,2.00,중소형,1,val
2,T52SBC_20200427T021611_2020027.tif,2020027,2020027,1.82,중소형,1,train
3,T52SBD_20220402T021559_2022046.tif,2022046,2022046,3.00,중소형,1,val
4,T52SBE_20170413T021601_2017002.tif,2017002,2017002,1.00,중소형,1,test
5,T52SBE_20210407T021559_2021017.tif,2021017,2021017,2.00,중소형,1,train
6,T52SBE_20220522T021609_2022077.tif,2022077,2022077,2.50,중소형,1,test
7,T52SBF_20220303T021609_2022028.tif,2022028,2022028,1.50,중소형,1,train
8,T52SBF_20220308T021611_2022038.tif,2022038,2022038,5.00,중소형,2,train
9,T52SBF_20220417T021611_2022058.tif,2022058,2022058,158.11,대형,4,train
10,T52SBG_20160329T022653_2016008.tif,2016008,2016008,1.00,중소형,1,val
11,T52SBG_20160408T022530_2016008.tif,2016008,2016008,1.00,중소형,1,train
12,T52SBG_20160508T022702_2016026.tif,2016026,2016026,1.30,중소형,1,test
13,T52SBG_20161005T021602_2016029.tif,2016029,2016029,2.15,중소형,1,train
14,T52SBG_20161214T022102_2016030.tif,2016030,2016030,4.50,중소형,1,train
15,T52SBG_20170324T021601_2017006.tif,2017006,2017006,3.00,중소형,1,val
16,T52SBG_20170403T022701_2017006.tif,2017006,2017006,3.00,중소형,1,val
17,T52SBG_20170403T022701_2017013.tif,2017013,2017013,1.00,중소형,1,train
18,T52SBG_20170503T021611_2017018.tif,2017018,2017018,1.20,중소형,1,train
19,T52SBG_20170526T022551_2017026.tif,2017026,2017026,1.00,중소형,1,train
20,T52SBG_20200318T021601_2020003.tif,2020003,2020003,7.00,중소형,2,val
21,T52SBG_20200323T021559_2020006.tif,2020006,2020006,2.68,중소형,1,test
22,T52SBG_20200427T021611_2020021.tif,2020021,2020021,1.20,중소형,1,train
23,T52SCD_20190403T021651_2019020.tif,2019020,2019020,7.00,중소형,2,train
24,T52SCD_20201208T022059_2020034.tif,2020034,2020034,2.00,중소형,1,test
25,T52SCD_20210213T020809_2021006.tif,2021006,2021006,3.00,중소형,1,train
26,T52SCD_20210305T020649_2021014.tif,2021014,2021014,49.15,중소형,3,train
27,T52SCD_20210414T020649_2021020.tif,2021020,2021020,1.40,중소형,1,test
28,T52SCD_20210429T020651_2021022.tif,2021022,2021022,1.50,중소형,1,train
29,T52SCD_20211228T022111_2021027.tif,2021027,2021027,10.00,중소형,2,test
30,T52SCD_20211230T021059_2021027.tif,2021027,2021027,10.00,중소형,2,train
31,T52SCD_20220203T020911_2022003.tif,2022003,2022003,4.40,중소형,1,train
32,T52SCD_20220226T021651_2022022.tif,2022022,2022022,2.00,중소형,1,train
33,T52SCD_20220226T021651_2022023.tif,2022023,2022023,29.00,중소형,2,val
34,T52SCD_20220412T021559_2022055.tif,2022055,2022055,1.80,중소형,1,train
35,T52SCE_20171211T021049_2017037.tif,2017037,2017037,5.00,중소형,2,train
36,T52SCE_20180217T021741_2018012.tif,2018012,2018012,3.00,중소형,1,test
37,T52SCE_20180821T021559_2018034.tif,2018034,2018034,1.00,중소형,1,test
38,T52SCE_20180905T021601_2018034.tif,2018034,2018034,1.00,중소형,1,train
39,T52SCE_20190408T021609_2019025.tif,2019025,2019025,1.00,중소형,1,train
40,T52SCE_20200409T020649_2020018.tif,2020018,2020018,20.00,중소형,2,train
41,T52SCE_20210104T021059_2021001.tif,2021001,2021001,3.00,중소형,1,train
42,T52SCE_20210107T022059_2021001.tif,2021001,2021001,3.00,중소형,1,test
43,T52SCE_20210109T021051_2021001.tif,2021001,2021001,3.00,중소형,1,train
44,T52SCE_20210502T021601_2021023.tif,2021023,2021023,10.00,중소형,2,train
45,T52SCE_20210509T020651_2021023.tif,2021023,2021023,10.00,중소형,2,train
46,T52SCE_20220226T021651_2022021.tif,2022021,2022021,8.03,중소형,2,train
47,T52SCE_20220305T020701_2022033.tif,2022033,2022033,16.30,중소형,2,train
48,T52SCE_20220315T020701_2022047.tif,2022047,2022047,3.80,중소형,1,train
49,T52SCE_20220404T020701_2022049.tif,2022049,2022049,5.00,중소형,2,train
50,T52SCE_20220502T021559_2022073.tif,2022073,2022073,5.00,중소형,2,train
51,T52SCF_20160408T022530_2016018.tif,2016018,2016018,4.80,중소형,1,train
52,T52SCF_20170503T021611_2017019.tif,2017019,2017019,2.00,중소형,1,train
53,T52SCF_20170612T021601_2017033.tif,2017033,2017033,3.12,중소형,1,train
54,T52SCF_20170727T021559_2017034.tif,2017034,2017034,6.30,중소형,2,train
55,T52SCF_20171214T022059_2017036.tif,2017036,2017036,4.80,중소형,1,train
56,T52SCF_20190408T021609_2019032.tif,2019032,2019032,1.30,중소형,1,test
57,T52SCF_20190418T021609_2019041.tif,2019041,2019041,1.50,중소형,1,train
58,T52SCF_20190503T021611_2019041.tif,2019041,2019041,1.50,중소형,1,train
59,T52SCF_20190503T021611_2019042.tif,2019042,2019042,2.00,중소형,1,train
60,T52SCF_20210226T021639_2021010.tif,2021010,2021010,34.13,중소형,3,train
61,T52SCF_20210904T021559_2021025.tif,2021025,2021025,5.00,중소형,2,train
62,T52SCF_20220226T021651_2022012.tif,2022012,2022012,1.80,중소형,1,val
63,T52SCF_20220417T021611_2022054.tif,2022054,2022054,4.00,중소형,1,train
64,T52SCF_20220424T020701_2022072.tif,2022072,2022072,2.82,중소형,1,train
65,T52SCF_20221208T022059_2022084.tif,2022084,2022084,5.00,중소형,2,val
66,T52SCG_20160309T022651_2016004.tif,2016004,2016004,2.70,중소형,1,train
67,T52SCG_20160408T021612_2016020.tif,2016020,2016020,1.00,중소형,1,train
68,T52SCG_20160408T021612_2016022.tif,2016022,2016022,3.90,중소형,1,train
69,T52SCG_20160408T021612_2016023.tif,2016023,2016023,2.00,중소형,1,train
70,T52SCG_20160408T022530_2016005.tif,2016005,2016005,2.00,중소형,1,train
71,T52SCG_20160408T022530_2016011.tif,2016011,2016011,8.30,중소형,2,train
72,T52SCG_20160408T022530_2016013.tif,2016013,2016013,1.00,중소형,1,test
73,T52SCG_20160408T022530_2016015.tif,2016015,2016015,2.60,중소형,1,train
74,T52SCG_20160428T022700_2016019.tif,2016019,2016019,7.00,중소형,2,val
75,T52SCH_20160408T022530_2016019.tif,2016019,2016019,7.00,중소형,2,train
76,T52SCG_20160428T022702_2016025.tif,2016025,2016025,2.00,중소형,1,val
77,T52SCG_20170403T022701_2017005.tif,2017005,2017005,2.00,중소형,1,train
78,T52SCG_20170403T022701_2017007.tif,2017007,2017007,2.00,중소형,1,train
79,T52SCG_20170403T022701_2017008.tif,2017008,2017008,1.30,중소형,1,train
80,T52SCG_20170403T022701_2017012.tif,2017012,2017012,1.00,중소형,1,val
81,T52SCG_20170413T021601_2017014.tif,2017014,2017014,2.50,중소형,1,val
82,T52SCG_20170413T021601_2017015.tif,2017015,2017015,2.50,중소형,1,test
83,T52SCG_20170413T021601_2017016.tif,2017016,2017016,1.00,중소형,1,val
84,T52SCG_20170503T021611_2017021.tif,2017021,2017021,1.00,중소형,1,test
85,T52SCG_20170503T021611_2017022.tif,2017022,2017022,2.00,중소형,1,train
86,T52SCG_20170503T021611_2017023.tif,2017023,2017023,1.30,중소형,1,train
87,T52SCG_20170602T022701_2017023.tif,2017023,2017023,1.30,중소형,1,val
88,T52SCG_20170602T022701_2017031.tif,2017031,2017031,1.70,중소형,1,train
89,T52SCG_20180202T021909_2018003.tif,2018003,2018003,3.00,중소형,1,train
90,T52SCG_20180324T021559_2018018.tif,2018018,2018018,1.10,중소형,1,val
91,T52SCG_20180428T021611_2018026.tif,2018026,2018026,1.00,중소형,1,train
92,T52SCG_20180707T021601_2018028.tif,2018028,2018028,1.00,중소형,1,train
93,T52SCG_20190207T021849_2019005.tif,2019005,2019005,1.45,중소형,1,train
94,T52SCG_20190314T021601_2019010.tif,2019010,2019010,1.00,중소형,1,train
95,T52SCG_20190324T021601_2019011.tif,2019011,2019011,1.00,중소형,1,train
96,T52SCG_20190324T021601_2019013.tif,2019013,2019013,1.00,중소형,1,train
97,T52SCG_20190408T021609_2019024.tif,2019024,2019024,3.50,중소형,1,train
98,T52SCG_20190408T021609_2019033.tif,2019033,2019033,1.00,중소형,1,val
99,T52SCG_20190413T021611_2019039.tif,2019039,2019039,1.50,중소형,1,test
100,T52SCG_20190523T021611_2019045.tif,2019045,2019045,1.50,중소형,1,test
101,T52SCG_20200323T021559_2020005.tif,2020005,2020005,2.20,중소형,1,val
102,T52SCG_20200402T021559_2020013.tif,2020013,2020013,3.75,중소형,1,test
103,T52SCG_20200407T021601_2020013.tif,2020013,2020013,3.75,중소형,1,train
104,T52SCG_20200407T021601_2020014.tif,2020014,2020014,6.20,중소형,2,test
105,T52SCG_20200407T021601_2020016.tif,2020016,2020016,2.70,중소형,1,train
106,T52SCG_20200427T021611_2020022.tif,2020022,2020022,2.75,중소형,1,train
107,T52SCG_20200507T021611_2020022.tif,2020022,2020022,2.75,중소형,1,val
108,T52SCG_20200527T021611_2020022.tif,2020022,2020022,2.75,중소형,1,test
109,T52SCG_20200507T021611_2020024.tif,2020024,2020024,3.56,중소형,1,train
110,T52SCG_20201113T021941_2020033.tif,2020033,2020033,3.00,중소형,1,val
111,T52SCG_20220226T021651_2022018.tif,2022018,2022018,3.00,중소형,1,test
112,T52SCG_20220308T021611_2022034.tif,2022034,2022034,1.80,중소형,1,val
113,T52SCG_20220308T021611_2022040.tif,2022040,2022040,8.00,중소형,2,test
114,T52SCG_20220328T021611_2022043.tif,2022043,2022043,5.00,중소형,2,val
115,T52SCG_20220407T021601_2022050.tif,2022050,2022050,8.00,중소형,2,test
116,T52SCG_20220412T021559_2022056.tif,2022056,2022056,1.50,중소형,1,train
117,T52SCG_20220417T021611_2022056.tif,2022056,2022056,1.50,중소형,1,val
118,T52SCG_20220417T021611_2022053.tif,2022053,2022053,8.00,중소형,2,train
119,T52SCG_20220427T021611_2022069.tif,2022069,2022069,1.80,중소형,1,train
120,T52SCG_20220527T021611_2022075.tif,2022075,2022075,4.00,중소형,1,val
121,T52SCH_20160408T021612_2016007.tif,2016007,2016007,2.00,중소형,1,test
122,T52SCH_20160408T022530_2016010.tif,2016010,2016010,1.50,중소형,1,test
123,T52SCH_20170413T021601_2017009.tif,2017009,2017009,1.50,중소형,1,val
124,T52SCH_20170503T021611_2017017.tif,2017017,2017017,1.50,중소형,1,val
125,T52SCH_20171119T022001_2017035.tif,2017035,2017035,6.50,중소형,2,train
126,T52SCH_20180413T021559_2018022.tif,2018022,2018022,1.50,중소형,1,val
127,T52SCH_20180831T021559_2018033.tif,2018033,2018033,9.40,중소형,2,train
128,T52SCH_20190123T022001_2019002.tif,2019002,2019002,1.46,중소형,1,train
129,T52SCH_20190128T021949_2019003.tif,2019003,2019003,5.00,중소형,2,val
130,T52SCH_20190304T021601_2019009.tif,2019009,2019009,1.00,중소형,1,train
131,T52SCH_20190314T021601_2019009.tif,2019009,2019009,1.00,중소형,1,train
132,T52SCH_20190403T021651_2019022.tif,2019022,2019022,1.00,중소형,1,train
133,T52SCH_20190408T021609_2019030.tif,2019030,2019030,2.00,중소형,1,train
134,T52SCH_20190508T021609_2019047.tif,2019047,2019047,1.00,중소형,1,train
135,T52SCH_20190508T021609_2019048.tif,2019048,2019048,1.50,중소형,1,test
136,T52SCH_20190523T021611_2019049.tif,2019049,2019049,2.00,중소형,1,train
137,T52SCH_20200113T022039_2020001.tif,2020001,2020001,34.26,중소형,3,val
138,T52SCH_20200118T022021_2020001.tif,2020001,2020001,34.26,중소형,3,val
139,T52SCH_20200328T021601_2020011.tif,2020011,2020011,9.85,중소형,2,train
140,T52SCH_20200402T021559_2020012.tif,2020012,2020012,2.11,중소형,1,val
141,T52SCH_20200422T021559_2020023.tif,2020023,2020023,19.00,중소형,2,train
142,T52SCH_20220102T022059_2021028.tif,2021028,2021028,4.00,중소형,1,test
143,T52SCH_20220216T021751_2022008.tif,2022008,2022008,1.60,중소형,1,test
144,T52SCH_20220417T021611_2022057.tif,2022057,2022057,1.60,중소형,1,train
145,T52SCH_20220417T021611_2022062.tif,2022062,2022062,1.24,중소형,1,train
146,T52SCH_20220417T021611_2022064.tif,2022064,2022064,3.30,중소형,1,val
147,T52SDD_20180130T020919_2018004.tif,2018004,2018004,1.00,중소형,1,train
148,T52SDD_20180224T020651_2018007.tif,2018007,2018007,1.50,중소형,1,test
149,T52SDD_20190301T020651_2019008.tif,2019008,2019008,2.00,중소형,1,train
150,T52SDD_20220208T020829_2022006.tif,2022006,2022006,1.03,중소형,1,train
151,T52SDD_20220305T020701_2022019.tif,2022019,2022019,10.20,중소형,2,val
152,T52SDD_20221230T021111_2022085.tif,2022085,2022085,2.00,중소형,1,train
153,T52SDE_20170321T020651_2017004.tif,2017004,2017004,5.20,중소형,2,val
154,T52SDE_20170430T020701_2017020.tif,2017020,2017020,1.25,중소형,1,train
155,T52SDE_20170609T020651_2017032.tif,2017032,2017032,24.18,중소형,2,train
156,T52SDE_20171221T021059_2017040.tif,2017040,2017040,1.50,중소형,1,train
157,T52SDE_20180209T020829_2018006.tif,2018006,2018006,1.20,중소형,1,test
158,T52SDE_20180219T020719_2018014.tif,2018014,2018014,1.00,중소형,1,test
159,T52SDE_20180222T021709_2018015.tif,2018015,2018015,1.00,중소형,1,test
160,T52SDE_20180408T021601_2018024.tif,2018024,2018024,16.10,중소형,2,test
161,T52SDE_20180729T020649_2018030.tif,2018030,2018030,1.50,중소형,1,val
162,T52SDE_20180801T021649_2018030.tif,2018030,2018030,1.50,중소형,1,train
163,T52SDE_20190331T030651_2019016.tif,2019016,2019016,2.00,중소형,1,train
164,T52SDE_20190405T020659_2019026.tif,2019026,2019026,1.00,중소형,1,val
165,T52SDE_20190415T020659_2019036.tif,2019036,2019036,2.00,중소형,1,test
166,T52SDE_20190530T020701_2019050.tif,2019050,2019050,1.00,중소형,1,test
167,T52SDE_20220114T021041_2022001.tif,2022001,2022001,5.50,중소형,2,test
168,T52SDE_20220203T020911_2022004.tif,2022004,2022004,1.45,중소형,1,val
169,T52SDE_20220218T020729_2022009.tif,2022009,2022009,12.40,중소형,2,train
170,T52SDE_20220218T020729_2022013.tif,2022013,2022013,8.53,중소형,2,train
171,T52SDE_20220218T020729_2022014.tif,2022014,2022014,1.50,중소형,1,val
172,T52SDE_20220303T021609_2022030.tif,2022030,2022030,813.89,대형,4,train
173,T52SDE_20220305T020701_2022024.tif,2022024,2022024,88.63,중소형,3,test
174,T52SDE_20220315T020701_2022024.tif,2022024,2022024,88.63,중소형,3,train
175,T52SDE_20220305T020701_2022037.tif,2022037,2022037,6.54,중소형,2,train
176,T52SDE_20220402T021559_2022048.tif,2022048,2022048,1.47,중소형,1,train
177,T52SDE_20220417T021611_2022066.tif,2022066,2022066,9.69,중소형,2,test
178,T52SDE_20220424T020701_2022067.tif,2022067,2022067,2.89,중소형,1,train
179,T52SDE_20220424T020701_2022068.tif,2022068,2022068,3.18,중소형,1,train
180,T52SDE_20220504T020701_2022074.tif,2022074,2022074,1.44,중소형,1,val
181,T52SDE_20220522T021609_2022078.tif,2022078,2022078,3.00,중소형,1,train
182,T52SDE_20220529T020659_2022080.tif,2022080,2022080,2.80,중소형,1,train
183,T52SDE_20220603T020701_2022080.tif,2022080,2022080,2.80,중소형,1,val
184,T52SDE_20220601T021559_2022082.tif,2022082,2022082,5.30,중소형,2,val
185,T52SDE_20220603T020701_2022083.tif,2022083,2022083,660.82,대형,4,train
186,T52SDF_20160215T021228_2016002.tif,2016002,2016002,1.50,중소형,1,train
187,T52SDF_20160408T021612_2016009.tif,2016009,2016009,92.60,중소형,3,train
188,T52SDF_20160408T021612_2016016.tif,2016016,2016016,66.50,중소형,3,train
189,T52SDF_20160408T022530_2016006.tif,2016006,2016006,1.50,중소형,1,train
190,T52SDF_20160408T022530_2016012.tif,2016012,2016012,4.00,중소형,1,train
191,T52SDF_20160408T022530_2016024.tif,2016024,2016024,53.80,중소형,3,train
192,T52SDF_20170314T022651_2017001.tif,2017001,2017001,2.00,중소형,1,train
193,T52SDF_20170403T022701_2017001.tif,2017001,2017001,2.00,중소형,1,train
194,T52SDF_20170410T020651_2017010.tif,2017010,2017010,2.20,중소형,1,train
195,T52SDF_20170410T020651_2017011.tif,2017011,2017011,1.50,중소형,1,train
196,T52SDF_20170520T020701_2017025.tif,2017025,2017025,1.50,중소형,1,val
197,T52SDF_20170520T020701_2017028.tif,2017028,2017028,86.00,중소형,3,test
198,T52SDF_20180202T021909_2018005.tif,2018005,2018005,1.00,중소형,1,train
199,T52SDF_20180324T021559_2018017.tif,2018017,2018017,2.50,중소형,1,train
200,T52SDF_20181002T020651_2018032.tif,2018032,2018032,31.90,중소형,3,train
201,T52SDF_20190319T021659_2019014.tif,2019014,2019014,3.00,중소형,1,train
202,T52SDF_20190324T021601_2019014.tif,2019014,2019014,3.00,중소형,1,train
203,T52SDF_20190403T021651_2019015.tif,2019015,2019015,22.00,중소형,2,train
204,T52SDF_20190403T021651_2019017.tif,2019017,2019017,1.00,중소형,1,val
205,T52SDF_20190403T021651_2019018.tif,2019018,2019018,1.00,중소형,1,test
206,T52SDF_20190408T021609_2019038.tif,2019038,2019038,1.00,중소형,1,test
207,T52SDF_20190415T020659_2019019.tif,2019019,2019019,18.44,중소형,2,test
208,T52SDF_20190530T020701_2019051.tif,2019051,2019051,4.70,중소형,1,val
209,T52SDF_20200308T021601_2020002.tif,2020002,2020002,1.35,중소형,1,train
210,T52SDF_20200323T021559_2020007.tif,2020007,2020007,18.30,중소형,2,train
211,T52SDF_20200404T020651_2020010.tif,2020010,2020010,13.20,중소형,2,train
212,T52SDF_20200409T020649_2020020.tif,2020020,2020020,48.20,중소형,3,val
213,T52SDF_20200427T021611_2020025.tif,2020025,2020025,1944.00,대형,5,train
214,T52SDF_20200429T020649_2020025.tif,2020025,2020025,1944.00,대형,5,train
215,T52SDF_20210223T020659_2021011.tif,2021011,2021011,74.90,중소형,3,val
216,T52SDF_20210223T020659_2021012.tif,2021012,2021012,112.00,대형,4,train
217,T52SDF_20210223T020659_2021013.tif,2021013,2021013,307.00,대형,4,train
218,T52SDF_20210502T021601_2021021.tif,2021021,2021021,2.00,중소형,1,val
219,T52SDF_20220112T022039_2022002.tif,2022002,2022002,14.10,중소형,2,train
220,T52SDF_20220211T021819_2022007.tif,2022007,2022007,1.15,중소형,1,train
221,T52SDF_20220218T020729_2022011.tif,2022011,2022011,1.47,중소형,1,train
222,T52SDF_20220223T020701_2022016.tif,2022016,2022016,9.20,중소형,2,train
223,T52SDF_20220303T021609_2022026.tif,2022026,2022026,18.50,중소형,2,val
224,T52SDF_20220308T021611_2022039.tif,2022039,2022039,3.86,중소형,1,val
225,T52SDF_20220407T021601_2022052.tif,2022052,2022052,130.00,대형,4,train
226,T52SDF_20220409T020649_2022052.tif,2022052,2022052,130.00,대형,4,train
227,T52SDF_20220412T021559_2022052.tif,2022052,2022052,130.00,대형,4,val
228,T52SDF_20220419T020649_2022063.tif,2022063,2022063,225.72,대형,4,test
229,T52SDF_20220424T020701_2022071.tif,2022071,2022071,3.00,중소형,1,train
230,T52SDG_20160126T021710_2016001.tif,2016001,2016001,3.00,중소형,1,train
231,T52SDG_20160218T022652_2016003.tif,2016003,2016003,3.00,중소형,1,test
232,T52SDG_20160309T022651_2016003.tif,2016003,2016003,3.00,중소형,1,train
233,T52SDG_20160408T022530_2016017.tif,2016017,2016017,1.00,중소형,1,train
234,T52SDG_20160408T022530_2016021.tif,2016021,2016021,4.70,중소형,1,val
235,T52SDG_20160515T020702_2016027.tif,2016027,2016027,2.00,중소형,1,train
236,T52SDG_20160518T021612_2016027.tif,2016027,2016027,2.00,중소형,1,val
237,T52SDG_20160528T022702_2016028.tif,2016028,2016028,13.00,중소형,2,train
238,T52SDG_20170311T021651_2017003.tif,2017003,2017003,160.41,대형,4,train
239,T52SDG_20170520T020701_2017027.tif,2017027,2017027,252.00,대형,4,test
240,T52SDG_20170520T020701_2017029.tif,2017029,2017029,765.12,대형,4,val
241,T52SDG_20190405T020659_2019027.tif,2019027,2019027,1260.15,대형,5,val
242,T52SDG_20190408T021609_2019027.tif,2019027,2019027,1260.15,대형,5,train
243,T52SDG_20190413T021611_2019027.tif,2019027,2019027,1260.15,대형,5,train
244,T52SDG_20190415T020659_2019027.tif,2019027,2019027,1260.15,대형,5,test
245,T52SDG_20190408T021609_2019031.tif,2019031,2019031,4.00,중소형,1,train
246,T52SDG_20190508T021609_2019046.tif,2019046,2019046,1.90,중소형,1,train
247,T52SDG_20200330T020649_2020009.tif,2020009,2020009,1.40,중소형,1,train
248,T52SDG_20200409T020649_2020019.tif,2020019,2020019,11.91,중소형,2,val
249,T52SDG_20200427T021611_2020017.tif,2020017,2020017,1.50,중소형,1,train
250,T52SDG_20200429T020649_2020026.tif,2020026,2020026,1.70,중소형,1,train
251,T52SDG_20210206T021849_2021004.tif,2021004,2021004,2.02,중소형,1,train
252,T52SDG_20210208T020851_2021004.tif,2021004,2021004,2.02,중소형,1,train
253,T52SDG_20210213T020809_2021005.tif,2021005,2021005,3.70,중소형,1,test
254,T52SDG_20210218T020731_2021007.tif,2021007,2021007,2.70,중소형,1,train
255,T52SDG_20210221T021721_2021009.tif,2021009,2021009,24.56,중소형,2,val
256,T52SDG_20210223T020659_2021009.tif,2021009,2021009,24.56,중소형,2,test
257,T52SDG_20210313T021601_2021015.tif,2021015,2021015,4.42,중소형,1,train
258,T52SDG_20210402T021601_2021016.tif,2021016,2021016,20.00,중소형,2,test
259,T52SDG_20210402T021601_2021019.tif,2021019,2021019,10.70,중소형,2,train
260,T52SDG_20220223T020701_2022017.tif,2022017,2022017,3.95,중소형,1,train
261,T52SDG_20220228T020649_2022020.tif,2022020,2022020,4.10,중소형,1,train
262,T52SDG_20220305T020701_2022032.tif,2022032,2022032,30.89,중소형,3,train
263,T52SDG_20220308T021611_2022032.tif,2022032,2022032,30.89,중소형,3,train
264,T52SDG_20220305T020701_2022035.tif,2022035,2022035,184.01,대형,4,test
265,T52SDG_20220308T021611_2022035.tif,2022035,2022035,184.01,대형,4,train
266,T52SDG_20220305T020701_2022041.tif,2022041,2022041,4190.38,대형,5,train
267,T52SDG_20220310T020649_2022041.tif,2022041,2022041,4190.38,대형,5,train
268,T52SDG_20220315T020701_2022041.tif,2022041,2022041,4190.38,대형,5,val
269,T52SDG_20220315T020701_2022045.tif,2022045,2022045,8.00,중소형,2,val
270,T52SDG_20220524T020701_2022076.tif,2022076,2022076,2.25,중소형,1,test
271,T52SDG_20220524T020701_2022079.tif,2022079,2022079,1.20,중소형,1,train
272,T52SDH_20160408T022530_2016014.tif,2016014,2016014,14.40,중소형,2,test
273,T52SDH_20180115T021021_2018002.tif,2018002,2018002,17.73,중소형,2,train
274,T52SDH_20180329T021651_2018021.tif,2018021,2018021,356.85,대형,4,train
275,T52SDH_20180331T020649_2018021.tif,2018021,2018021,356.85,대형,4,test
276,T52SDH_20180420T020649_2018025.tif,2018025,2018025,13.08,중소형,2,val
277,T52SDH_20180428T021611_2018027.tif,2018027,2018027,3.00,중소형,1,train
278,T52SDH_20190103T022101_2019001.tif,2019001,2019001,97.94,중소형,3,test

In [221]:
os.getcwd()

'D:\\deep_learning\\Sentinel_forestfire\\MY_TEST_SENTINEL_IMAGERY_DATA\\imagery_data_complete_0828\\data\\image'

In [21]:
os.chdir('../mask')

In [22]:
os.getcwd()

'D:\\deep_learning\\Sentinel_forestfire\\MY_TEST_SENTINEL_IMAGERY_DATA\\imagery_data_complete_0828\\data\\mask'

In [23]:
masks = glob('*.tif')

In [24]:
masks[0][-16:-9]

'2022027'

In [25]:
masks_s = pd.Series(masks)

In [26]:
masks_df = masks_s.to_frame()

In [27]:
masks_df['mask_id']=''

In [28]:
for index, row in masks_df.iterrows():
    maskid = row[0][-16:-9]
    masks_df.at[index,'mask_id'] = maskid

In [29]:
masks[0][:-9]

'T51SYU_20220226T021651_2022027'

In [30]:
masks_df['target_fname']=''
for index, row in masks_df.iterrows():
    tname = row[0][:-9]
    masks_df.at[index,'target_fname'] = tname+'.tif'

In [31]:
masks_df

,0,mask_id,target_fname
0,T51SYU_20220226T021651_2022027_mask.tif,2022027,T51SYU_20220226T021651_2022027.tif
1,T51SYU_20220303T021609_2022027_mask.tif,2022027,T51SYU_20220303T021609_2022027.tif
2,T52SBC_20200427T021611_2020027_mask.tif,2020027,T52SBC_20200427T021611_2020027.tif
3,T52SBD_20220402T021559_2022046_mask.tif,2022046,T52SBD_20220402T021559_2022046.tif
4,T52SBE_20170413T021601_2017002_mask.tif,2017002,T52SBE_20170413T021601_2017002.tif
5,T52SBE_20210407T021559_2021017_mask.tif,2021017,T52SBE_20210407T021559_2021017.tif
6,T52SBE_20220522T021609_2022077_mask.tif,2022077,T52SBE_20220522T021609_2022077.tif
7,T52SBF_20220303T021609_2022028_mask.tif,2022028,T52SBF_20220303T021609_2022028.tif
8,T52SBF_20220308T021611_2022038_mask.tif,2022038,T52SBF_20220308T021611_2022038.tif
9,T52SBF_20220417T021611_2022058_mask.tif,2022058,T52SBF_20220417T021611_2022058.tif
10,T52SBG_20160329T022653_2016008_mask.tif,2016008,T52SBG_20160329T022653_2016008.tif
11,T52SBG_20160408T022530_2016008_mask.tif,2016008,T52SBG_20160408T022530_2016008.tif
12,T52SBG_20160508T022702_2016026_mask.tif,2016026,T52SBG_20160508T022702_2016026.tif
13,T52SBG_20161005T021602_2016029_mask.tif,2016029,T52SBG_20161005T021602_2016029.tif
14,T52SBG_20161214T022102_2016030_mask.tif,2016030,T52SBG_20161214T022102_2016030.tif
15,T52SBG_20170324T021601_2017006_mask.tif,2017006,T52SBG_20170324T021601_2017006.tif
16,T52SBG_20170403T022701_2017006_mask.tif,2017006,T52SBG_20170403T022701_2017006.tif
17,T52SBG_20170403T022701_2017013_mask.tif,2017013,T52SBG_20170403T022701_2017013.tif
18,T52SBG_20170503T021611_2017018_mask.tif,2017018,T52SBG_20170503T021611_2017018.tif
19,T52SBG_20170526T022551_2017026_mask.tif,2017026,T52SBG_20170526T022551_2017026.tif
20,T52SBG_20200318T021601_2020003_mask.tif,2020003,T52SBG_20200318T021601_2020003.tif
21,T52SBG_20200323T021559_2020006_mask.tif,2020006,T52SBG_20200323T021559_2020006.tif
22,T52SBG_20200427T021611_2020021_mask.tif,2020021,T52SBG_20200427T021611_2020021.tif
23,T52SCD_20190403T021651_2019020_mask.tif,2019020,T52SCD_20190403T021651_2019020.tif
24,T52SCD_20201208T022059_2020034_mask.tif,2020034,T52SCD_20201208T022059_2020034.tif
25,T52SCD_20210213T020809_2021006_mask.tif,2021006,T52SCD_20210213T020809_2021006.tif
26,T52SCD_20210305T020649_2021014_mask.tif,2021014,T52SCD_20210305T020649_2021014.tif
27,T52SCD_20210414T020649_2021020_mask.tif,2021020,T52SCD_20210414T020649_2021020.tif
28,T52SCD_20210429T020651_2021022_mask.tif,2021022,T52SCD_20210429T020651_2021022.tif
29,T52SCD_20211228T022111_2021027_mask.tif,2021027,T52SCD_20211228T022111_2021027.tif
30,T52SCD_20211230T021059_2021027_mask.tif,2021027,T52SCD_20211230T021059_2021027.tif
31,T52SCD_20220203T020911_2022003_mask.tif,2022003,T52SCD_20220203T020911_2022003.tif
32,T52SCD_20220226T021651_2022022_mask.tif,2022022,T52SCD_20220226T021651_2022022.tif
33,T52SCD_20220226T021651_2022023_mask.tif,2022023,T52SCD_20220226T021651_2022023.tif
34,T52SCD_20220412T021559_2022055_mask.tif,2022055,T52SCD_20220412T021559_2022055.tif
35,T52SCE_20171211T021049_2017037_mask.tif,2017037,T52SCE_20171211T021049_2017037.tif
36,T52SCE_20180217T021741_2018012_mask.tif,2018012,T52SCE_20180217T021741_2018012.tif
37,T52SCE_20180821T021559_2018034_mask.tif,2018034,T52SCE_20180821T021559_2018034.tif
38,T52SCE_20180905T021601_2018034_mask.tif,2018034,T52SCE_20180905T021601_2018034.tif
39,T52SCE_20190408T021609_2019025_mask.tif,2019025,T52SCE_20190408T021609_2019025.tif
40,T52SCE_20200409T020649_2020018_mask.tif,2020018,T52SCE_20200409T020649_2020018.tif
41,T52SCE_20210104T021059_2021001_mask.tif,2021001,T52SCE_20210104T021059_2021001.tif
42,T52SCE_20210107T022059_2021001_mask.tif,2021001,T52SCE_20210107T022059_2021001.tif
43,T52SCE_20210109T021051_2021001_mask.tif,2021001,T52SCE_20210109T021051_2021001.tif
44,T52SCE_20210502T021601_2021023_mask.tif,2021023,T52SCE_20210502T021601_2021023.tif
45,T52SCE_20210509T020651_2021023_mask.tif,2021023,T52SCE_20210509T020651_2021023.tif
46,T52SCE_20220226T021651_2022021_mask.tif,2022021,T52SCE_20220226T021651_2022021.tif
47,T52SCE_20220305T020701_2022033_mask.tif,2022033,T52SCE_20220305T020701_2022033.tif
48,T52SCE_20220315T020701_2022047_mask.tif,2022047,T52SCE_20220315T020701_2022047.tif
49,T52SCE_20220404T020701_2022049_mask.tif,2022049,T52SCE_20220404T020701_2022049.tif
50,T52SCE_20220502T021559_2022073_mask.tif,2022073,T52SCE_20220502T021559_2022073.tif
51,T52SCF_20160408T022530_2016018_mask.tif,2016018,T52SCF_20160408T022530_2016018.tif
52,T52SCF_20170503T021611_2017019_mask.tif,2017019,T52SCF_20170503T021611_2017019.tif
53,T52SCF_20170612T021601_2017033_mask.tif,2017033,T52SCF_20170612T021601_2017033.tif
54,T52SCF_20170727T021559_2017034_mask.tif,2017034,T52SCF_20170727T021559_2017034.tif
55,T52SCF_20171214T022059_2017036_mask.tif,2017036,T52SCF_20171214T022059_2017036.tif
56,T52SCF_20190408T021609_2019032_mask.tif,2019032,T52SCF_20190408T021609_2019032.tif
57,T52SCF_20190418T021609_2019041_mask.tif,2019041,T52SCF_20190418T021609_2019041.tif
58,T52SCF_20190503T021611_2019041_mask.tif,2019041,T52SCF_20190503T021611_2019041.tif
59,T52SCF_20190503T021611_2019042_mask.tif,2019042,T52SCF_20190503T021611_2019042.tif
60,T52SCF_20210226T021639_2021010_mask.tif,2021010,T52SCF_20210226T021639_2021010.tif
61,T52SCF_20210904T021559_2021025_mask.tif,2021025,T52SCF_20210904T021559_2021025.tif
62,T52SCF_20220226T021651_2022012_mask.tif,2022012,T52SCF_20220226T021651_2022012.tif
63,T52SCF_20220417T021611_2022054_mask.tif,2022054,T52SCF_20220417T021611_2022054.tif
64,T52SCF_20220424T020701_2022072_mask.tif,2022072,T52SCF_20220424T020701_2022072.tif
65,T52SCF_20221208T022059_2022084_mask.tif,2022084,T52SCF_20221208T022059_2022084.tif
66,T52SCG_20160309T022651_2016004_mask.tif,2016004,T52SCG_20160309T022651_2016004.tif
67,T52SCG_20160408T021612_2016020_mask.tif,2016020,T52SCG_20160408T021612_2016020.tif
68,T52SCG_20160408T021612_2016022_mask.tif,2016022,T52SCG_20160408T021612_2016022.tif
69,T52SCG_20160408T021612_2016023_mask.tif,2016023,T52SCG_20160408T021612_2016023.tif
70,T52SCG_20160408T022530_2016005_mask.tif,2016005,T52SCG_20160408T022530_2016005.tif
71,T52SCG_20160408T022530_2016011_mask.tif,2016011,T52SCG_20160408T022530_2016011.tif
72,T52SCG_20160408T022530_2016013_mask.tif,2016013,T52SCG_20160408T022530_2016013.tif
73,T52SCG_20160408T022530_2016015_mask.tif,2016015,T52SCG_20160408T022530_2016015.tif
74,T52SCG_20160428T022700_2016019_mask.tif,2016019,T52SCG_20160428T022700_2016019.tif
75,T52SCG_20160428T022702_2016025_mask.tif,2016025,T52SCG_20160428T022702_2016025.tif
76,T52SCG_20170403T022701_2017005_mask.tif,2017005,T52SCG_20170403T022701_2017005.tif
77,T52SCG_20170403T022701_2017007_mask.tif,2017007,T52SCG_20170403T022701_2017007.tif
78,T52SCG_20170403T022701_2017008_mask.tif,2017008,T52SCG_20170403T022701_2017008.tif
79,T52SCG_20170403T022701_2017012_mask.tif,2017012,T52SCG_20170403T022701_2017012.tif
80,T52SCG_20170413T021601_2017014_mask.tif,2017014,T52SCG_20170413T021601_2017014.tif
81,T52SCG_20170413T021601_2017015_mask.tif,2017015,T52SCG_20170413T021601_2017015.tif
82,T52SCG_20170413T021601_2017016_mask.tif,2017016,T52SCG_20170413T021601_2017016.tif
83,T52SCG_20170503T021611_2017021_mask.tif,2017021,T52SCG_20170503T021611_2017021.tif
84,T52SCG_20170503T021611_2017022_mask.tif,2017022,T52SCG_20170503T021611_2017022.tif
85,T52SCG_20170503T021611_2017023_mask.tif,2017023,T52SCG_20170503T021611_2017023.tif
86,T52SCG_20170602T022701_2017023_mask.tif,2017023,T52SCG_20170602T022701_2017023.tif
87,T52SCG_20170602T022701_2017031_mask.tif,2017031,T52SCG_20170602T022701_2017031.tif
88,T52SCG_20180202T021909_2018003_mask.tif,2018003,T52SCG_20180202T021909_2018003.tif
89,T52SCG_20180324T021559_2018018_mask.tif,2018018,T52SCG_20180324T021559_2018018.tif
90,T52SCG_20180428T021611_2018026_mask.tif,2018026,T52SCG_20180428T021611_2018026.tif
91,T52SCG_20180707T021601_2018028_mask.tif,2018028,T52SCG_20180707T021601_2018028.tif
92,T52SCG_20190207T021849_2019005_mask.tif,2019005,T52SCG_20190207T021849_2019005.tif
93,T52SCG_20190314T021601_2019010_mask.tif,2019010,T52SCG_20190314T021601_2019010.tif
94,T52SCG_20190324T021601_2019011_mask.tif,2019011,T52SCG_20190324T021601_2019011.tif
95,T52SCG_20190324T021601_2019013_mask.tif,2019013,T52SCG_20190324T021601_2019013.tif
96,T52SCG_20190408T021609_2019024_mask.tif,2019024,T52SCG_20190408T021609_2019024.tif
97,T52SCG_20190408T021609_2019033_mask.tif,2019033,T52SCG_20190408T021609_2019033.tif
98,T52SCG_20190413T021611_2019039_mask.tif,2019039,T52SCG_20190413T021611_2019039.tif
99,T52SCG_20190523T021611_2019045_mask.tif,2019045,T52SCG_20190523T021611_2019045.tif
100,T52SCG_20200323T021559_2020005_mask.tif,2020005,T52SCG_20200323T021559_2020005.tif
101,T52SCG_20200402T021559_2020013_mask.tif,2020013,T52SCG_20200402T021559_2020013.tif
102,T52SCG_20200407T021601_2020013_mask.tif,2020013,T52SCG_20200407T021601_2020013.tif
103,T52SCG_20200407T021601_2020014_mask.tif,2020014,T52SCG_20200407T021601_2020014.tif
104,T52SCG_20200407T021601_2020016_mask.tif,2020016,T52SCG_20200407T021601_2020016.tif
105,T52SCG_20200427T021611_2020022_mask.tif,2020022,T52SCG_20200427T021611_2020022.tif
106,T52SCG_20200507T021611_2020022_mask.tif,2020022,T52SCG_20200507T021611_2020022.tif
107,T52SCG_20200507T021611_2020024_mask.tif,2020024,T52SCG_20200507T021611_2020024.tif
108,T52SCG_20200527T021611_2020022_mask.tif,2020022,T52SCG_20200527T021611_2020022.tif
109,T52SCG_20201113T021941_2020033_mask.tif,2020033,T52SCG_20201113T021941_2020033.tif
110,T52SCG_20220226T021651_2022018_mask.tif,2022018,T52SCG_20220226T021651_2022018.tif
111,T52SCG_20220308T021611_2022034_mask.tif,2022034,T52SCG_20220308T021611_2022034.tif
112,T52SCG_20220308T021611_2022040_mask.tif,2022040,T52SCG_20220308T021611_2022040.tif
113,T52SCG_20220328T021611_2022043_mask.tif,2022043,T52SCG_20220328T021611_2022043.tif
114,T52SCG_20220407T021601_2022050_mask.tif,2022050,T52SCG_20220407T021601_2022050.tif
115,T52SCG_20220412T021559_2022056_mask.tif,2022056,T52SCG_20220412T021559_2022056.tif
116,T52SCG_20220417T021611_2022053_mask.tif,2022053,T52SCG_20220417T021611_2022053.tif
117,T52SCG_20220417T021611_2022056_mask.tif,2022056,T52SCG_20220417T021611_2022056.tif
118,T52SCG_20220427T021611_2022069_mask.tif,2022069,T52SCG_20220427T021611_2022069.tif
119,T52SCG_20220527T021611_2022075_mask.tif,2022075,T52SCG_20220527T021611_2022075.tif
120,T52SCH_20160408T021612_2016007_mask.tif,2016007,T52SCH_20160408T021612_2016007.tif
121,T52SCH_20160408T022530_2016010_mask.tif,2016010,T52SCH_20160408T022530_2016010.tif
122,T52SCH_20160408T022530_2016019_mask.tif,2016019,T52SCH_20160408T022530_2016019.tif
123,T52SCH_20170413T021601_2017009_mask.tif,2017009,T52SCH_20170413T021601_2017009.tif
124,T52SCH_20170503T021611_2017017_mask.tif,2017017,T52SCH_20170503T021611_2017017.tif
125,T52SCH_20171119T022001_2017035_mask.tif,2017035,T52SCH_20171119T022001_2017035.tif
126,T52SCH_20180413T021559_2018022_mask.tif,2018022,T52SCH_20180413T021559_2018022.tif
127,T52SCH_20180831T021559_2018033_mask.tif,2018033,T52SCH_20180831T021559_2018033.tif
128,T52SCH_20190123T022001_2019002_mask.tif,2019002,T52SCH_20190123T022001_2019002.tif
129,T52SCH_20190128T021949_2019003_mask.tif,2019003,T52SCH_20190128T021949_2019003.tif
130,T52SCH_20190304T021601_2019009_mask.tif,2019009,T52SCH_20190304T021601_2019009.tif
131,T52SCH_20190314T021601_2019009_mask.tif,2019009,T52SCH_20190314T021601_2019009.tif
132,T52SCH_20190403T021651_2019022_mask.tif,2019022,T52SCH_20190403T021651_2019022.tif
133,T52SCH_20190408T021609_2019030_mask.tif,2019030,T52SCH_20190408T021609_2019030.tif
134,T52SCH_20190508T021609_2019047_mask.tif,2019047,T52SCH_20190508T021609_2019047.tif
135,T52SCH_20190508T021609_2019048_mask.tif,2019048,T52SCH_20190508T021609_2019048.tif
136,T52SCH_20190523T021611_2019049_mask.tif,2019049,T52SCH_20190523T021611_2019049.tif
137,T52SCH_20200113T022039_2020001_mask.tif,2020001,T52SCH_20200113T022039_2020001.tif
138,T52SCH_20200118T022021_2020001_mask.tif,2020001,T52SCH_20200118T022021_2020001.tif
139,T52SCH_20200328T021601_2020011_mask.tif,2020011,T52SCH_20200328T021601_2020011.tif
140,T52SCH_20200402T021559_2020012_mask.tif,2020012,T52SCH_20200402T021559_2020012.tif
141,T52SCH_20200422T021559_2020023_mask.tif,2020023,T52SCH_20200422T021559_2020023.tif
142,T52SCH_20220102T022059_2021028_mask.tif,2021028,T52SCH_20220102T022059_2021028.tif
143,T52SCH_20220216T021751_2022008_mask.tif,2022008,T52SCH_20220216T021751_2022008.tif
144,T52SCH_20220417T021611_2022057_mask.tif,2022057,T52SCH_20220417T021611_2022057.tif
145,T52SCH_20220417T021611_2022062_mask.tif,2022062,T52SCH_20220417T021611_2022062.tif
146,T52SCH_20220417T021611_2022064_mask.tif,2022064,T52SCH_20220417T021611_2022064.tif
147,T52SDD_20180130T020919_2018004_mask.tif,2018004,T52SDD_20180130T020919_2018004.tif
148,T52SDD_20180224T020651_2018007_mask.tif,2018007,T52SDD_20180224T020651_2018007.tif
149,T52SDD_20190301T020651_2019008_mask.tif,2019008,T52SDD_20190301T020651_2019008.tif
150,T52SDD_20220208T020829_2022006_mask.tif,2022006,T52SDD_20220208T020829_2022006.tif
151,T52SDD_20220305T020701_2022019_mask.tif,2022019,T52SDD_20220305T020701_2022019.tif
152,T52SDD_20221230T021111_2022085_mask.tif,2022085,T52SDD_20221230T021111_2022085.tif
153,T52SDE_20170321T020651_2017004_mask.tif,2017004,T52SDE_20170321T020651_2017004.tif
154,T52SDE_20170430T020701_2017020_mask.tif,2017020,T52SDE_20170430T020701_2017020.tif
155,T52SDE_20170609T020651_2017032_mask.tif,2017032,T52SDE_20170609T020651_2017032.tif
156,T52SDE_20171221T021059_2017040_mask.tif,2017040,T52SDE_20171221T021059_2017040.tif
157,T52SDE_20180209T020829_2018006_mask.tif,2018006,T52SDE_20180209T020829_2018006.tif
158,T52SDE_20180219T020719_2018014_mask.tif,2018014,T52SDE_20180219T020719_2018014.tif
159,T52SDE_20180222T021709_2018015_mask.tif,2018015,T52SDE_20180222T021709_2018015.tif
160,T52SDE_20180408T021601_2018024_mask.tif,2018024,T52SDE_20180408T021601_2018024.tif
161,T52SDE_20180729T020649_2018030_mask.tif,2018030,T52SDE_20180729T020649_2018030.tif
162,T52SDE_20180801T021649_2018030_mask.tif,2018030,T52SDE_20180801T021649_2018030.tif
163,T52SDE_20190331T030651_2019016_mask.tif,2019016,T52SDE_20190331T030651_2019016.tif
164,T52SDE_20190405T020659_2019026_mask.tif,2019026,T52SDE_20190405T020659_2019026.tif
165,T52SDE_20190415T020659_2019036_mask.tif,2019036,T52SDE_20190415T020659_2019036.tif
166,T52SDE_20190530T020701_2019050_mask.tif,2019050,T52SDE_20190530T020701_2019050.tif
167,T52SDE_20220114T021041_2022001_mask.tif,2022001,T52SDE_20220114T021041_2022001.tif
168,T52SDE_20220203T020911_2022004_mask.tif,2022004,T52SDE_20220203T020911_2022004.tif
169,T52SDE_20220218T020729_2022009_mask.tif,2022009,T52SDE_20220218T020729_2022009.tif
170,T52SDE_20220218T020729_2022013_mask.tif,2022013,T52SDE_20220218T020729_2022013.tif
171,T52SDE_20220218T020729_2022014_mask.tif,2022014,T52SDE_20220218T020729_2022014.tif
172,T52SDE_20220303T021609_2022030_mask.tif,2022030,T52SDE_20220303T021609_2022030.tif
173,T52SDE_20220305T020701_2022024_mask.tif,2022024,T52SDE_20220305T020701_2022024.tif
174,T52SDE_20220305T020701_2022037_mask.tif,2022037,T52SDE_20220305T020701_2022037.tif
175,T52SDE_20220315T020701_2022024_mask.tif,2022024,T52SDE_20220315T020701_2022024.tif
176,T52SDE_20220402T021559_2022048_mask.tif,2022048,T52SDE_20220402T021559_2022048.tif
177,T52SDE_20220417T021611_2022066_mask.tif,2022066,T52SDE_20220417T021611_2022066.tif
178,T52SDE_20220424T020701_2022067_mask.tif,2022067,T52SDE_20220424T020701_2022067.tif
179,T52SDE_20220424T020701_2022068_mask.tif,2022068,T52SDE_20220424T020701_2022068.tif
180,T52SDE_20220504T020701_2022074_mask.tif,2022074,T52SDE_20220504T020701_2022074.tif
181,T52SDE_20220522T021609_2022078_mask.tif,2022078,T52SDE_20220522T021609_2022078.tif
182,T52SDE_20220529T020659_2022080_mask.tif,2022080,T52SDE_20220529T020659_2022080.tif
183,T52SDE_20220601T021559_2022082_mask.tif,2022082,T52SDE_20220601T021559_2022082.tif
184,T52SDE_20220603T020701_2022080_mask.tif,2022080,T52SDE_20220603T020701_2022080.tif
185,T52SDE_20220603T020701_2022083_mask.tif,2022083,T52SDE_20220603T020701_2022083.tif
186,T52SDF_20160215T021228_2016002_mask.tif,2016002,T52SDF_20160215T021228_2016002.tif
187,T52SDF_20160408T021612_2016009_mask.tif,2016009,T52SDF_20160408T021612_2016009.tif
188,T52SDF_20160408T021612_2016016_mask.tif,2016016,T52SDF_20160408T021612_2016016.tif
189,T52SDF_20160408T022530_2016006_mask.tif,2016006,T52SDF_20160408T022530_2016006.tif
190,T52SDF_20160408T022530_2016012_mask.tif,2016012,T52SDF_20160408T022530_2016012.tif
191,T52SDF_20160408T022530_2016024_mask.tif,2016024,T52SDF_20160408T022530_2016024.tif
192,T52SDF_20170314T022651_2017001_mask.tif,2017001,T52SDF_20170314T022651_2017001.tif
193,T52SDF_20170403T022701_2017001_mask.tif,2017001,T52SDF_20170403T022701_2017001.tif
194,T52SDF_20170410T020651_2017010_mask.tif,2017010,T52SDF_20170410T020651_2017010.tif
195,T52SDF_20170410T020651_2017011_mask.tif,2017011,T52SDF_20170410T020651_2017011.tif
196,T52SDF_20170520T020701_2017025_mask.tif,2017025,T52SDF_20170520T020701_2017025.tif
197,T52SDF_20170520T020701_2017028_mask.tif,2017028,T52SDF_20170520T020701_2017028.tif
198,T52SDF_20180202T021909_2018005_mask.tif,2018005,T52SDF_20180202T021909_2018005.tif
199,T52SDF_20180324T021559_2018017_mask.tif,2018017,T52SDF_20180324T021559_2018017.tif
200,T52SDF_20181002T020651_2018032_mask.tif,2018032,T52SDF_20181002T020651_2018032.tif
201,T52SDF_20190319T021659_2019014_mask.tif,2019014,T52SDF_20190319T021659_2019014.tif
202,T52SDF_20190324T021601_2019014_mask.tif,2019014,T52SDF_20190324T021601_2019014.tif
203,T52SDF_20190403T021651_2019015_mask.tif,2019015,T52SDF_20190403T021651_2019015.tif
204,T52SDF_20190403T021651_2019017_mask.tif,2019017,T52SDF_20190403T021651_2019017.tif
205,T52SDF_20190403T021651_2019018_mask.tif,2019018,T52SDF_20190403T021651_2019018.tif
206,T52SDF_20190408T021609_2019038_mask.tif,2019038,T52SDF_20190408T021609_2019038.tif
207,T52SDF_20190415T020659_2019019_mask.tif,2019019,T52SDF_20190415T020659_2019019.tif
208,T52SDF_20190530T020701_2019051_mask.tif,2019051,T52SDF_20190530T020701_2019051.tif
209,T52SDF_20200308T021601_2020002_mask.tif,2020002,T52SDF_20200308T021601_2020002.tif
210,T52SDF_20200323T021559_2020007_mask.tif,2020007,T52SDF_20200323T021559_2020007.tif
211,T52SDF_20200404T020651_2020010_mask.tif,2020010,T52SDF_20200404T020651_2020010.tif
212,T52SDF_20200409T020649_2020020_mask.tif,2020020,T52SDF_20200409T020649_2020020.tif
213,T52SDF_20200427T021611_2020025_mask.tif,2020025,T52SDF_20200427T021611_2020025.tif
214,T52SDF_20200429T020649_2020025_mask.tif,2020025,T52SDF_20200429T020649_2020025.tif
215,T52SDF_20210223T020659_2021011_mask.tif,2021011,T52SDF_20210223T020659_2021011.tif
216,T52SDF_20210223T020659_2021012_mask.tif,2021012,T52SDF_20210223T020659_2021012.tif
217,T52SDF_20210223T020659_2021013_mask.tif,2021013,T52SDF_20210223T020659_2021013.tif
218,T52SDF_20210502T021601_2021021_mask.tif,2021021,T52SDF_20210502T021601_2021021.tif
219,T52SDF_20220112T022039_2022002_mask.tif,2022002,T52SDF_20220112T022039_2022002.tif
220,T52SDF_20220211T021819_2022007_mask.tif,2022007,T52SDF_20220211T021819_2022007.tif
221,T52SDF_20220218T020729_2022011_mask.tif,2022011,T52SDF_20220218T020729_2022011.tif
222,T52SDF_20220223T020701_2022016_mask.tif,2022016,T52SDF_20220223T020701_2022016.tif
223,T52SDF_20220303T021609_2022026_mask.tif,2022026,T52SDF_20220303T021609_2022026.tif
224,T52SDF_20220308T021611_2022039_mask.tif,2022039,T52SDF_20220308T021611_2022039.tif
225,T52SDF_20220407T021601_2022052_mask.tif,2022052,T52SDF_20220407T021601_2022052.tif
226,T52SDF_20220409T020649_2022052_mask.tif,2022052,T52SDF_20220409T020649_2022052.tif
227,T52SDF_20220412T021559_2022052_mask.tif,2022052,T52SDF_20220412T021559_2022052.tif
228,T52SDF_20220419T020649_2022063_mask.tif,2022063,T52SDF_20220419T020649_2022063.tif
229,T52SDF_20220424T020701_2022071_mask.tif,2022071,T52SDF_20220424T020701_2022071.tif

In [32]:
new_df2 = pd.merge(new_df, masks_df, left_on = 'filename', right_on = 'target_fname', how ='inner')

In [33]:
new_df2.columns.tolist()

['filename',
 'file_id',
 '산불ID',
 '피해면적',
 '규모구분(대형/중소형)',
 '규모구분(등급)',
 0,
 'mask_id',
 'target_fname']

In [34]:
new_df2 = new_df2.drop(columns = ['file_id', 'mask_id', 'target_fname'], axis = 1)

In [35]:
new_df2 = new_df2.rename(columns = {0 : 'maskfilename'})

In [36]:
new_df2.columns

Index(['filename', '산불ID', '피해면적', '규모구분(대형/중소형)', '규모구분(등급)', 'maskfilename'], dtype='object')

In [244]:
new_df2 = new_df2[['filename', 'maskfilename','산불ID', '피해면적', '규모구분(대형/중소형)', '규모구분(등급)', 'dataset' ]]

In [37]:
new_df2

,filename,산불ID,피해면적,규모구분(대형/중소형),규모구분(등급),maskfilename
0,T51SYU_20220226T021651_2022027.tif,2022027,2.00,중소형,1,T51SYU_20220226T021651_2022027_mask.tif
1,T51SYU_20220303T021609_2022027.tif,2022027,2.00,중소형,1,T51SYU_20220303T021609_2022027_mask.tif
2,T52SBC_20200427T021611_2020027.tif,2020027,1.82,중소형,1,T52SBC_20200427T021611_2020027_mask.tif
3,T52SBD_20220402T021559_2022046.tif,2022046,3.00,중소형,1,T52SBD_20220402T021559_2022046_mask.tif
4,T52SBE_20170413T021601_2017002.tif,2017002,1.00,중소형,1,T52SBE_20170413T021601_2017002_mask.tif
5,T52SBE_20210407T021559_2021017.tif,2021017,2.00,중소형,1,T52SBE_20210407T021559_2021017_mask.tif
6,T52SBE_20220522T021609_2022077.tif,2022077,2.50,중소형,1,T52SBE_20220522T021609_2022077_mask.tif
7,T52SBF_20220303T021609_2022028.tif,2022028,1.50,중소형,1,T52SBF_20220303T021609_2022028_mask.tif
8,T52SBF_20220308T021611_2022038.tif,2022038,5.00,중소형,2,T52SBF_20220308T021611_2022038_mask.tif
9,T52SBF_20220417T021611_2022058.tif,2022058,158.11,대형,4,T52SBF_20220417T021611_2022058_mask.tif
10,T52SBG_20160329T022653_2016008.tif,2016008,1.00,중소형,1,T52SBG_20160329T022653_2016008_mask.tif
11,T52SBG_20160408T022530_2016008.tif,2016008,1.00,중소형,1,T52SBG_20160408T022530_2016008_mask.tif
12,T52SBG_20160508T022702_2016026.tif,2016026,1.30,중소형,1,T52SBG_20160508T022702_2016026_mask.tif
13,T52SBG_20161005T021602_2016029.tif,2016029,2.15,중소형,1,T52SBG_20161005T021602_2016029_mask.tif
14,T52SBG_20161214T022102_2016030.tif,2016030,4.50,중소형,1,T52SBG_20161214T022102_2016030_mask.tif
15,T52SBG_20170324T021601_2017006.tif,2017006,3.00,중소형,1,T52SBG_20170324T021601_2017006_mask.tif
16,T52SBG_20170403T022701_2017006.tif,2017006,3.00,중소형,1,T52SBG_20170403T022701_2017006_mask.tif
17,T52SBG_20170403T022701_2017013.tif,2017013,1.00,중소형,1,T52SBG_20170403T022701_2017013_mask.tif
18,T52SBG_20170503T021611_2017018.tif,2017018,1.20,중소형,1,T52SBG_20170503T021611_2017018_mask.tif
19,T52SBG_20170526T022551_2017026.tif,2017026,1.00,중소형,1,T52SBG_20170526T022551_2017026_mask.tif
20,T52SBG_20200318T021601_2020003.tif,2020003,7.00,중소형,2,T52SBG_20200318T021601_2020003_mask.tif
21,T52SBG_20200323T021559_2020006.tif,2020006,2.68,중소형,1,T52SBG_20200323T021559_2020006_mask.tif
22,T52SBG_20200427T021611_2020021.tif,2020021,1.20,중소형,1,T52SBG_20200427T021611_2020021_mask.tif
23,T52SCD_20190403T021651_2019020.tif,2019020,7.00,중소형,2,T52SCD_20190403T021651_2019020_mask.tif
24,T52SCD_20201208T022059_2020034.tif,2020034,2.00,중소형,1,T52SCD_20201208T022059_2020034_mask.tif
25,T52SCD_20210213T020809_2021006.tif,2021006,3.00,중소형,1,T52SCD_20210213T020809_2021006_mask.tif
26,T52SCD_20210305T020649_2021014.tif,2021014,49.15,중소형,3,T52SCD_20210305T020649_2021014_mask.tif
27,T52SCD_20210414T020649_2021020.tif,2021020,1.40,중소형,1,T52SCD_20210414T020649_2021020_mask.tif
28,T52SCD_20210429T020651_2021022.tif,2021022,1.50,중소형,1,T52SCD_20210429T020651_2021022_mask.tif
29,T52SCD_20211228T022111_2021027.tif,2021027,10.00,중소형,2,T52SCD_20211228T022111_2021027_mask.tif
30,T52SCD_20211230T021059_2021027.tif,2021027,10.00,중소형,2,T52SCD_20211230T021059_2021027_mask.tif
31,T52SCD_20220203T020911_2022003.tif,2022003,4.40,중소형,1,T52SCD_20220203T020911_2022003_mask.tif
32,T52SCD_20220226T021651_2022022.tif,2022022,2.00,중소형,1,T52SCD_20220226T021651_2022022_mask.tif
33,T52SCD_20220226T021651_2022023.tif,2022023,29.00,중소형,2,T52SCD_20220226T021651_2022023_mask.tif
34,T52SCD_20220412T021559_2022055.tif,2022055,1.80,중소형,1,T52SCD_20220412T021559_2022055_mask.tif
35,T52SCE_20171211T021049_2017037.tif,2017037,5.00,중소형,2,T52SCE_20171211T021049_2017037_mask.tif
36,T52SCE_20180217T021741_2018012.tif,2018012,3.00,중소형,1,T52SCE_20180217T021741_2018012_mask.tif
37,T52SCE_20180821T021559_2018034.tif,2018034,1.00,중소형,1,T52SCE_20180821T021559_2018034_mask.tif
38,T52SCE_20180905T021601_2018034.tif,2018034,1.00,중소형,1,T52SCE_20180905T021601_2018034_mask.tif
39,T52SCE_20190408T021609_2019025.tif,2019025,1.00,중소형,1,T52SCE_20190408T021609_2019025_mask.tif
40,T52SCE_20200409T020649_2020018.tif,2020018,20.00,중소형,2,T52SCE_20200409T020649_2020018_mask.tif
41,T52SCE_20210104T021059_2021001.tif,2021001,3.00,중소형,1,T52SCE_20210104T021059_2021001_mask.tif
42,T52SCE_20210107T022059_2021001.tif,2021001,3.00,중소형,1,T52SCE_20210107T022059_2021001_mask.tif
43,T52SCE_20210109T021051_2021001.tif,2021001,3.00,중소형,1,T52SCE_20210109T021051_2021001_mask.tif
44,T52SCE_20210502T021601_2021023.tif,2021023,10.00,중소형,2,T52SCE_20210502T021601_2021023_mask.tif
45,T52SCE_20210509T020651_2021023.tif,2021023,10.00,중소형,2,T52SCE_20210509T020651_2021023_mask.tif
46,T52SCE_20220226T021651_2022021.tif,2022021,8.03,중소형,2,T52SCE_20220226T021651_2022021_mask.tif
47,T52SCE_20220305T020701_2022033.tif,2022033,16.30,중소형,2,T52SCE_20220305T020701_2022033_mask.tif
48,T52SCE_20220315T020701_2022047.tif,2022047,3.80,중소형,1,T52SCE_20220315T020701_2022047_mask.tif
49,T52SCE_20220404T020701_2022049.tif,2022049,5.00,중소형,2,T52SCE_20220404T020701_2022049_mask.tif
50,T52SCE_20220502T021559_2022073.tif,2022073,5.00,중소형,2,T52SCE_20220502T021559_2022073_mask.tif
51,T52SCF_20160408T022530_2016018.tif,2016018,4.80,중소형,1,T52SCF_20160408T022530_2016018_mask.tif
52,T52SCF_20170503T021611_2017019.tif,2017019,2.00,중소형,1,T52SCF_20170503T021611_2017019_mask.tif
53,T52SCF_20170612T021601_2017033.tif,2017033,3.12,중소형,1,T52SCF_20170612T021601_2017033_mask.tif
54,T52SCF_20170727T021559_2017034.tif,2017034,6.30,중소형,2,T52SCF_20170727T021559_2017034_mask.tif
55,T52SCF_20171214T022059_2017036.tif,2017036,4.80,중소형,1,T52SCF_20171214T022059_2017036_mask.tif
56,T52SCF_20190408T021609_2019032.tif,2019032,1.30,중소형,1,T52SCF_20190408T021609_2019032_mask.tif
57,T52SCF_20190418T021609_2019041.tif,2019041,1.50,중소형,1,T52SCF_20190418T021609_2019041_mask.tif
58,T52SCF_20190503T021611_2019041.tif,2019041,1.50,중소형,1,T52SCF_20190503T021611_2019041_mask.tif
59,T52SCF_20190503T021611_2019042.tif,2019042,2.00,중소형,1,T52SCF_20190503T021611_2019042_mask.tif
60,T52SCF_20210226T021639_2021010.tif,2021010,34.13,중소형,3,T52SCF_20210226T021639_2021010_mask.tif
61,T52SCF_20210904T021559_2021025.tif,2021025,5.00,중소형,2,T52SCF_20210904T021559_2021025_mask.tif
62,T52SCF_20220226T021651_2022012.tif,2022012,1.80,중소형,1,T52SCF_20220226T021651_2022012_mask.tif
63,T52SCF_20220417T021611_2022054.tif,2022054,4.00,중소형,1,T52SCF_20220417T021611_2022054_mask.tif
64,T52SCF_20220424T020701_2022072.tif,2022072,2.82,중소형,1,T52SCF_20220424T020701_2022072_mask.tif
65,T52SCF_20221208T022059_2022084.tif,2022084,5.00,중소형,2,T52SCF_20221208T022059_2022084_mask.tif
66,T52SCG_20160309T022651_2016004.tif,2016004,2.70,중소형,1,T52SCG_20160309T022651_2016004_mask.tif
67,T52SCG_20160408T021612_2016020.tif,2016020,1.00,중소형,1,T52SCG_20160408T021612_2016020_mask.tif
68,T52SCG_20160408T021612_2016022.tif,2016022,3.90,중소형,1,T52SCG_20160408T021612_2016022_mask.tif
69,T52SCG_20160408T021612_2016023.tif,2016023,2.00,중소형,1,T52SCG_20160408T021612_2016023_mask.tif
70,T52SCG_20160408T022530_2016005.tif,2016005,2.00,중소형,1,T52SCG_20160408T022530_2016005_mask.tif
71,T52SCG_20160408T022530_2016011.tif,2016011,8.30,중소형,2,T52SCG_20160408T022530_2016011_mask.tif
72,T52SCG_20160408T022530_2016013.tif,2016013,1.00,중소형,1,T52SCG_20160408T022530_2016013_mask.tif
73,T52SCG_20160408T022530_2016015.tif,2016015,2.60,중소형,1,T52SCG_20160408T022530_2016015_mask.tif
74,T52SCG_20160428T022700_2016019.tif,2016019,7.00,중소형,2,T52SCG_20160428T022700_2016019_mask.tif
75,T52SCH_20160408T022530_2016019.tif,2016019,7.00,중소형,2,T52SCH_20160408T022530_2016019_mask.tif
76,T52SCG_20160428T022702_2016025.tif,2016025,2.00,중소형,1,T52SCG_20160428T022702_2016025_mask.tif
77,T52SCG_20170403T022701_2017005.tif,2017005,2.00,중소형,1,T52SCG_20170403T022701_2017005_mask.tif
78,T52SCG_20170403T022701_2017007.tif,2017007,2.00,중소형,1,T52SCG_20170403T022701_2017007_mask.tif
79,T52SCG_20170403T022701_2017008.tif,2017008,1.30,중소형,1,T52SCG_20170403T022701_2017008_mask.tif
80,T52SCG_20170403T022701_2017012.tif,2017012,1.00,중소형,1,T52SCG_20170403T022701_2017012_mask.tif
81,T52SCG_20170413T021601_2017014.tif,2017014,2.50,중소형,1,T52SCG_20170413T021601_2017014_mask.tif
82,T52SCG_20170413T021601_2017015.tif,2017015,2.50,중소형,1,T52SCG_20170413T021601_2017015_mask.tif
83,T52SCG_20170413T021601_2017016.tif,2017016,1.00,중소형,1,T52SCG_20170413T021601_2017016_mask.tif
84,T52SCG_20170503T021611_2017021.tif,2017021,1.00,중소형,1,T52SCG_20170503T021611_2017021_mask.tif
85,T52SCG_20170503T021611_2017022.tif,2017022,2.00,중소형,1,T52SCG_20170503T021611_2017022_mask.tif
86,T52SCG_20170503T021611_2017023.tif,2017023,1.30,중소형,1,T52SCG_20170503T021611_2017023_mask.tif
87,T52SCG_20170602T022701_2017023.tif,2017023,1.30,중소형,1,T52SCG_20170602T022701_2017023_mask.tif
88,T52SCG_20170602T022701_2017031.tif,2017031,1.70,중소형,1,T52SCG_20170602T022701_2017031_mask.tif
89,T52SCG_20180202T021909_2018003.tif,2018003,3.00,중소형,1,T52SCG_20180202T021909_2018003_mask.tif
90,T52SCG_20180324T021559_2018018.tif,2018018,1.10,중소형,1,T52SCG_20180324T021559_2018018_mask.tif
91,T52SCG_20180428T021611_2018026.tif,2018026,1.00,중소형,1,T52SCG_20180428T021611_2018026_mask.tif
92,T52SCG_20180707T021601_2018028.tif,2018028,1.00,중소형,1,T52SCG_20180707T021601_2018028_mask.tif
93,T52SCG_20190207T021849_2019005.tif,2019005,1.45,중소형,1,T52SCG_20190207T021849_2019005_mask.tif
94,T52SCG_20190314T021601_2019010.tif,2019010,1.00,중소형,1,T52SCG_20190314T021601_2019010_mask.tif
95,T52SCG_20190324T021601_2019011.tif,2019011,1.00,중소형,1,T52SCG_20190324T021601_2019011_mask.tif
96,T52SCG_20190324T021601_2019013.tif,2019013,1.00,중소형,1,T52SCG_20190324T021601_2019013_mask.tif
97,T52SCG_20190408T021609_2019024.tif,2019024,3.50,중소형,1,T52SCG_20190408T021609_2019024_mask.tif
98,T52SCG_20190408T021609_2019033.tif,2019033,1.00,중소형,1,T52SCG_20190408T021609_2019033_mask.tif
99,T52SCG_20190413T021611_2019039.tif,2019039,1.50,중소형,1,T52SCG_20190413T021611_2019039_mask.tif
100,T52SCG_20190523T021611_2019045.tif,2019045,1.50,중소형,1,T52SCG_20190523T021611_2019045_mask.tif
101,T52SCG_20200323T021559_2020005.tif,2020005,2.20,중소형,1,T52SCG_20200323T021559_2020005_mask.tif
102,T52SCG_20200402T021559_2020013.tif,2020013,3.75,중소형,1,T52SCG_20200402T021559_2020013_mask.tif
103,T52SCG_20200407T021601_2020013.tif,2020013,3.75,중소형,1,T52SCG_20200407T021601_2020013_mask.tif
104,T52SCG_20200407T021601_2020014.tif,2020014,6.20,중소형,2,T52SCG_20200407T021601_2020014_mask.tif
105,T52SCG_20200407T021601_2020016.tif,2020016,2.70,중소형,1,T52SCG_20200407T021601_2020016_mask.tif
106,T52SCG_20200427T021611_2020022.tif,2020022,2.75,중소형,1,T52SCG_20200427T021611_2020022_mask.tif
107,T52SCG_20200507T021611_2020022.tif,2020022,2.75,중소형,1,T52SCG_20200507T021611_2020022_mask.tif
108,T52SCG_20200527T021611_2020022.tif,2020022,2.75,중소형,1,T52SCG_20200527T021611_2020022_mask.tif
109,T52SCG_20200507T021611_2020024.tif,2020024,3.56,중소형,1,T52SCG_20200507T021611_2020024_mask.tif
110,T52SCG_20201113T021941_2020033.tif,2020033,3.00,중소형,1,T52SCG_20201113T021941_2020033_mask.tif
111,T52SCG_20220226T021651_2022018.tif,2022018,3.00,중소형,1,T52SCG_20220226T021651_2022018_mask.tif
112,T52SCG_20220308T021611_2022034.tif,2022034,1.80,중소형,1,T52SCG_20220308T021611_2022034_mask.tif
113,T52SCG_20220308T021611_2022040.tif,2022040,8.00,중소형,2,T52SCG_20220308T021611_2022040_mask.tif
114,T52SCG_20220328T021611_2022043.tif,2022043,5.00,중소형,2,T52SCG_20220328T021611_2022043_mask.tif
115,T52SCG_20220407T021601_2022050.tif,2022050,8.00,중소형,2,T52SCG_20220407T021601_2022050_mask.tif
116,T52SCG_20220412T021559_2022056.tif,2022056,1.50,중소형,1,T52SCG_20220412T021559_2022056_mask.tif
117,T52SCG_20220417T021611_2022056.tif,2022056,1.50,중소형,1,T52SCG_20220417T021611_2022056_mask.tif
118,T52SCG_20220417T021611_2022053.tif,2022053,8.00,중소형,2,T52SCG_20220417T021611_2022053_mask.tif
119,T52SCG_20220427T021611_2022069.tif,2022069,1.80,중소형,1,T52SCG_20220427T021611_2022069_mask.tif
120,T52SCG_20220527T021611_2022075.tif,2022075,4.00,중소형,1,T52SCG_20220527T021611_2022075_mask.tif
121,T52SCH_20160408T021612_2016007.tif,2016007,2.00,중소형,1,T52SCH_20160408T021612_2016007_mask.tif
122,T52SCH_20160408T022530_2016010.tif,2016010,1.50,중소형,1,T52SCH_20160408T022530_2016010_mask.tif
123,T52SCH_20170413T021601_2017009.tif,2017009,1.50,중소형,1,T52SCH_20170413T021601_2017009_mask.tif
124,T52SCH_20170503T021611_2017017.tif,2017017,1.50,중소형,1,T52SCH_20170503T021611_2017017_mask.tif
125,T52SCH_20171119T022001_2017035.tif,2017035,6.50,중소형,2,T52SCH_20171119T022001_2017035_mask.tif
126,T52SCH_20180413T021559_2018022.tif,2018022,1.50,중소형,1,T52SCH_20180413T021559_2018022_mask.tif
127,T52SCH_20180831T021559_2018033.tif,2018033,9.40,중소형,2,T52SCH_20180831T021559_2018033_mask.tif
128,T52SCH_20190123T022001_2019002.tif,2019002,1.46,중소형,1,T52SCH_20190123T022001_2019002_mask.tif
129,T52SCH_20190128T021949_2019003.tif,2019003,5.00,중소형,2,T52SCH_20190128T021949_2019003_mask.tif
130,T52SCH_20190304T021601_2019009.tif,2019009,1.00,중소형,1,T52SCH_20190304T021601_2019009_mask.tif
131,T52SCH_20190314T021601_2019009.tif,2019009,1.00,중소형,1,T52SCH_20190314T021601_2019009_mask.tif
132,T52SCH_20190403T021651_2019022.tif,2019022,1.00,중소형,1,T52SCH_20190403T021651_2019022_mask.tif
133,T52SCH_20190408T021609_2019030.tif,2019030,2.00,중소형,1,T52SCH_20190408T021609_2019030_mask.tif
134,T52SCH_20190508T021609_2019047.tif,2019047,1.00,중소형,1,T52SCH_20190508T021609_2019047_mask.tif
135,T52SCH_20190508T021609_2019048.tif,2019048,1.50,중소형,1,T52SCH_20190508T021609_2019048_mask.tif
136,T52SCH_20190523T021611_2019049.tif,2019049,2.00,중소형,1,T52SCH_20190523T021611_2019049_mask.tif
137,T52SCH_20200113T022039_2020001.tif,2020001,34.26,중소형,3,T52SCH_20200113T022039_2020001_mask.tif
138,T52SCH_20200118T022021_2020001.tif,2020001,34.26,중소형,3,T52SCH_20200118T022021_2020001_mask.tif
139,T52SCH_20200328T021601_2020011.tif,2020011,9.85,중소형,2,T52SCH_20200328T021601_2020011_mask.tif
140,T52SCH_20200402T021559_2020012.tif,2020012,2.11,중소형,1,T52SCH_20200402T021559_2020012_mask.tif
141,T52SCH_20200422T021559_2020023.tif,2020023,19.00,중소형,2,T52SCH_20200422T021559_2020023_mask.tif
142,T52SCH_20220102T022059_2021028.tif,2021028,4.00,중소형,1,T52SCH_20220102T022059_2021028_mask.tif
143,T52SCH_20220216T021751_2022008.tif,2022008,1.60,중소형,1,T52SCH_20220216T021751_2022008_mask.tif
144,T52SCH_20220417T021611_2022057.tif,2022057,1.60,중소형,1,T52SCH_20220417T021611_2022057_mask.tif
145,T52SCH_20220417T021611_2022062.tif,2022062,1.24,중소형,1,T52SCH_20220417T021611_2022062_mask.tif
146,T52SCH_20220417T021611_2022064.tif,2022064,3.30,중소형,1,T52SCH_20220417T021611_2022064_mask.tif
147,T52SDD_20180130T020919_2018004.tif,2018004,1.00,중소형,1,T52SDD_20180130T020919_2018004_mask.tif
148,T52SDD_20180224T020651_2018007.tif,2018007,1.50,중소형,1,T52SDD_20180224T020651_2018007_mask.tif
149,T52SDD_20190301T020651_2019008.tif,2019008,2.00,중소형,1,T52SDD_20190301T020651_2019008_mask.tif
150,T52SDD_20220208T020829_2022006.tif,2022006,1.03,중소형,1,T52SDD_20220208T020829_2022006_mask.tif
151,T52SDD_20220305T020701_2022019.tif,2022019,10.20,중소형,2,T52SDD_20220305T020701_2022019_mask.tif
152,T52SDD_20221230T021111_2022085.tif,2022085,2.00,중소형,1,T52SDD_20221230T021111_2022085_mask.tif
153,T52SDE_20170321T020651_2017004.tif,2017004,5.20,중소형,2,T52SDE_20170321T020651_2017004_mask.tif
154,T52SDE_20170430T020701_2017020.tif,2017020,1.25,중소형,1,T52SDE_20170430T020701_2017020_mask.tif
155,T52SDE_20170609T020651_2017032.tif,2017032,24.18,중소형,2,T52SDE_20170609T020651_2017032_mask.tif
156,T52SDE_20171221T021059_2017040.tif,2017040,1.50,중소형,1,T52SDE_20171221T021059_2017040_mask.tif
157,T52SDE_20180209T020829_2018006.tif,2018006,1.20,중소형,1,T52SDE_20180209T020829_2018006_mask.tif
158,T52SDE_20180219T020719_2018014.tif,2018014,1.00,중소형,1,T52SDE_20180219T020719_2018014_mask.tif
159,T52SDE_20180222T021709_2018015.tif,2018015,1.00,중소형,1,T52SDE_20180222T021709_2018015_mask.tif
160,T52SDE_20180408T021601_2018024.tif,2018024,16.10,중소형,2,T52SDE_20180408T021601_2018024_mask.tif
161,T52SDE_20180729T020649_2018030.tif,2018030,1.50,중소형,1,T52SDE_20180729T020649_2018030_mask.tif
162,T52SDE_20180801T021649_2018030.tif,2018030,1.50,중소형,1,T52SDE_20180801T021649_2018030_mask.tif
163,T52SDE_20190331T030651_2019016.tif,2019016,2.00,중소형,1,T52SDE_20190331T030651_2019016_mask.tif
164,T52SDE_20190405T020659_2019026.tif,2019026,1.00,중소형,1,T52SDE_20190405T020659_2019026_mask.tif
165,T52SDE_20190415T020659_2019036.tif,2019036,2.00,중소형,1,T52SDE_20190415T020659_2019036_mask.tif
166,T52SDE_20190530T020701_2019050.tif,2019050,1.00,중소형,1,T52SDE_20190530T020701_2019050_mask.tif
167,T52SDE_20220114T021041_2022001.tif,2022001,5.50,중소형,2,T52SDE_20220114T021041_2022001_mask.tif
168,T52SDE_20220203T020911_2022004.tif,2022004,1.45,중소형,1,T52SDE_20220203T020911_2022004_mask.tif
169,T52SDE_20220218T020729_2022009.tif,2022009,12.40,중소형,2,T52SDE_20220218T020729_2022009_mask.tif
170,T52SDE_20220218T020729_2022013.tif,2022013,8.53,중소형,2,T52SDE_20220218T020729_2022013_mask.tif
171,T52SDE_20220218T020729_2022014.tif,2022014,1.50,중소형,1,T52SDE_20220218T020729_2022014_mask.tif
172,T52SDE_20220303T021609_2022030.tif,2022030,813.89,대형,4,T52SDE_20220303T021609_2022030_mask.tif
173,T52SDE_20220305T020701_2022024.tif,2022024,88.63,중소형,3,T52SDE_20220305T020701_2022024_mask.tif
174,T52SDE_20220315T020701_2022024.tif,2022024,88.63,중소형,3,T52SDE_20220315T020701_2022024_mask.tif
175,T52SDE_20220305T020701_2022037.tif,2022037,6.54,중소형,2,T52SDE_20220305T020701_2022037_mask.tif
176,T52SDE_20220402T021559_2022048.tif,2022048,1.47,중소형,1,T52SDE_20220402T021559_2022048_mask.tif
177,T52SDE_20220417T021611_2022066.tif,2022066,9.69,중소형,2,T52SDE_20220417T021611_2022066_mask.tif
178,T52SDE_20220424T020701_2022067.tif,2022067,2.89,중소형,1,T52SDE_20220424T020701_2022067_mask.tif
179,T52SDE_20220424T020701_2022068.tif,2022068,3.18,중소형,1,T52SDE_20220424T020701_2022068_mask.tif
180,T52SDE_20220504T020701_2022074.tif,2022074,1.44,중소형,1,T52SDE_20220504T020701_2022074_mask.tif
181,T52SDE_20220522T021609_2022078.tif,2022078,3.00,중소형,1,T52SDE_20220522T021609_2022078_mask.tif
182,T52SDE_20220529T020659_2022080.tif,2022080,2.80,중소형,1,T52SDE_20220529T020659_2022080_mask.tif
183,T52SDE_20220603T020701_2022080.tif,2022080,2.80,중소형,1,T52SDE_20220603T020701_2022080_mask.tif
184,T52SDE_20220601T021559_2022082.tif,2022082,5.30,중소형,2,T52SDE_20220601T021559_2022082_mask.tif
185,T52SDE_20220603T020701_2022083.tif,2022083,660.82,대형,4,T52SDE_20220603T020701_2022083_mask.tif
186,T52SDF_20160215T021228_2016002.tif,2016002,1.50,중소형,1,T52SDF_20160215T021228_2016002_mask.tif
187,T52SDF_20160408T021612_2016009.tif,2016009,92.60,중소형,3,T52SDF_20160408T021612_2016009_mask.tif
188,T52SDF_20160408T021612_2016016.tif,2016016,66.50,중소형,3,T52SDF_20160408T021612_2016016_mask.tif
189,T52SDF_20160408T022530_2016006.tif,2016006,1.50,중소형,1,T52SDF_20160408T022530_2016006_mask.tif
190,T52SDF_20160408T022530_2016012.tif,2016012,4.00,중소형,1,T52SDF_20160408T022530_2016012_mask.tif
191,T52SDF_20160408T022530_2016024.tif,2016024,53.80,중소형,3,T52SDF_20160408T022530_2016024_mask.tif
192,T52SDF_20170314T022651_2017001.tif,2017001,2.00,중소형,1,T52SDF_20170314T022651_2017001_mask.tif
193,T52SDF_20170403T022701_2017001.tif,2017001,2.00,중소형,1,T52SDF_20170403T022701_2017001_mask.tif
194,T52SDF_20170410T020651_2017010.tif,2017010,2.20,중소형,1,T52SDF_20170410T020651_2017010_mask.tif
195,T52SDF_20170410T020651_2017011.tif,2017011,1.50,중소형,1,T52SDF_20170410T020651_2017011_mask.tif
196,T52SDF_20170520T020701_2017025.tif,2017025,1.50,중소형,1,T52SDF_20170520T020701_2017025_mask.tif
197,T52SDF_20170520T020701_2017028.tif,2017028,86.00,중소형,3,T52SDF_20170520T020701_2017028_mask.tif
198,T52SDF_20180202T021909_2018005.tif,2018005,1.00,중소형,1,T52SDF_20180202T021909_2018005_mask.tif
199,T52SDF_20180324T021559_2018017.tif,2018017,2.50,중소형,1,T52SDF_20180324T021559_2018017_mask.tif
200,T52SDF_20181002T020651_2018032.tif,2018032,31.90,중소형,3,T52SDF_20181002T020651_2018032_mask.tif
201,T52SDF_20190319T021659_2019014.tif,2019014,3.00,중소형,1,T52SDF_20190319T021659_2019014_mask.tif
202,T52SDF_20190324T021601_2019014.tif,2019014,3.00,중소형,1,T52SDF_20190324T021601_2019014_mask.tif
203,T52SDF_20190403T021651_2019015.tif,2019015,22.00,중소형,2,T52SDF_20190403T021651_2019015_mask.tif

In [246]:
new_df2.loc[new_df2['dataset']=='test']

,filename,maskfilename,산불ID,피해면적,규모구분(대형/중소형),규모구분(등급),dataset
4,T52SBE_20170413T021601_2017002.tif,T52SBE_20170413T021601_2017002_mask.tif,2017002,1.00,중소형,1,test
6,T52SBE_20220522T021609_2022077.tif,T52SBE_20220522T021609_2022077_mask.tif,2022077,2.50,중소형,1,test
12,T52SBG_20160508T022702_2016026.tif,T52SBG_20160508T022702_2016026_mask.tif,2016026,1.30,중소형,1,test
21,T52SBG_20200323T021559_2020006.tif,T52SBG_20200323T021559_2020006_mask.tif,2020006,2.68,중소형,1,test
24,T52SCD_20201208T022059_2020034.tif,T52SCD_20201208T022059_2020034_mask.tif,2020034,2.00,중소형,1,test
27,T52SCD_20210414T020649_2021020.tif,T52SCD_20210414T020649_2021020_mask.tif,2021020,1.40,중소형,1,test
29,T52SCD_20211228T022111_2021027.tif,T52SCD_20211228T022111_2021027_mask.tif,2021027,10.00,중소형,2,test
36,T52SCE_20180217T021741_2018012.tif,T52SCE_20180217T021741_2018012_mask.tif,2018012,3.00,중소형,1,test
37,T52SCE_20180821T021559_2018034.tif,T52SCE_20180821T021559_2018034_mask.tif,2018034,1.00,중소형,1,test
42,T52SCE_20210107T022059_2021001.tif,T52SCE_20210107T022059_2021001_mask.tif,2021001,3.00,중소형,1,test
56,T52SCF_20190408T021609_2019032.tif,T52SCF_20190408T021609_2019032_mask.tif,2019032,1.30,중소형,1,test
72,T52SCG_20160408T022530_2016013.tif,T52SCG_20160408T022530_2016013_mask.tif,2016013,1.00,중소형,1,test
82,T52SCG_20170413T021601_2017015.tif,T52SCG_20170413T021601_2017015_mask.tif,2017015,2.50,중소형,1,test
84,T52SCG_20170503T021611_2017021.tif,T52SCG_20170503T021611_2017021_mask.tif,2017021,1.00,중소형,1,test
99,T52SCG_20190413T021611_2019039.tif,T52SCG_20190413T021611_2019039_mask.tif,2019039,1.50,중소형,1,test
100,T52SCG_20190523T021611_2019045.tif,T52SCG_20190523T021611_2019045_mask.tif,2019045,1.50,중소형,1,test
102,T52SCG_20200402T021559_2020013.tif,T52SCG_20200402T021559_2020013_mask.tif,2020013,3.75,중소형,1,test
104,T52SCG_20200407T021601_2020014.tif,T52SCG_20200407T021601_2020014_mask.tif,2020014,6.20,중소형,2,test
108,T52SCG_20200527T021611_2020022.tif,T52SCG_20200527T021611_2020022_mask.tif,2020022,2.75,중소형,1,test
111,T52SCG_20220226T021651_2022018.tif,T52SCG_20220226T021651_2022018_mask.tif,2022018,3.00,중소형,1,test
113,T52SCG_20220308T021611_2022040.tif,T52SCG_20220308T021611_2022040_mask.tif,2022040,8.00,중소형,2,test
115,T52SCG_20220407T021601_2022050.tif,T52SCG_20220407T021601_2022050_mask.tif,2022050,8.00,중소형,2,test
121,T52SCH_20160408T021612_2016007.tif,T52SCH_20160408T021612_2016007_mask.tif,2016007,2.00,중소형,1,test
122,T52SCH_20160408T022530_2016010.tif,T52SCH_20160408T022530_2016010_mask.tif,2016010,1.50,중소형,1,test
135,T52SCH_20190508T021609_2019048.tif,T52SCH_20190508T021609_2019048_mask.tif,2019048,1.50,중소형,1,test
142,T52SCH_20220102T022059_2021028.tif,T52SCH_20220102T022059_2021028_mask.tif,2021028,4.00,중소형,1,test
143,T52SCH_20220216T021751_2022008.tif,T52SCH_20220216T021751_2022008_mask.tif,2022008,1.60,중소형,1,test
148,T52SDD_20180224T020651_2018007.tif,T52SDD_20180224T020651_2018007_mask.tif,2018007,1.50,중소형,1,test
157,T52SDE_20180209T020829_2018006.tif,T52SDE_20180209T020829_2018006_mask.tif,2018006,1.20,중소형,1,test
158,T52SDE_20180219T020719_2018014.tif,T52SDE_20180219T020719_2018014_mask.tif,2018014,1.00,중소형,1,test
159,T52SDE_20180222T021709_2018015.tif,T52SDE_20180222T021709_2018015_mask.tif,2018015,1.00,중소형,1,test
160,T52SDE_20180408T021601_2018024.tif,T52SDE_20180408T021601_2018024_mask.tif,2018024,16.10,중소형,2,test
165,T52SDE_20190415T020659_2019036.tif,T52SDE_20190415T020659_2019036_mask.tif,2019036,2.00,중소형,1,test
166,T52SDE_20190530T020701_2019050.tif,T52SDE_20190530T020701_2019050_mask.tif,2019050,1.00,중소형,1,test
167,T52SDE_20220114T021041_2022001.tif,T52SDE_20220114T021041_2022001_mask.tif,2022001,5.50,중소형,2,test
173,T52SDE_20220305T020701_2022024.tif,T52SDE_20220305T020701_2022024_mask.tif,2022024,88.63,중소형,3,test
177,T52SDE_20220417T021611_2022066.tif,T52SDE_20220417T021611_2022066_mask.tif,2022066,9.69,중소형,2,test
197,T52SDF_20170520T020701_2017028.tif,T52SDF_20170520T020701_2017028_mask.tif,2017028,86.00,중소형,3,test
205,T52SDF_20190403T021651_2019018.tif,T52SDF_20190403T021651_2019018_mask.tif,2019018,1.00,중소형,1,test
206,T52SDF_20190408T021609_2019038.tif,T52SDF_20190408T021609_2019038_mask.tif,2019038,1.00,중소형,1,test
207,T52SDF_20190415T020659_2019019.tif,T52SDF_20190415T020659_2019019_mask.tif,2019019,18.44,중소형,2,test
228,T52SDF_20220419T020649_2022063.tif,T52SDF_20220419T020649_2022063_mask.tif,2022063,225.72,대형,4,test
231,T52SDG_20160218T022652_2016003.tif,T52SDG_20160218T022652_2016003_mask.tif,2016003,3.00,중소형,1,test
239,T52SDG_20170520T020701_2017027.tif,T52SDG_20170520T020701_2017027_mask.tif,2017027,252.00,대형,4,test
244,T52SDG_20190415T020659_2019027.tif,T52SDG_20190415T020659_2019027_mask.tif,2019027,1260.15,대형,5,test
253,T52SDG_20210213T020809_2021005.tif,T52SDG_20210213T020809_2021005_mask.tif,2021005,3.70,중소형,1,test
256,T52SDG_20210223T020659_2021009.tif,T52SDG_20210223T020659_2021009_mask.tif,2021009,24.56,중소형,2,test
258,T52SDG_20210402T021601_2021016.tif,T52SDG_20210402T021601_2021016_mask.tif,2021016,20.00,중소형,2,test
264,T52SDG_20220305T020701_2022035.tif,T52SDG_20220305T020701_2022035_mask.tif,2022035,184.01,대형,4,test
270,T52SDG_20220524T020701_2022076.tif,T52SDG_20220524T020701_2022076_mask.tif,2022076,2.25,중소형,1,test
272,T52SDH_20160408T022530_2016014.tif,T52SDH_20160408T022530_2016014_mask.tif,2016014,14.40,중소형,2,test
275,T52SDH_20180331T020649_2018021.tif,T52SDH_20180331T020649_2018021_mask.tif,2018021,356.85,대형,4,test
278,T52SDH_20190103T022101_2019001.tif,T52SDH_20190103T022101_2019001_mask.tif,2019001,97.94,중소형,3,test
281,T52SDH_20190405T020659_2019028.tif,T52SDH_20190405T020659_2019028_mask.tif,2019028,1266.62,대형,5,test
289,T52SDH_20220228T020649_2022025.tif,T52SDH_20220228T020649_2022025_mask.tif,2022025,8.69,중소형,2,test
291,T52SDH_20220417T021611_2022060.tif,T52SDH_20220417T021611_2022060_mask.tif,2022060,716.31,대형,4,test
295,T52SEE_20171231T021059_2017041.tif,T52SEE_20171231T021059_2017041_mask.tif,2017041,3.00,중소형,1,test
298,T52SEE_20180326T020651_2018016.tif,T52SEE_20180326T020651_2018016_mask.tif,2018016,1.40,중소형,1,test
299,T52SEE_20180326T020651_2018019.tif,T52SEE_20180326T020651_2018019_mask.tif,2018019,1.20,중소형,1,test
301,T52SEE_20180714T020651_2018029.tif,T52SEE_20180714T020651_2018029_mask.tif,2018029,3.00,중소형,1,test
309,T52SEE_20190415T020659_2019037.tif,T52SEE_20190415T020659_2019037_mask.tif,2019037,2.00,중소형,1,test
314,T52SEE_20200325T020651_2020008.tif,T52SEE_20200325T020651_2020008_mask.tif,2020008,10.59,중소형,2,test
316,T52SEE_20210119T021021_2021002.tif,T52SEE_20210119T021021_2021002_mask.tif,2021002,4.00,중소형,1,test
320,T52SEE_20220305T020701_2022029.tif,T52SEE_20220305T020701_2022029_mask.tif,2022029,2.00,중소형,1,test
322,T52SEE_20220310T020649_2022031.tif,T52SEE_20220310T020649_2022031_mask.tif,2022031,20.00,중소형,2,test
324,T52SEE_20220404T020701_2022044.tif,T52SEE_20220404T020701_2022044_mask.tif,2022044,1.16,중소형,1,test
326,T52SEE_20220419T020649_2022065.tif,T52SEE_20220419T020649_2022065_mask.tif,2022065,2.00,중소형,1,test
331,T52SEF_20180331T020649_2018020.tif,T52SEF_20180331T020649_2018020_mask.tif,2018020,12.40,중소형,2,test
342,T52SEG_20180219T020719_2018009.tif,T52SEG_20180219T020719_2018009_mask.tif,2018009,76.46,중소형,3,test
347,T52SEG_20220305T020701_2022036.tif,T52SEG_20220305T020701_2022036_mask.tif,2022036,16301.98,대형,5,test
351,T52SEG_20220419T020649_2022059.tif,T52SEG_20220419T020649_2022059_mask.tif,2022059,3.00,중소형,1,test

In [247]:
os.getcwd()

'D:\\deep_learning\\Sentinel_forestfire\\MY_TEST_SENTINEL_IMAGERY_DATA\\imagery_data_complete_0828\\data\\mask'

In [248]:
os.chdir('../')

In [249]:
os.getcwd()

'D:\\deep_learning\\Sentinel_forestfire\\MY_TEST_SENTINEL_IMAGERY_DATA\\imagery_data_complete_0828\\data'

In [250]:
image_source_folder = 'image'
mask_source_folder = 'mask'

In [251]:
train_dest_folder = '../train'
test_dest_folder = '../test'
val_dest_folder = '../val'

In [252]:
for index, row in tqdm(new_df2.iterrows(), total = new_df2.shape[0]):
    fname = row['filename']
    mname = row['maskfilename']
    dataset = row['dataset']
    
    source_image_path = os.path.join(image_source_folder, fname)
    source_mask_path = os.path.join(mask_source_folder, mname)
    
    if dataset == 'train':
        destination_image_folder = train_dest_folder
        destination_mask_folder = train_dest_folder
    elif dataset =='val':
        destination_image_folder = val_dest_folder
        destination_mask_folder = val_dest_folder
    elif dataset =='test':
        destination_image_folder = test_dest_folder
        destination_mask_folder = test_dest_folder
    else:
        print(f"Invalid dataset label: {dataset}")
        continue
        
    destination_image_path = os.path.join(destination_image_folder, 'image', fname)
    destination_mask_path = os.path.join(destination_mask_folder, 'mask' ,mname)
    
    #shutil.copy(source_image_path, destination_image_path)
    shutil.copy(source_mask_path, destination_mask_path)
    
print('FIle copying completed.')

100%|████████████████████████████████████████████████████████████████████████████████| 353/353 [00:04<00:00, 74.43it/s]

FIle copying completed.

In [53]:
os.getcwd()

'D:\\deep_learning\\Sentinel_forestfire\\MY_TEST_SENTINEL_IMAGERY_DATA\\imagery_data_complete_0828\\data\\mask'

In [ ]:
# 옮기려는 파일 자체는 동일하니, 폐기된 mask 폴더에서 이름 불러와서 동일한 파일 이름인 것을 복붙하도록

In [39]:
source_masks = glob('*.tif')

In [51]:
source_masks[0]

'T51SYU_20220226T021651_2022027_mask.tif'

In [41]:
len(source_masks)

353

In [47]:
target_val_masks = glob('../../val/mask(폐기)/*.tif')

In [50]:
target_val_masks[0][19:]

'T51SYU_20220226T021651_2022027_mask.tif'

In [54]:
target_dest_folder = '../../val/mask'

In [55]:
for mask in source_masks:
    for target in target_val_masks:
        if mask == target[19:]:
            target_mask_name = target[19:]
            
            
            shutil.copy(mask, os.path.join(target_dest_folder, target_mask_name))

In [56]:
target_train_masks= glob('../../train/mask(폐기)/*.tif')
target_dest_folder= '../../train/mask'

In [62]:
target_train_masks[0][21:]

'T52SBC_20200427T021611_2020027_mask.tif'

In [64]:
for mask in source_masks:
    for target in target_train_masks:
        if mask == target[21:]:
            target_mask_name = target[21:]
            
            
            shutil.copy(mask, os.path.join(target_dest_folder, target_mask_name))

In [65]:
target_test_masks= glob('../../test/mask(폐기)/*.tif')
target_dest_folder= '../../test/mask'

In [68]:
target_test_masks[0][20:]

'T52SBE_20170413T021601_2017002_mask.tif'

In [67]:
for mask in source_masks:
    for target in target_test_masks:
        if mask == target[20:]:
            target_mask_name = target[20:]
            
            
            shutil.copy(mask, os.path.join(target_dest_folder, target_mask_name))